In [ ]:
import os
import pandas as pd
import re
import numpy as np
from dotenv import load_dotenv
import os
load_dotenv()  
pd.set_option('display.max_rows', None)


''' To upload SG files do the following: 
1. go to pga.com site and go to stats site, then to the SG:Total 
2. Save the file as SG_[tourneyID]_[year].csv 
3. Save the file to the /Users/brandon/Desktop/Golf_Data/upload_staging/data_for_upload/ folder 

Other info: 
4. the process should create a merged file (this can be deleted at some point) in the folder 

'''

# Base folder path
SG_CSV_PATH = os.getenv("SG_CSV_PATH")
JOIN_FILE_CSV_PATH = os.getenv("JOIN_FILE_CSV_PATH")


# Load the file to join
main_df = pd.read_csv(JOIN_FILE_CSV_PATH)
main_df = main_df[['TourneyID', 'Tournament', 'Week_Of_Season', 'Course', 'Signature_Event', 'Major_Event', 'par']]

# --- Parse ID and Year from filename ---
def parse_id_and_year(filename):
    match = re.match(r'.*_(\d+)_(\d{4})\.csv', filename)
    if match:
        return match.group(1), match.group(2)
    return None, None


# --- Identify Leader Files ---
leader_files = [
    f for f in os.listdir(SG_CSV_PATH)
    if f.startswith('sg') and f.endswith('.csv')
]

In [2]:
# --- Process Each Leader File ---
for leader_file in leader_files:
    tourney_id, year = parse_id_and_year(leader_file)
    if not tourney_id:
        continue

    print(f"Processing SG file: {leader_file} (TourneyID={tourney_id}, year={year})")

    # Load leader file
    leader_path = os.path.join(SG_CSV_PATH, leader_file)
    leader_df = pd.read_csv(leader_path)
    leader_df['TourneyID'] = int(tourney_id)
    leader_df['year'] = year

    # Join metadata (left join on tourneyID)
    enriched_df = leader_df.merge(main_df, on='TourneyID', how='left')

    # Remove blank rows
    enriched_df.dropna(how='all', inplace=True)

    # Trim spaces from column names in join file
    enriched_df.columns = enriched_df.columns.str.strip()

    # Trim spaces from string values in join file
    enriched_df = enriched_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)



    # Save output

Processing SG file: sg_23_2026.csv (TourneyID=23, year=2026)

In [3]:
tourney_file_name = enriched_df['Tournament'].unique().tolist()
print(tourney_file_name)

['THE PLAYERS Championship']

In [ ]:
# Need to re-do postgres creds 
from dotenv import load_dotenv


# Load environment variables from .env file
load_dotenv()

# Database configuration from environment variables
db_config = {
    'host': os.getenv('DB_HOST'),
    'database': os.getenv('DB_NAME'),
    'user': os.getenv('DB_USER'),
    'password': os.getenv('DB_PASSWORD'),
    'port': os.getenv('DB_PORT', '5432')
}
schema = os.getenv('DB_SCHEMA')

# Test the connection
try:
    conn = psycopg2.connect(**db_config)
    conn.close()
    print("✅ Database connection successful!")
    print(f"   Connected to: {db_config['database']} on {db_config['host']}")
except Exception as e:
    print(f"❌ Connection failed: {e}")

✅ Database connection successful!
   Connected to: brdb on localhost

In [6]:
# Target table name
table_name = 'sg_data'

In [7]:
#adding 2 null cols for Movement and PlayerID 
enriched_df['MOVEMENT'] = np.nan
#enriched_df['PLAYER_ID'] = np.nan
enriched_df['PLAYER_ID'] = None
#enriched_df['PLAYER_ID'] = pd.to_numeric(enriched_df['PLAYER_ID'], errors='coerce').astype('Int64')
#enriched_df = enriched_df.where(pd.notna(enriched_df), None)


#enriched_df['MOVEMENT'] = pd.Series([np.nan] * len(enriched_df), dtype='Int64')  # note the capital 'I'
#enriched_df['PLAYER_ID'] = pd.Series([np.nan] * len(enriched_df), dtype='Int64')  # note the capital 'I'


# reorder cols 
enriched_df = enriched_df[['Rank', 'MOVEMENT', 'PLAYER_ID', 'Player','Avg', 'Total SG:T', 'Total SG:T2G'
                           , 'Total SG:P', 'Measured Rounds','TourneyID','year','Tournament'
                           , 'Week_Of_Season' , 'Course','Signature_Event','Major_Event','par']]

In [8]:
enriched_df

,Rank,MOVEMENT,PLAYER_ID,Player,Avg,Total SG:T,Total SG:T2G,Total SG:P,Measured Rounds,TourneyID,year,Tournament,Week_Of_Season,Course,Signature_Event,Major_Event,par
0,1,NaN,None,Cameron Young,3.663,14.653,9.840,4.813,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
1,2,NaN,None,Matt Fitzpatrick,3.413,13.653,12.171,1.482,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
2,3,NaN,None,Xander Schauffele,3.163,12.653,9.989,2.664,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
3,4,NaN,None,Robert MacIntyre,2.913,11.653,7.065,4.588,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
4,5,NaN,None,Ludvig Åberg,2.663,10.653,9.234,1.419,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
5,5,NaN,None,Jacob Bridgeman,2.663,10.653,0.902,9.751,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
6,5,NaN,None,Sudarshan Yellamaraju,2.663,10.653,5.152,5.501,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
7,8,NaN,None,Tommy Fleetwood,2.413,9.653,12.391,-2.738,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
8,8,NaN,None,Sepp Straka,2.413,9.653,7.090,2.563,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
9,8,NaN,None,Justin Thomas,2.413,9.653,5.385,4.268,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
10,11,NaN,None,Brian Harman,2.163,8.653,8.928,-0.275,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
11,11,NaN,None,Patrick Rodgers,2.163,8.653,5.950,2.703,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
12,13,NaN,None,Akshay Bhatia,1.913,7.653,6.901,0.752,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
13,13,NaN,None,Sam Burns,1.913,7.653,-0.038,7.691,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
14,13,NaN,None,Corey Conners,1.913,7.653,7.186,0.467,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
15,13,NaN,None,Russell Henley,1.913,7.653,4.966,2.687,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
16,13,NaN,None,Ryo Hisatsune,1.913,7.653,10.759,-3.106,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
17,13,NaN,None,Viktor Hovland,1.913,7.653,7.043,0.610,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
18,13,NaN,None,Brooks Koepka,1.913,7.653,8.808,-1.155,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
19,13,NaN,None,Justin Rose,1.913,7.653,4.530,3.123,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
20,13,NaN,None,Austin Smotherman,1.913,7.653,9.278,-1.625,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
21,22,NaN,None,Scottie Scheffler,1.663,6.653,4.469,2.184,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
22,22,NaN,None,Michael Thorbjornsen,1.663,6.653,5.677,0.976,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
23,24,NaN,None,William Mouw,1.413,5.653,4.219,1.434,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
24,24,NaN,None,Alex Smalley,1.413,5.653,3.336,2.317,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
25,24,NaN,None,J.J. Spaun,1.413,5.653,3.844,1.809,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
26,27,NaN,None,Ryan Gerard,1.163,4.653,2.718,1.935,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
27,27,NaN,None,Nicolai Højgaard,1.163,4.653,-0.892,5.545,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
28,27,NaN,None,Chris Kirk,1.163,4.653,5.819,-1.166,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
29,27,NaN,None,Hideki Matsuyama,1.163,4.653,2.387,2.266,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
30,27,NaN,None,Chad Ramey,1.163,4.653,2.247,2.406,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
31,32,NaN,None,Patrick Cantlay,0.913,3.653,3.213,0.440,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
32,32,NaN,None,Bud Cauley,0.913,3.653,5.536,-1.883,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
33,32,NaN,None,Eric Cole,0.913,3.653,-1.234,4.887,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
34,32,NaN,None,Max Homa,0.913,3.653,1.256,2.397,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
35,32,NaN,None,Min Woo Lee,0.913,3.653,2.201,1.452,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
36,32,NaN,None,Maverick McNealy,0.913,3.653,0.782,2.871,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
37,32,NaN,None,Alex Noren,0.913,3.653,0.782,2.871,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
38,32,NaN,None,Andrew Putnam,0.913,3.653,4.903,-1.250,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
39,32,NaN,None,Jordan Spieth,0.913,3.653,5.989,-2.336,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
40,32,NaN,None,Sahith Theegala,0.913,3.653,2.224,1.429,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
41,42,NaN,None,Wyndham Clark,0.663,2.653,4.578,-1.925,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
42,42,NaN,None,Rickie Fowler,0.663,2.653,0.457,2.196,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
43,42,NaN,None,Joe Highsmith,0.663,2.653,1.277,1.376,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
44,42,NaN,None,Nick Taylor,0.663,2.653,6.511,-3.858,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
45,46,NaN,None,Rory McIlroy,0.413,1.653,7.023,-5.370,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
46,46,NaN,None,Keith Mitchell,0.413,1.653,2.001,-0.348,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
47,46,NaN,None,Taylor Pendrith,0.413,1.653,5.996,-4.343,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
48,46,NaN,None,Matti Schmid,0.413,1.653,-1.140,2.793,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
49,50,NaN,None,Zach Bauchou,0.163,0.653,1.688,-1.035,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
50,50,NaN,None,Keegan Bradley,0.163,0.653,-4.528,5.181,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
51,50,NaN,None,Si Woo Kim,0.163,0.653,0.083,0.570,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
52,50,NaN,None,Max McGreevy,0.163,0.653,0.138,0.515,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
53,50,NaN,None,Taylor Moore,0.163,0.653,0.993,-0.340,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
54,50,NaN,None,J.T. Poston,0.163,0.653,-2.659,3.312,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
55,56,NaN,None,Chris Gotterup,-0.087,-0.347,-0.573,0.226,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
56,56,NaN,None,Adam Scott,-0.087,-0.347,1.991,-2.338,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
57,58,NaN,None,Sam Stevens,-0.337,-1.347,4.152,-5.499,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
58,59,NaN,None,Jason Day,-0.587,-2.347,0.260,-2.607,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
59,59,NaN,None,Lee Hodges,-0.587,-2.347,-5.588,3.241,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
60,59,NaN,None,Kevin Roy,-0.587,-2.347,0.840,-3.187,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
61,62,NaN,None,Steven Fisk,-0.837,-3.347,-4.339,0.992,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
62,62,NaN,None,Rico Hoey,-0.837,-3.347,-6.954,3.607,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
63,62,NaN,None,Stephan Jaeger,-0.837,-3.347,-6.997,3.650,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
64,62,NaN,None,Danny Walker,-0.837,-3.347,-4.487,1.140,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
65,66,NaN,None,Daniel Berger,-1.087,-4.347,-4.970,0.623,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
66,66,NaN,None,Nico Echavarria,-1.087,-4.347,-3.999,-0.348,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
67,66,NaN,None,Kristoffer Reitan,-1.087,-4.347,-4.900,0.553,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
68,69,NaN,None,Michael Brennan,-1.337,-5.347,-1.697,-3.650,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
69,70,NaN,None,Ricky Castillo,-1.587,-6.347,-4.017,-2.330,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
70,70,NaN,None,Tony Finau,-1.587,-6.347,-3.901,-2.446,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
71,70,NaN,None,Seamus Power,-1.587,-6.347,-1.929,-4.418,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
72,73,NaN,None,Takumi Kanaya,-2.087,-8.347,-7.009,-1.338,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0

In [9]:
df = enriched_df.rename(columns={'Rank': 'Rank', 'MOVEMENT': 'Movement', 
                            'PLAYER_ID': 'PlayerID', 'Player': 'Player', 'Total SG:T': 'Total_SG_T'
                            , 'Total SG:T2G': 'Total_SG_T2G', 'Total SG:P':'Total_SG_P'
                            , 'Measured Rounds':'Measured_Rounds' })

df = df.dropna(subset=df.columns[:7], how='all')

columns_to_clean = ['par', 'Week_Of_Season', 'year','Rank','Measured_Rounds'] # removing Player_ID since its null/blank



#print(df.head())

In [10]:
df

,Rank,Movement,PlayerID,Player,Avg,Total_SG_T,Total_SG_T2G,Total_SG_P,Measured_Rounds,TourneyID,year,Tournament,Week_Of_Season,Course,Signature_Event,Major_Event,par
0,1,NaN,None,Cameron Young,3.663,14.653,9.840,4.813,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
1,2,NaN,None,Matt Fitzpatrick,3.413,13.653,12.171,1.482,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
2,3,NaN,None,Xander Schauffele,3.163,12.653,9.989,2.664,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
3,4,NaN,None,Robert MacIntyre,2.913,11.653,7.065,4.588,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
4,5,NaN,None,Ludvig Åberg,2.663,10.653,9.234,1.419,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
5,5,NaN,None,Jacob Bridgeman,2.663,10.653,0.902,9.751,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
6,5,NaN,None,Sudarshan Yellamaraju,2.663,10.653,5.152,5.501,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
7,8,NaN,None,Tommy Fleetwood,2.413,9.653,12.391,-2.738,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
8,8,NaN,None,Sepp Straka,2.413,9.653,7.090,2.563,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
9,8,NaN,None,Justin Thomas,2.413,9.653,5.385,4.268,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
10,11,NaN,None,Brian Harman,2.163,8.653,8.928,-0.275,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
11,11,NaN,None,Patrick Rodgers,2.163,8.653,5.950,2.703,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
12,13,NaN,None,Akshay Bhatia,1.913,7.653,6.901,0.752,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
13,13,NaN,None,Sam Burns,1.913,7.653,-0.038,7.691,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
14,13,NaN,None,Corey Conners,1.913,7.653,7.186,0.467,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
15,13,NaN,None,Russell Henley,1.913,7.653,4.966,2.687,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
16,13,NaN,None,Ryo Hisatsune,1.913,7.653,10.759,-3.106,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
17,13,NaN,None,Viktor Hovland,1.913,7.653,7.043,0.610,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
18,13,NaN,None,Brooks Koepka,1.913,7.653,8.808,-1.155,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
19,13,NaN,None,Justin Rose,1.913,7.653,4.530,3.123,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
20,13,NaN,None,Austin Smotherman,1.913,7.653,9.278,-1.625,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
21,22,NaN,None,Scottie Scheffler,1.663,6.653,4.469,2.184,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
22,22,NaN,None,Michael Thorbjornsen,1.663,6.653,5.677,0.976,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
23,24,NaN,None,William Mouw,1.413,5.653,4.219,1.434,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
24,24,NaN,None,Alex Smalley,1.413,5.653,3.336,2.317,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
25,24,NaN,None,J.J. Spaun,1.413,5.653,3.844,1.809,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
26,27,NaN,None,Ryan Gerard,1.163,4.653,2.718,1.935,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
27,27,NaN,None,Nicolai Højgaard,1.163,4.653,-0.892,5.545,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
28,27,NaN,None,Chris Kirk,1.163,4.653,5.819,-1.166,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
29,27,NaN,None,Hideki Matsuyama,1.163,4.653,2.387,2.266,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
30,27,NaN,None,Chad Ramey,1.163,4.653,2.247,2.406,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
31,32,NaN,None,Patrick Cantlay,0.913,3.653,3.213,0.440,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
32,32,NaN,None,Bud Cauley,0.913,3.653,5.536,-1.883,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
33,32,NaN,None,Eric Cole,0.913,3.653,-1.234,4.887,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
34,32,NaN,None,Max Homa,0.913,3.653,1.256,2.397,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
35,32,NaN,None,Min Woo Lee,0.913,3.653,2.201,1.452,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
36,32,NaN,None,Maverick McNealy,0.913,3.653,0.782,2.871,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
37,32,NaN,None,Alex Noren,0.913,3.653,0.782,2.871,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
38,32,NaN,None,Andrew Putnam,0.913,3.653,4.903,-1.250,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
39,32,NaN,None,Jordan Spieth,0.913,3.653,5.989,-2.336,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
40,32,NaN,None,Sahith Theegala,0.913,3.653,2.224,1.429,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
41,42,NaN,None,Wyndham Clark,0.663,2.653,4.578,-1.925,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
42,42,NaN,None,Rickie Fowler,0.663,2.653,0.457,2.196,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
43,42,NaN,None,Joe Highsmith,0.663,2.653,1.277,1.376,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
44,42,NaN,None,Nick Taylor,0.663,2.653,6.511,-3.858,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
45,46,NaN,None,Rory McIlroy,0.413,1.653,7.023,-5.370,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
46,46,NaN,None,Keith Mitchell,0.413,1.653,2.001,-0.348,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
47,46,NaN,None,Taylor Pendrith,0.413,1.653,5.996,-4.343,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
48,46,NaN,None,Matti Schmid,0.413,1.653,-1.140,2.793,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
49,50,NaN,None,Zach Bauchou,0.163,0.653,1.688,-1.035,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
50,50,NaN,None,Keegan Bradley,0.163,0.653,-4.528,5.181,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
51,50,NaN,None,Si Woo Kim,0.163,0.653,0.083,0.570,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
52,50,NaN,None,Max McGreevy,0.163,0.653,0.138,0.515,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
53,50,NaN,None,Taylor Moore,0.163,0.653,0.993,-0.340,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
54,50,NaN,None,J.T. Poston,0.163,0.653,-2.659,3.312,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
55,56,NaN,None,Chris Gotterup,-0.087,-0.347,-0.573,0.226,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
56,56,NaN,None,Adam Scott,-0.087,-0.347,1.991,-2.338,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
57,58,NaN,None,Sam Stevens,-0.337,-1.347,4.152,-5.499,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
58,59,NaN,None,Jason Day,-0.587,-2.347,0.260,-2.607,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
59,59,NaN,None,Lee Hodges,-0.587,-2.347,-5.588,3.241,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
60,59,NaN,None,Kevin Roy,-0.587,-2.347,0.840,-3.187,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
61,62,NaN,None,Steven Fisk,-0.837,-3.347,-4.339,0.992,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
62,62,NaN,None,Rico Hoey,-0.837,-3.347,-6.954,3.607,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
63,62,NaN,None,Stephan Jaeger,-0.837,-3.347,-6.997,3.650,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
64,62,NaN,None,Danny Walker,-0.837,-3.347,-4.487,1.140,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
65,66,NaN,None,Daniel Berger,-1.087,-4.347,-4.970,0.623,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
66,66,NaN,None,Nico Echavarria,-1.087,-4.347,-3.999,-0.348,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
67,66,NaN,None,Kristoffer Reitan,-1.087,-4.347,-4.900,0.553,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
68,69,NaN,None,Michael Brennan,-1.337,-5.347,-1.697,-3.650,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
69,70,NaN,None,Ricky Castillo,-1.587,-6.347,-4.017,-2.330,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
70,70,NaN,None,Tony Finau,-1.587,-6.347,-3.901,-2.446,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
71,70,NaN,None,Seamus Power,-1.587,-6.347,-1.929,-4.418,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0
72,73,NaN,None,Takumi Kanaya,-2.087,-8.347,-7.009,-1.338,4,23,2026,THE PLAYERS Championship,11.0,TPC Sawgrass,N,N,72.0

In [11]:
df.drop(columns=['TourneyID'], inplace=True)

In [12]:
for col in columns_to_clean:
    df[col] = df[col].apply(lambda x: None if pd.isna(x) else int(x))

In [ ]:
#df = df.dropna(subset=['pos'])
#df = df.dropna(how='all')

In [ ]:
df

In [13]:
conn = psycopg2.connect(**db_config)
cur = conn.cursor()
for _, row in df.iterrows():
    columns = ', '.join(df.columns)
    placeholders = ', '.join(['%s'] * len(row))
    insert_sql = f"INSERT INTO {schema}.{table_name} ({columns}) VALUES ({placeholders})"
    
    # DEBUG: print the row and data types
    print("Row data:", row.to_dict())

    try:
        cur.execute(insert_sql, tuple(row))
    except Exception as e:
        print("Error on row:", row.to_dict())
        print("Data types:", [type(x) for x in row])
        raise e  # re-raise to stop execution

    #cur.execute(insert_sql, tuple(row))
        
    conn.commit()
    print(f"Inserted data from {tourney_file_name} into {table_name}")

Row data: {'Rank': 1, 'Movement': nan, 'PlayerID': None, 'Player': 'Cameron Young', 'Avg': 3.663, 'Total_SG_T': 14.653, 'Total_SG_T2G': 9.84, 'Total_SG_P': 4.813, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 2, 'Movement': nan, 'PlayerID': None, 'Player': 'Matt Fitzpatrick', 'Avg': 3.413, 'Total_SG_T': 13.653, 'Total_SG_T2G': 12.171, 'Total_SG_P': 1.482, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 3, 'Movement': nan, 'PlayerID': None, 'Player': 'Xander Schauffele', 'Avg': 3.163, 'Total_SG_T': 12.653, 'Total_SG_T2G': 9.989, 'Total_SG_P': 2.664, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 4, 'Movement': nan, 'PlayerID': None, 'Player': 'Robert MacIntyre', 'Avg': 2.913, 'Total_SG_T': 11.653, 'Total_SG_T2G': 7.065, 'Total_SG_P': 4.588, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 5, 'Movement': nan, 'PlayerID': None, 'Player': 'Ludvig Åberg', 'Avg': 2.663, 'Total_SG_T': 10.653, 'Total_SG_T2G': 9.234, 'Total_SG_P': 1.419, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 5, 'Movement': nan, 'PlayerID': None, 'Player': 'Jacob Bridgeman', 'Avg': 2.663, 'Total_SG_T': 10.653, 'Total_SG_T2G': 0.902, 'Total_SG_P': 9.751, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 5, 'Movement': nan, 'PlayerID': None, 'Player': 'Sudarshan Yellamaraju', 'Avg': 2.663, 'Total_SG_T': 10.653, 'Total_SG_T2G': 5.152, 'Total_SG_P': 5.501, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 8, 'Movement': nan, 'PlayerID': None, 'Player': 'Tommy Fleetwood', 'Avg': 2.413, 'Total_SG_T': 9.653, 'Total_SG_T2G': 12.391, 'Total_SG_P': -2.738, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 8, 'Movement': nan, 'PlayerID': None, 'Player': 'Sepp Straka', 'Avg': 2.413, 'Total_SG_T': 9.653, 'Total_SG_T2G': 7.09, 'Total_SG_P': 2.563, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 8, 'Movement': nan, 'PlayerID': None, 'Player': 'Justin Thomas', 'Avg': 2.413, 'Total_SG_T': 9.653, 'Total_SG_T2G': 5.385, 'Total_SG_P': 4.268, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 11, 'Movement': nan, 'PlayerID': None, 'Player': 'Brian Harman', 'Avg': 2.163, 'Total_SG_T': 8.653, 'Total_SG_T2G': 8.928, 'Total_SG_P': -0.275, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 11, 'Movement': nan, 'PlayerID': None, 'Player': 'Patrick Rodgers', 'Avg': 2.163, 'Total_SG_T': 8.653, 'Total_SG_T2G': 5.95, 'Total_SG_P': 2.703, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Akshay Bhatia', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 6.901, 'Total_SG_P': 0.752, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Sam Burns', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': -0.038, 'Total_SG_P': 7.691, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Corey Conners', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 7.186, 'Total_SG_P': 0.467, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Russell Henley', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 4.966, 'Total_SG_P': 2.687, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Ryo Hisatsune', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 10.759, 'Total_SG_P': -3.106, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Viktor Hovland', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 7.043, 'Total_SG_P': 0.61, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Brooks Koepka', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 8.808, 'Total_SG_P': -1.155, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Justin Rose', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 4.53, 'Total_SG_P': 3.123, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Austin Smotherman', 'Avg': 1.913, 'Total_SG_T': 7.653, 'Total_SG_T2G': 9.278, 'Total_SG_P': -1.625, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 22, 'Movement': nan, 'PlayerID': None, 'Player': 'Scottie Scheffler', 'Avg': 1.663, 'Total_SG_T': 6.653, 'Total_SG_T2G': 4.469, 'Total_SG_P': 2.184, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 22, 'Movement': nan, 'PlayerID': None, 'Player': 'Michael Thorbjornsen', 'Avg': 1.663, 'Total_SG_T': 6.653, 'Total_SG_T2G': 5.677, 'Total_SG_P': 0.976, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 24, 'Movement': nan, 'PlayerID': None, 'Player': 'William Mouw', 'Avg': 1.413, 'Total_SG_T': 5.653, 'Total_SG_T2G': 4.219, 'Total_SG_P': 1.434, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 24, 'Movement': nan, 'PlayerID': None, 'Player': 'Alex Smalley', 'Avg': 1.413, 'Total_SG_T': 5.653, 'Total_SG_T2G': 3.336, 'Total_SG_P': 2.317, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 24, 'Movement': nan, 'PlayerID': None, 'Player': 'J.J. Spaun', 'Avg': 1.413, 'Total_SG_T': 5.653, 'Total_SG_T2G': 3.844, 'Total_SG_P': 1.809, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 27, 'Movement': nan, 'PlayerID': None, 'Player': 'Ryan Gerard', 'Avg': 1.163, 'Total_SG_T': 4.653, 'Total_SG_T2G': 2.718, 'Total_SG_P': 1.935, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 27, 'Movement': nan, 'PlayerID': None, 'Player': 'Nicolai Højgaard', 'Avg': 1.163, 'Total_SG_T': 4.653, 'Total_SG_T2G': -0.892, 'Total_SG_P': 5.545, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 27, 'Movement': nan, 'PlayerID': None, 'Player': 'Chris Kirk', 'Avg': 1.163, 'Total_SG_T': 4.653, 'Total_SG_T2G': 5.819, 'Total_SG_P': -1.166, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 27, 'Movement': nan, 'PlayerID': None, 'Player': 'Hideki Matsuyama', 'Avg': 1.163, 'Total_SG_T': 4.653, 'Total_SG_T2G': 2.387, 'Total_SG_P': 2.266, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 27, 'Movement': nan, 'PlayerID': None, 'Player': 'Chad Ramey', 'Avg': 1.163, 'Total_SG_T': 4.653, 'Total_SG_T2G': 2.247, 'Total_SG_P': 2.406, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Patrick Cantlay', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 3.213, 'Total_SG_P': 0.44, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Bud Cauley', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 5.536, 'Total_SG_P': -1.883, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Eric Cole', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': -1.234, 'Total_SG_P': 4.887, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Max Homa', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 1.256, 'Total_SG_P': 2.397, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Min Woo Lee', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 2.201, 'Total_SG_P': 1.452, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Maverick McNealy', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 0.782, 'Total_SG_P': 2.871, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Alex Noren', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 0.782, 'Total_SG_P': 2.871, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Andrew Putnam', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 4.903, 'Total_SG_P': -1.25, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Jordan Spieth', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 5.989, 'Total_SG_P': -2.336, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Sahith Theegala', 'Avg': 0.913, 'Total_SG_T': 3.653, 'Total_SG_T2G': 2.224, 'Total_SG_P': 1.429, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 42, 'Movement': nan, 'PlayerID': None, 'Player': 'Wyndham Clark', 'Avg': 0.663, 'Total_SG_T': 2.653, 'Total_SG_T2G': 4.578, 'Total_SG_P': -1.925, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 42, 'Movement': nan, 'PlayerID': None, 'Player': 'Rickie Fowler', 'Avg': 0.663, 'Total_SG_T': 2.653, 'Total_SG_T2G': 0.457, 'Total_SG_P': 2.196, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 42, 'Movement': nan, 'PlayerID': None, 'Player': 'Joe Highsmith', 'Avg': 0.663, 'Total_SG_T': 2.653, 'Total_SG_T2G': 1.277, 'Total_SG_P': 1.376, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 42, 'Movement': nan, 'PlayerID': None, 'Player': 'Nick Taylor', 'Avg': 0.663, 'Total_SG_T': 2.653, 'Total_SG_T2G': 6.511, 'Total_SG_P': -3.858, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 46, 'Movement': nan, 'PlayerID': None, 'Player': 'Rory McIlroy', 'Avg': 0.413, 'Total_SG_T': 1.653, 'Total_SG_T2G': 7.023, 'Total_SG_P': -5.37, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 46, 'Movement': nan, 'PlayerID': None, 'Player': 'Keith Mitchell', 'Avg': 0.413, 'Total_SG_T': 1.653, 'Total_SG_T2G': 2.001, 'Total_SG_P': -0.348, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 46, 'Movement': nan, 'PlayerID': None, 'Player': 'Taylor Pendrith', 'Avg': 0.413, 'Total_SG_T': 1.653, 'Total_SG_T2G': 5.996, 'Total_SG_P': -4.343, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data
Row data: {'Rank': 46, 'Movement': nan, 'PlayerID': None, 'Player': 'Matti Schmid', 'Avg': 0.413, 'Total_SG_T': 1.653, 'Total_SG_T2G': -1.14, 'Total_SG_P': 2.793, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'THE PLAYERS Championship', 'Week_Of_Season': 11, 'Course': 'TPC Sawgrass', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 72}
Inserted data from ['THE PLAYERS Championship'] into sg_data