This is the version without player ID and movement

if you run into an issue with the vir env try this: 

brandon@Mac ~ % cd /Users/brandon/Desktop/Golf_Data/
brandon@Mac Golf_Data % ls -al

In [16]:
import os
import pandas as pd
import re
import numpy as np
pd.set_option('display.max_rows', None)


''' To upload SG files do the following: 
1. go to pga.com site and go to stats site, then to the SG:Total 
2. Save the file as SG_[tourneyID]_[year].csv 
3. Save the file to the /Users/brandon/Desktop/Golf_Data/upload_staging/data_for_upload/ folder 

Other info: 
4. the process should create a merged file (this can be deleted at some point) in the folder 

'''

# Base folder path
# base_path = "/Users/brandon/Desktop/Golf_Data/upload_staging/sg_upload"
base_path = r"C:\Users\brand\OneDrive\Documents\pga_stats\upload_staging\sg_upload"


# File to join
#join_file = "/Users/brandon/Desktop/Golf_Data/PGA_CourseInfo_for_Upload.csv"
join_file = r"C:\Users\brand\OneDrive\Documents\pga_stats\PGA_CourseInfo_for_Upload.csv"

# Load the file to join
main_df = pd.read_csv(join_file)
main_df = main_df[['TourneyID', 'Tournament', 'Week_Of_Season', 'Course', 'Signature_Event', 'Major_Event', 'par']]

# --- Parse ID and Year from filename ---
def parse_id_and_year(filename):
    match = re.match(r'.*_(\d+)_(\d{4})\.csv', filename)
    if match:
        return match.group(1), match.group(2)
    return None, None


# --- Identify Leader Files ---
leader_files = [
    f for f in os.listdir(base_path)
    if f.startswith('sg') and f.endswith('.csv')
]

In [17]:
# --- Process Each Leader File ---
for leader_file in leader_files:
    tourney_id, year = parse_id_and_year(leader_file)
    if not tourney_id:
        continue

    print(f"Processing SG file: {leader_file} (TourneyID={tourney_id}, year={year})")

    # Load leader file
    leader_path = os.path.join(base_path, leader_file)
    leader_df = pd.read_csv(leader_path)
    leader_df['TourneyID'] = int(tourney_id)
    leader_df['year'] = year

    # Join metadata (left join on tourneyID)
    enriched_df = leader_df.merge(main_df, on='TourneyID', how='left')

    # Remove blank rows
    enriched_df.dropna(how='all', inplace=True)

    # Trim spaces from column names in join file
    enriched_df.columns = enriched_df.columns.str.strip()

    # Trim spaces from string values in join file
    enriched_df = enriched_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)



    # Save output

Processing SG file: sg_6_2026.csv (TourneyID=6, year=2026)

In [18]:
tourney_file_name = enriched_df['Tournament'].unique().tolist()
print(tourney_file_name)

['Cognizant Classic in The Palm Beaches']

In [19]:
# Need to re-do postgres creds 
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import execute_values

# Load environment variables from .env file
load_dotenv()

# Database configuration from environment variables
db_config = {
    'host': os.getenv('DB_HOST'),
    'database': os.getenv('DB_NAME'),
    'user': os.getenv('DB_USER'),
    'password': os.getenv('DB_PASSWORD'),
    'port': os.getenv('DB_PORT', '5432')
}
schema = os.getenv('DB_SCHEMA')

# Test the connection
try:
    conn = psycopg2.connect(**db_config)
    conn.close()
    print("✅ Database connection successful!")
    print(f"   Connected to: {db_config['database']} on {db_config['host']}")
except Exception as e:
    print(f"❌ Connection failed: {e}")

✅ Database connection successful!
   Connected to: brdb on localhost

In [20]:
# 
# use this to insert a group of csv files into a table 
'''
import psycopg2
import pandas as pd
import os


conn = psycopg2.connect(
    dbname='brdb',
    user='brandon',
    password='',
    host='localhost',
    port='5432'
)

cur = conn.cursor()
'''
# Folder where your CSV files are stored
# csv_folder = '/Users/brandon/Desktop/Golf_Data/test/the_players_championshipSG_combined_Data.csv'

"\nimport psycopg2\nimport pandas as pd\nimport os\n\n\nconn = psycopg2.connect(\n    dbname='brdb',\n    user='brandon',\n    password='',\n    host='localhost',\n    port='5432'\n)\n\ncur = conn.cursor()\n"

In [21]:
# Target table name
table_name = 'sg_data'

In [22]:
#adding 2 null cols for Movement and PlayerID 
enriched_df['MOVEMENT'] = np.nan
#enriched_df['PLAYER_ID'] = np.nan
enriched_df['PLAYER_ID'] = None
#enriched_df['PLAYER_ID'] = pd.to_numeric(enriched_df['PLAYER_ID'], errors='coerce').astype('Int64')
#enriched_df = enriched_df.where(pd.notna(enriched_df), None)


#enriched_df['MOVEMENT'] = pd.Series([np.nan] * len(enriched_df), dtype='Int64')  # note the capital 'I'
#enriched_df['PLAYER_ID'] = pd.Series([np.nan] * len(enriched_df), dtype='Int64')  # note the capital 'I'


# reorder cols 
enriched_df = enriched_df[['Rank', 'MOVEMENT', 'PLAYER_ID', 'Player','Avg', 'Total SG:T', 'Total SG:T2G'
                           , 'Total SG:P', 'Measured Rounds','TourneyID','year','Tournament'
                           , 'Week_Of_Season' , 'Course','Signature_Event','Major_Event','par']]

In [23]:
enriched_df

,Rank,MOVEMENT,PLAYER_ID,Player,Avg,Total SG:T,Total SG:T2G,Total SG:P,Measured Rounds,TourneyID,year,Tournament,Week_Of_Season,Course,Signature_Event,Major_Event,par
0,1,NaN,None,Nico Echavarria,3.508,14.033,9.761,4.273,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
1,2,NaN,None,Shane Lowry,3.008,12.033,6.969,5.065,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
2,2,NaN,None,Taylor Moore,3.008,12.033,7.744,4.290,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
3,2,NaN,None,Austin Smotherman,3.008,12.033,9.474,2.560,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
4,5,NaN,None,Ricky Castillo,2.508,10.033,8.080,1.954,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
5,6,NaN,None,Nicolai Højgaard,2.008,8.033,7.002,1.032,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
6,6,NaN,None,Keith Mitchell,2.008,8.033,6.036,1.998,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
7,6,NaN,None,William Mouw,2.008,8.033,3.907,4.127,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
8,9,NaN,None,Joel Dahmen,1.758,7.033,7.656,-0.622,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
9,9,NaN,None,Rasmus Højgaard,1.758,7.033,4.124,2.910,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
10,9,NaN,None,Brooks Koepka,1.758,7.033,4.298,2.736,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
11,9,NaN,None,Matti Schmid,1.758,7.033,5.350,1.684,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
12,13,NaN,None,A.J. Ewart,1.508,6.033,0.934,5.100,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
13,13,NaN,None,Max Homa,1.508,6.033,4.427,1.607,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
14,13,NaN,None,Patton Kizzire,1.508,6.033,5.539,0.495,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
15,13,NaN,None,Pontus Nyholm,1.508,6.033,1.869,4.165,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
16,17,NaN,None,Zecheng Dou,1.258,5.033,6.294,-1.260,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
17,17,NaN,None,Takumi Kanaya,1.258,5.033,1.630,3.404,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
18,17,NaN,None,Matthieu Pavon,1.258,5.033,-2.829,7.863,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
19,17,NaN,None,Chad Ramey,1.258,5.033,3.142,1.892,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
20,17,NaN,None,Kristoffer Reitan,1.258,5.033,2.385,2.649,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
21,17,NaN,None,Sudarshan Yellamaraju,1.258,5.033,3.529,1.505,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
22,23,NaN,None,Zach Bauchou,1.008,4.033,3.999,0.035,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
23,23,NaN,None,Adrien Dumont de Chassart,1.008,4.033,4.096,-0.062,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
24,23,NaN,None,Ryan Gerard,1.008,4.033,5.057,-1.023,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
25,23,NaN,None,Beau Hossler,1.008,4.033,1.480,2.554,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
26,23,NaN,None,Mark Hubbard,1.008,4.033,-0.674,4.708,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
27,23,NaN,None,Mackenzie Hughes,1.008,4.033,0.086,3.948,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
28,23,NaN,None,Aaron Rai,1.008,4.033,5.586,-1.552,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
29,23,NaN,None,Kevin Roy,1.008,4.033,2.188,1.846,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
30,23,NaN,None,Jordan Smith,1.008,4.033,3.319,0.715,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
31,32,NaN,None,Daniel Berger,0.758,3.033,3.755,-0.721,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
32,32,NaN,None,David Ford,0.758,3.033,3.747,-0.713,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
33,32,NaN,None,Haotong Li,0.758,3.033,0.896,2.138,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
34,32,NaN,None,Jimmy Stanger,0.758,3.033,0.468,2.566,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
35,32,NaN,None,Kevin Streelman,0.758,3.033,1.075,1.959,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
36,37,NaN,None,Christiaan Bezuidenhout,0.508,2.033,2.302,-0.268,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
37,37,NaN,None,Eric Cole,0.508,2.033,-1.465,3.499,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
38,37,NaN,None,Steven Fisk,0.508,2.033,3.662,-1.628,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
39,40,NaN,None,Dan Brown,0.258,1.033,5.983,-4.949,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
40,40,NaN,None,Austin Eckroat,0.258,1.033,2.889,-1.855,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
41,40,NaN,None,Patrick Fishburn,0.258,1.033,-3.536,4.570,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
42,40,NaN,None,Garrick Higgo,0.258,1.033,4.381,-3.347,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
43,40,NaN,None,Lee Hodges,0.258,1.033,3.212,-2.178,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
44,40,NaN,None,Hank Lebioda,0.258,1.033,-0.690,1.724,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
45,40,NaN,None,Max McGreevy,0.258,1.033,5.622,-4.588,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
46,40,NaN,None,Rasmus Neergaard-Petersen,0.258,1.033,1.459,-0.425,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
47,40,NaN,None,Thorbjørn Olesen,0.258,1.033,1.285,-0.251,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
48,40,NaN,None,Ben Silverman,0.258,1.033,2.880,-1.846,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
49,40,NaN,None,Danny Walker,0.258,1.033,0.730,0.304,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
50,40,NaN,None,Matt Wallace,0.258,1.033,0.250,0.784,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
51,52,NaN,None,Michael Brennan,0.008,0.033,4.505,-4.471,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
52,52,NaN,None,Seamus Power,0.008,0.033,-3.169,3.203,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
53,52,NaN,None,Alex Smalley,0.008,0.033,5.516,-5.482,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
54,52,NaN,None,Carson Young,0.008,0.033,-1.220,1.254,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
55,56,NaN,None,Emiliano Grillo,-0.242,-0.967,4.517,-5.483,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
56,56,NaN,None,Chan Kim,-0.242,-0.967,-0.871,-0.095,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
57,56,NaN,None,Adrien Saddier,-0.242,-0.967,-1.896,0.930,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
58,59,NaN,None,Tom Kim,-0.492,-1.967,-2.763,0.797,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
59,60,NaN,None,Adam Schenk,-0.742,-2.967,-2.606,-0.360,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
60,60,NaN,None,Davis Thompson,-0.742,-2.967,-0.620,-2.346,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
61,62,NaN,None,Billy Horschel,-0.992,-3.967,-5.028,1.062,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
62,63,NaN,None,John Parry,-1.242,-4.967,2.538,-7.504,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
63,63,NaN,None,Chandler Phillips,-1.242,-4.967,-3.723,-1.243,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
64,63,NaN,None,Jackson Suber,-1.242,-4.967,-5.024,0.058,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
65,66,NaN,None,Dylan Wu,-1.742,-6.967,-3.691,-3.275,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
66,67,NaN,None,Joe Highsmith,-2.242,-8.967,-6.368,-2.598,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0

In [24]:
df = enriched_df.rename(columns={'Rank': 'Rank', 'MOVEMENT': 'Movement', 
                            'PLAYER_ID': 'PlayerID', 'Player': 'Player', 'Total SG:T': 'Total_SG_T'
                            , 'Total SG:T2G': 'Total_SG_T2G', 'Total SG:P':'Total_SG_P'
                            , 'Measured Rounds':'Measured_Rounds' })

df = df.dropna(subset=df.columns[:7], how='all')

columns_to_clean = ['par', 'Week_Of_Season', 'year','Rank','Measured_Rounds'] # removing Player_ID since its null/blank



#print(df.head())

In [25]:
df

,Rank,Movement,PlayerID,Player,Avg,Total_SG_T,Total_SG_T2G,Total_SG_P,Measured_Rounds,TourneyID,year,Tournament,Week_Of_Season,Course,Signature_Event,Major_Event,par
0,1,NaN,None,Nico Echavarria,3.508,14.033,9.761,4.273,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
1,2,NaN,None,Shane Lowry,3.008,12.033,6.969,5.065,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
2,2,NaN,None,Taylor Moore,3.008,12.033,7.744,4.290,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
3,2,NaN,None,Austin Smotherman,3.008,12.033,9.474,2.560,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
4,5,NaN,None,Ricky Castillo,2.508,10.033,8.080,1.954,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
5,6,NaN,None,Nicolai Højgaard,2.008,8.033,7.002,1.032,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
6,6,NaN,None,Keith Mitchell,2.008,8.033,6.036,1.998,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
7,6,NaN,None,William Mouw,2.008,8.033,3.907,4.127,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
8,9,NaN,None,Joel Dahmen,1.758,7.033,7.656,-0.622,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
9,9,NaN,None,Rasmus Højgaard,1.758,7.033,4.124,2.910,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
10,9,NaN,None,Brooks Koepka,1.758,7.033,4.298,2.736,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
11,9,NaN,None,Matti Schmid,1.758,7.033,5.350,1.684,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
12,13,NaN,None,A.J. Ewart,1.508,6.033,0.934,5.100,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
13,13,NaN,None,Max Homa,1.508,6.033,4.427,1.607,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
14,13,NaN,None,Patton Kizzire,1.508,6.033,5.539,0.495,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
15,13,NaN,None,Pontus Nyholm,1.508,6.033,1.869,4.165,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
16,17,NaN,None,Zecheng Dou,1.258,5.033,6.294,-1.260,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
17,17,NaN,None,Takumi Kanaya,1.258,5.033,1.630,3.404,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
18,17,NaN,None,Matthieu Pavon,1.258,5.033,-2.829,7.863,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
19,17,NaN,None,Chad Ramey,1.258,5.033,3.142,1.892,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
20,17,NaN,None,Kristoffer Reitan,1.258,5.033,2.385,2.649,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
21,17,NaN,None,Sudarshan Yellamaraju,1.258,5.033,3.529,1.505,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
22,23,NaN,None,Zach Bauchou,1.008,4.033,3.999,0.035,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
23,23,NaN,None,Adrien Dumont de Chassart,1.008,4.033,4.096,-0.062,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
24,23,NaN,None,Ryan Gerard,1.008,4.033,5.057,-1.023,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
25,23,NaN,None,Beau Hossler,1.008,4.033,1.480,2.554,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
26,23,NaN,None,Mark Hubbard,1.008,4.033,-0.674,4.708,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
27,23,NaN,None,Mackenzie Hughes,1.008,4.033,0.086,3.948,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
28,23,NaN,None,Aaron Rai,1.008,4.033,5.586,-1.552,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
29,23,NaN,None,Kevin Roy,1.008,4.033,2.188,1.846,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
30,23,NaN,None,Jordan Smith,1.008,4.033,3.319,0.715,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
31,32,NaN,None,Daniel Berger,0.758,3.033,3.755,-0.721,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
32,32,NaN,None,David Ford,0.758,3.033,3.747,-0.713,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
33,32,NaN,None,Haotong Li,0.758,3.033,0.896,2.138,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
34,32,NaN,None,Jimmy Stanger,0.758,3.033,0.468,2.566,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
35,32,NaN,None,Kevin Streelman,0.758,3.033,1.075,1.959,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
36,37,NaN,None,Christiaan Bezuidenhout,0.508,2.033,2.302,-0.268,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
37,37,NaN,None,Eric Cole,0.508,2.033,-1.465,3.499,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
38,37,NaN,None,Steven Fisk,0.508,2.033,3.662,-1.628,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
39,40,NaN,None,Dan Brown,0.258,1.033,5.983,-4.949,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
40,40,NaN,None,Austin Eckroat,0.258,1.033,2.889,-1.855,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
41,40,NaN,None,Patrick Fishburn,0.258,1.033,-3.536,4.570,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
42,40,NaN,None,Garrick Higgo,0.258,1.033,4.381,-3.347,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
43,40,NaN,None,Lee Hodges,0.258,1.033,3.212,-2.178,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
44,40,NaN,None,Hank Lebioda,0.258,1.033,-0.690,1.724,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
45,40,NaN,None,Max McGreevy,0.258,1.033,5.622,-4.588,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
46,40,NaN,None,Rasmus Neergaard-Petersen,0.258,1.033,1.459,-0.425,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
47,40,NaN,None,Thorbjørn Olesen,0.258,1.033,1.285,-0.251,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
48,40,NaN,None,Ben Silverman,0.258,1.033,2.880,-1.846,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
49,40,NaN,None,Danny Walker,0.258,1.033,0.730,0.304,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
50,40,NaN,None,Matt Wallace,0.258,1.033,0.250,0.784,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
51,52,NaN,None,Michael Brennan,0.008,0.033,4.505,-4.471,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
52,52,NaN,None,Seamus Power,0.008,0.033,-3.169,3.203,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
53,52,NaN,None,Alex Smalley,0.008,0.033,5.516,-5.482,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
54,52,NaN,None,Carson Young,0.008,0.033,-1.220,1.254,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
55,56,NaN,None,Emiliano Grillo,-0.242,-0.967,4.517,-5.483,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
56,56,NaN,None,Chan Kim,-0.242,-0.967,-0.871,-0.095,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
57,56,NaN,None,Adrien Saddier,-0.242,-0.967,-1.896,0.930,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
58,59,NaN,None,Tom Kim,-0.492,-1.967,-2.763,0.797,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
59,60,NaN,None,Adam Schenk,-0.742,-2.967,-2.606,-0.360,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
60,60,NaN,None,Davis Thompson,-0.742,-2.967,-0.620,-2.346,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
61,62,NaN,None,Billy Horschel,-0.992,-3.967,-5.028,1.062,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
62,63,NaN,None,John Parry,-1.242,-4.967,2.538,-7.504,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
63,63,NaN,None,Chandler Phillips,-1.242,-4.967,-3.723,-1.243,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
64,63,NaN,None,Jackson Suber,-1.242,-4.967,-5.024,0.058,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
65,66,NaN,None,Dylan Wu,-1.742,-6.967,-3.691,-3.275,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0
66,67,NaN,None,Joe Highsmith,-2.242,-8.967,-6.368,-2.598,4,6,2026,Cognizant Classic in The Palm Beaches,9.0,PGA National Resort,N,N,71.0

In [26]:
df.drop(columns=['TourneyID'], inplace=True)

In [27]:
for col in columns_to_clean:
    df[col] = df[col].apply(lambda x: None if pd.isna(x) else int(x))

In [28]:
#df = df.dropna(subset=['pos'])
#df = df.dropna(how='all')

In [29]:
df

,Rank,Movement,PlayerID,Player,Avg,Total_SG_T,Total_SG_T2G,Total_SG_P,Measured_Rounds,year,Tournament,Week_Of_Season,Course,Signature_Event,Major_Event,par
0,1,NaN,None,Nico Echavarria,3.508,14.033,9.761,4.273,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
1,2,NaN,None,Shane Lowry,3.008,12.033,6.969,5.065,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
2,2,NaN,None,Taylor Moore,3.008,12.033,7.744,4.290,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
3,2,NaN,None,Austin Smotherman,3.008,12.033,9.474,2.560,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
4,5,NaN,None,Ricky Castillo,2.508,10.033,8.080,1.954,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
5,6,NaN,None,Nicolai Højgaard,2.008,8.033,7.002,1.032,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
6,6,NaN,None,Keith Mitchell,2.008,8.033,6.036,1.998,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
7,6,NaN,None,William Mouw,2.008,8.033,3.907,4.127,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
8,9,NaN,None,Joel Dahmen,1.758,7.033,7.656,-0.622,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
9,9,NaN,None,Rasmus Højgaard,1.758,7.033,4.124,2.910,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
10,9,NaN,None,Brooks Koepka,1.758,7.033,4.298,2.736,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
11,9,NaN,None,Matti Schmid,1.758,7.033,5.350,1.684,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
12,13,NaN,None,A.J. Ewart,1.508,6.033,0.934,5.100,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
13,13,NaN,None,Max Homa,1.508,6.033,4.427,1.607,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
14,13,NaN,None,Patton Kizzire,1.508,6.033,5.539,0.495,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
15,13,NaN,None,Pontus Nyholm,1.508,6.033,1.869,4.165,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
16,17,NaN,None,Zecheng Dou,1.258,5.033,6.294,-1.260,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
17,17,NaN,None,Takumi Kanaya,1.258,5.033,1.630,3.404,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
18,17,NaN,None,Matthieu Pavon,1.258,5.033,-2.829,7.863,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
19,17,NaN,None,Chad Ramey,1.258,5.033,3.142,1.892,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
20,17,NaN,None,Kristoffer Reitan,1.258,5.033,2.385,2.649,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
21,17,NaN,None,Sudarshan Yellamaraju,1.258,5.033,3.529,1.505,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
22,23,NaN,None,Zach Bauchou,1.008,4.033,3.999,0.035,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
23,23,NaN,None,Adrien Dumont de Chassart,1.008,4.033,4.096,-0.062,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
24,23,NaN,None,Ryan Gerard,1.008,4.033,5.057,-1.023,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
25,23,NaN,None,Beau Hossler,1.008,4.033,1.480,2.554,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
26,23,NaN,None,Mark Hubbard,1.008,4.033,-0.674,4.708,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
27,23,NaN,None,Mackenzie Hughes,1.008,4.033,0.086,3.948,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
28,23,NaN,None,Aaron Rai,1.008,4.033,5.586,-1.552,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
29,23,NaN,None,Kevin Roy,1.008,4.033,2.188,1.846,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
30,23,NaN,None,Jordan Smith,1.008,4.033,3.319,0.715,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
31,32,NaN,None,Daniel Berger,0.758,3.033,3.755,-0.721,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
32,32,NaN,None,David Ford,0.758,3.033,3.747,-0.713,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
33,32,NaN,None,Haotong Li,0.758,3.033,0.896,2.138,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
34,32,NaN,None,Jimmy Stanger,0.758,3.033,0.468,2.566,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
35,32,NaN,None,Kevin Streelman,0.758,3.033,1.075,1.959,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
36,37,NaN,None,Christiaan Bezuidenhout,0.508,2.033,2.302,-0.268,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
37,37,NaN,None,Eric Cole,0.508,2.033,-1.465,3.499,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
38,37,NaN,None,Steven Fisk,0.508,2.033,3.662,-1.628,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
39,40,NaN,None,Dan Brown,0.258,1.033,5.983,-4.949,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
40,40,NaN,None,Austin Eckroat,0.258,1.033,2.889,-1.855,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
41,40,NaN,None,Patrick Fishburn,0.258,1.033,-3.536,4.570,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
42,40,NaN,None,Garrick Higgo,0.258,1.033,4.381,-3.347,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
43,40,NaN,None,Lee Hodges,0.258,1.033,3.212,-2.178,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
44,40,NaN,None,Hank Lebioda,0.258,1.033,-0.690,1.724,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
45,40,NaN,None,Max McGreevy,0.258,1.033,5.622,-4.588,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
46,40,NaN,None,Rasmus Neergaard-Petersen,0.258,1.033,1.459,-0.425,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
47,40,NaN,None,Thorbjørn Olesen,0.258,1.033,1.285,-0.251,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
48,40,NaN,None,Ben Silverman,0.258,1.033,2.880,-1.846,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
49,40,NaN,None,Danny Walker,0.258,1.033,0.730,0.304,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
50,40,NaN,None,Matt Wallace,0.258,1.033,0.250,0.784,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
51,52,NaN,None,Michael Brennan,0.008,0.033,4.505,-4.471,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
52,52,NaN,None,Seamus Power,0.008,0.033,-3.169,3.203,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
53,52,NaN,None,Alex Smalley,0.008,0.033,5.516,-5.482,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
54,52,NaN,None,Carson Young,0.008,0.033,-1.220,1.254,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
55,56,NaN,None,Emiliano Grillo,-0.242,-0.967,4.517,-5.483,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
56,56,NaN,None,Chan Kim,-0.242,-0.967,-0.871,-0.095,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
57,56,NaN,None,Adrien Saddier,-0.242,-0.967,-1.896,0.930,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
58,59,NaN,None,Tom Kim,-0.492,-1.967,-2.763,0.797,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
59,60,NaN,None,Adam Schenk,-0.742,-2.967,-2.606,-0.360,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
60,60,NaN,None,Davis Thompson,-0.742,-2.967,-0.620,-2.346,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
61,62,NaN,None,Billy Horschel,-0.992,-3.967,-5.028,1.062,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
62,63,NaN,None,John Parry,-1.242,-4.967,2.538,-7.504,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
63,63,NaN,None,Chandler Phillips,-1.242,-4.967,-3.723,-1.243,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
64,63,NaN,None,Jackson Suber,-1.242,-4.967,-5.024,0.058,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
65,66,NaN,None,Dylan Wu,-1.742,-6.967,-3.691,-3.275,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71
66,67,NaN,None,Joe Highsmith,-2.242,-8.967,-6.368,-2.598,4,2026,Cognizant Classic in The Palm Beaches,9,PGA National Resort,N,N,71

In [30]:
conn = psycopg2.connect(**db_config)
cur = conn.cursor()
for _, row in df.iterrows():
    columns = ', '.join(df.columns)
    placeholders = ', '.join(['%s'] * len(row))
    insert_sql = f"INSERT INTO {schema}.{table_name} ({columns}) VALUES ({placeholders})"
    
    # DEBUG: print the row and data types
    print("Row data:", row.to_dict())

    try:
        cur.execute(insert_sql, tuple(row))
    except Exception as e:
        print("Error on row:", row.to_dict())
        print("Data types:", [type(x) for x in row])
        raise e  # re-raise to stop execution

    #cur.execute(insert_sql, tuple(row))
        
    conn.commit()
    print(f"Inserted data from {tourney_file_name} into {table_name}")

Row data: {'Rank': 1, 'Movement': nan, 'PlayerID': None, 'Player': 'Nico Echavarria', 'Avg': 3.508, 'Total_SG_T': 14.033, 'Total_SG_T2G': 9.761, 'Total_SG_P': 4.273, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 2, 'Movement': nan, 'PlayerID': None, 'Player': 'Shane Lowry', 'Avg': 3.008, 'Total_SG_T': 12.033, 'Total_SG_T2G': 6.969, 'Total_SG_P': 5.065, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 2, 'Movement': nan, 'PlayerID': None, 'Player': 'Taylor Moore', 'Avg': 3.008, 'Total_SG_T': 12.033, 'Total_SG_T2G': 7.744, 'Total_SG_P': 4.29, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 2, 'Movement': nan, 'PlayerID': None, 'Player': 'Austin Smotherman', 'Avg': 3.008, 'Total_SG_T': 12.033, 'Total_SG_T2G': 9.474, 'Total_SG_P': 2.56, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 5, 'Movement': nan, 'PlayerID': None, 'Player': 'Ricky Castillo', 'Avg': 2.508, 'Total_SG_T': 10.033, 'Total_SG_T2G': 8.08, 'Total_SG_P': 1.954, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 6, 'Movement': nan, 'PlayerID': None, 'Player': 'Nicolai Højgaard', 'Avg': 2.008, 'Total_SG_T': 8.033, 'Total_SG_T2G': 7.002, 'Total_SG_P': 1.032, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 6, 'Movement': nan, 'PlayerID': None, 'Player': 'Keith Mitchell', 'Avg': 2.008, 'Total_SG_T': 8.033, 'Total_SG_T2G': 6.036, 'Total_SG_P': 1.998, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 6, 'Movement': nan, 'PlayerID': None, 'Player': 'William Mouw', 'Avg': 2.008, 'Total_SG_T': 8.033, 'Total_SG_T2G': 3.907, 'Total_SG_P': 4.127, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 9, 'Movement': nan, 'PlayerID': None, 'Player': 'Joel Dahmen', 'Avg': 1.758, 'Total_SG_T': 7.033, 'Total_SG_T2G': 7.656, 'Total_SG_P': -0.622, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 9, 'Movement': nan, 'PlayerID': None, 'Player': 'Rasmus Højgaard', 'Avg': 1.758, 'Total_SG_T': 7.033, 'Total_SG_T2G': 4.124, 'Total_SG_P': 2.91, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 9, 'Movement': nan, 'PlayerID': None, 'Player': 'Brooks Koepka', 'Avg': 1.758, 'Total_SG_T': 7.033, 'Total_SG_T2G': 4.298, 'Total_SG_P': 2.736, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 9, 'Movement': nan, 'PlayerID': None, 'Player': 'Matti Schmid', 'Avg': 1.758, 'Total_SG_T': 7.033, 'Total_SG_T2G': 5.35, 'Total_SG_P': 1.684, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'A.J. Ewart', 'Avg': 1.508, 'Total_SG_T': 6.033, 'Total_SG_T2G': 0.934, 'Total_SG_P': 5.1, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Max Homa', 'Avg': 1.508, 'Total_SG_T': 6.033, 'Total_SG_T2G': 4.427, 'Total_SG_P': 1.607, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Patton Kizzire', 'Avg': 1.508, 'Total_SG_T': 6.033, 'Total_SG_T2G': 5.539, 'Total_SG_P': 0.495, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 13, 'Movement': nan, 'PlayerID': None, 'Player': 'Pontus Nyholm', 'Avg': 1.508, 'Total_SG_T': 6.033, 'Total_SG_T2G': 1.869, 'Total_SG_P': 4.165, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 17, 'Movement': nan, 'PlayerID': None, 'Player': 'Zecheng Dou', 'Avg': 1.258, 'Total_SG_T': 5.033, 'Total_SG_T2G': 6.294, 'Total_SG_P': -1.26, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 17, 'Movement': nan, 'PlayerID': None, 'Player': 'Takumi Kanaya', 'Avg': 1.258, 'Total_SG_T': 5.033, 'Total_SG_T2G': 1.63, 'Total_SG_P': 3.404, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 17, 'Movement': nan, 'PlayerID': None, 'Player': 'Matthieu Pavon', 'Avg': 1.258, 'Total_SG_T': 5.033, 'Total_SG_T2G': -2.829, 'Total_SG_P': 7.863, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 17, 'Movement': nan, 'PlayerID': None, 'Player': 'Chad Ramey', 'Avg': 1.258, 'Total_SG_T': 5.033, 'Total_SG_T2G': 3.142, 'Total_SG_P': 1.892, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 17, 'Movement': nan, 'PlayerID': None, 'Player': 'Kristoffer Reitan', 'Avg': 1.258, 'Total_SG_T': 5.033, 'Total_SG_T2G': 2.385, 'Total_SG_P': 2.649, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 17, 'Movement': nan, 'PlayerID': None, 'Player': 'Sudarshan Yellamaraju', 'Avg': 1.258, 'Total_SG_T': 5.033, 'Total_SG_T2G': 3.529, 'Total_SG_P': 1.505, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Zach Bauchou', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 3.999, 'Total_SG_P': 0.035, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Adrien Dumont de Chassart', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 4.096, 'Total_SG_P': -0.062, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Ryan Gerard', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 5.057, 'Total_SG_P': -1.023, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Beau Hossler', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 1.48, 'Total_SG_P': 2.554, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Mark Hubbard', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': -0.674, 'Total_SG_P': 4.708, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Mackenzie Hughes', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 0.086, 'Total_SG_P': 3.948, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Aaron Rai', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 5.586, 'Total_SG_P': -1.552, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Kevin Roy', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 2.188, 'Total_SG_P': 1.846, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 23, 'Movement': nan, 'PlayerID': None, 'Player': 'Jordan Smith', 'Avg': 1.008, 'Total_SG_T': 4.033, 'Total_SG_T2G': 3.319, 'Total_SG_P': 0.715, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Daniel Berger', 'Avg': 0.758, 'Total_SG_T': 3.033, 'Total_SG_T2G': 3.755, 'Total_SG_P': -0.721, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'David Ford', 'Avg': 0.758, 'Total_SG_T': 3.033, 'Total_SG_T2G': 3.747, 'Total_SG_P': -0.713, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Haotong Li', 'Avg': 0.758, 'Total_SG_T': 3.033, 'Total_SG_T2G': 0.896, 'Total_SG_P': 2.138, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Jimmy Stanger', 'Avg': 0.758, 'Total_SG_T': 3.033, 'Total_SG_T2G': 0.468, 'Total_SG_P': 2.566, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 32, 'Movement': nan, 'PlayerID': None, 'Player': 'Kevin Streelman', 'Avg': 0.758, 'Total_SG_T': 3.033, 'Total_SG_T2G': 1.075, 'Total_SG_P': 1.959, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 37, 'Movement': nan, 'PlayerID': None, 'Player': 'Christiaan Bezuidenhout', 'Avg': 0.508, 'Total_SG_T': 2.033, 'Total_SG_T2G': 2.302, 'Total_SG_P': -0.268, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 37, 'Movement': nan, 'PlayerID': None, 'Player': 'Eric Cole', 'Avg': 0.508, 'Total_SG_T': 2.033, 'Total_SG_T2G': -1.465, 'Total_SG_P': 3.499, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 37, 'Movement': nan, 'PlayerID': None, 'Player': 'Steven Fisk', 'Avg': 0.508, 'Total_SG_T': 2.033, 'Total_SG_T2G': 3.662, 'Total_SG_P': -1.628, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 40, 'Movement': nan, 'PlayerID': None, 'Player': 'Dan Brown', 'Avg': 0.258, 'Total_SG_T': 1.033, 'Total_SG_T2G': 5.983, 'Total_SG_P': -4.949, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 40, 'Movement': nan, 'PlayerID': None, 'Player': 'Austin Eckroat', 'Avg': 0.258, 'Total_SG_T': 1.033, 'Total_SG_T2G': 2.889, 'Total_SG_P': -1.855, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 40, 'Movement': nan, 'PlayerID': None, 'Player': 'Patrick Fishburn', 'Avg': 0.258, 'Total_SG_T': 1.033, 'Total_SG_T2G': -3.536, 'Total_SG_P': 4.57, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 40, 'Movement': nan, 'PlayerID': None, 'Player': 'Garrick Higgo', 'Avg': 0.258, 'Total_SG_T': 1.033, 'Total_SG_T2G': 4.381, 'Total_SG_P': -3.347, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 40, 'Movement': nan, 'PlayerID': None, 'Player': 'Lee Hodges', 'Avg': 0.258, 'Total_SG_T': 1.033, 'Total_SG_T2G': 3.212, 'Total_SG_P': -2.178, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data
Row data: {'Rank': 40, 'Movement': nan, 'PlayerID': None, 'Player': 'Hank Lebioda', 'Avg': 0.258, 'Total_SG_T': 1.033, 'Total_SG_T2G': -0.69, 'Total_SG_P': 1.724, 'Measured_Rounds': 4, 'year': 2026, 'Tournament': 'Cognizant Classic in The Palm Beaches', 'Week_Of_Season': 9, 'Course': 'PGA National Resort', 'Signature_Event': 'N', 'Major_Event': 'N', 'par': 71}
Inserted data from ['Cognizant Classic in The Palm Beaches'] into sg_data