In [1]:
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import execute_values
import pandas as pd 
import numpy as np
import os
import re

In [2]:
# Improvements to the script 
# Need a way to investigate top rated golfers - DONE
# want to see a print out of top golfers and their assigned tier - DONE
# might need to put a min threshold on the amount of events, current analysis bias towards less events (done must at least 5) - DONE
# want to have a print out of past standings for an event 
# want to see the x last finishes for a golfer by search - DONE
# eventually need to track results - success of picks 
# need to add how many top 3 , 5 and 10 to part of the stats and less sg 

# New March 2026 
# Add DG ranks to output 
# Want to see a trend/moving average of last X events to show improvment or decline over time 
# Add query to pull past event score 
# Add code to github 
# Remove from jupyter notebook and make it a standalone script 
#

In [3]:
# Load environment variables from .env file
load_dotenv()

# Database configuration from environment variables
db_config = {
    'host': os.getenv('DB_HOST'),
    'database': os.getenv('DB_NAME'),
    'user': os.getenv('DB_USER'),
    'password': os.getenv('DB_PASSWORD'),
    'port': os.getenv('DB_PORT', '5432')
}
schema = os.getenv('DB_SCHEMA')

# Test the connection
try:
    conn = psycopg2.connect(**db_config)
    conn.close()
    print("✅ Database connection successful!")
    print(f"   Connected to: {db_config['database']} on {db_config['host']}")
except Exception as e:
    print(f"❌ Connection failed: {e}")

✅ Database connection successful!
   Connected to: brdb on localhost

In [4]:
# Create a cursor
conn = psycopg2.connect(**db_config)
cur = conn.cursor()

# Example query
query = ''' select a.player , a.pos , a.to_par 
, a.year , a.week_of_season , a.tournament , a.course
, b.avg , case when b.avg is null then -2 else b.avg end Updated_Avg
, b.total_sg_t , b.total_sg_t2g , b.total_sg_p , measured_rounds 
from pga_stats.Leaderboard_data a 
left join pga_stats.sg_data b
on a.player = b.player 
and a.year = b.year 
and a.week_of_season = b.week_of_season
'''

# Execute the query
cur.execute(query)

# Fetch results
rows = cur.fetchall()

colnames = [desc[0] for desc in cur.description]

# Load into DataFrame
df = pd.DataFrame(rows, columns=colnames)

# Close connections
#cur.close()
#conn.close()

In [5]:
# Sort data
df = df.sort_values(by=['player', 'year', 'week_of_season'])

# Group by golfer and compute rolling averages
df['SG_last_1'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(1, min_periods=1).mean())
df['SG_last_2'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(2, min_periods=1).mean())
df['SG_last_3'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(3, min_periods=1).mean())
df['SG_last_5'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(5, min_periods=1).mean())
df['SG_last_8'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(8, min_periods=1).mean())
df['SG_last_13'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(13, min_periods=1).mean())
df['SG_last_21'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(21, min_periods=1).mean())
df['SG_last_34'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(34, min_periods=1).mean())
df['SG_last_55'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(55, min_periods=1).mean())
df['SG_last_89'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(89, min_periods=1).mean())

In [6]:
df = df.round(3)
player_view = df[df['player'].str.lower() == 'ben griffin']
latest = df.groupby('player').tail(1).reset_index(drop=True)

In [7]:
# Query to call updated datagolf ranks 

'''
conn = psycopg2.connect(
    dbname='brdb',
    user='brandon',
    password='',
    host='localhost',
    port='5432'
)
'''

cur = conn.cursor()

# Write your SQL query
query = "SELECT * FROM pga_stats.datagolf_ranks;"

# Load data into a DataFrame
df = pd.read_sql_query(query, conn)

# Close the connection
# conn.close()

# Now df contains your table data
print(df.head())

     id        player_name   primary_tour  dg_rank  owgr_rank  dg_index  \
0  2001  Scottie Scheffler       PGA Tour        1          1     2.860
1  2002           Jon Rahm       LIV Golf        2         36     2.054
2  2003       Rory McIlroy  DP World Tour        3          2     1.984
3  2004     Russell Henley       PGA Tour        4          6     1.697
4  2005    Tommy Fleetwood       PGA Tour        5          3     1.655

                refresh_date
0 2026-03-10 22:33:59.146718
1 2026-03-10 22:33:59.146718
2 2026-03-10 22:33:59.146718
3 2026-03-10 22:33:59.146718
4 2026-03-10 22:33:59.146718

C:\Users\brand\AppData\Local\Temp\ipykernel_10376\508808764.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

In [8]:
joined_df = pd.merge(latest, df, how='left', left_on='player', right_on='player_name')

In [9]:
# Percentile Ranks
sg_cols = [
    'SG_last_1', 'SG_last_2', 'SG_last_3', 'SG_last_5', 'SG_last_8',
    'SG_last_13', 'SG_last_21', 'SG_last_34', 'SG_last_55', 'SG_last_89', 'dg_index'
]

for col in sg_cols:
    joined_df[f'{col}_percentile'] = joined_df[col].rank(pct=True, ascending=True)

In [10]:
# If you want descending order (best performer = 100th percentile)
joined_df['owgr_rank_percentile'] = joined_df['owgr_rank'].rank(pct=True,ascending=False)
joined_df = joined_df.round(4)

In [11]:
# Pull leaderboard data
'''
conn = psycopg2.connect(
    dbname='brdb',
    user='brandon',
    password='',
    host='localhost',
    port='5432'
)
'''
cur = conn.cursor()

# Write your SQL query
query = '''select player , pos , to_par , official_money 
, year , tournament , week_of_season , course 
from pga_stats.leaderboard_data ;'''

# Load data into a DataFrame
df = pd.read_sql_query(query, conn)

# Close the connection
# conn.close()

# Sort data
df = df.sort_values(by=['player', 'year', 'week_of_season'])

C:\Users\brand\AppData\Local\Temp\ipykernel_10376\135137390.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

In [12]:
# CONFIGURATION: Choose how to handle cuts
CUT_HANDLING = "penalty"  # Options: "penalty", "skip", "field_size"
CUT_PENALTY_POSITION = 80  # Position assigned to cuts when using "penalty" method

# Convert position to numeric, handling string positions like "T5", "T10", etc.
def clean_position(pos):
    if pd.isna(pos):
        return np.nan
    
    # Convert to string and handle tied positions
    pos_str = str(pos).upper().strip()
    
    # Handle cuts based on chosen method
    if pos_str == 'CUT' or pos_str == 'MC':  # MC = Missed Cut
        if CUT_HANDLING == "penalty":
            return CUT_PENALTY_POSITION  # Fixed penalty position
        elif CUT_HANDLING == "skip":
            return np.nan  # Skip cuts entirely - don't count in averages

    # Remove 'T' for tied positions and convert to integer
    if pos_str.startswith('T'):
        return int(pos_str[1:])
    else:
        try:
            return int(pos_str)
        except ValueError:
            return np.nan
        
# Apply position cleaning
df['position_numeric'] = df['pos'].apply(clean_position)

# Sort by player and then by week/year to get chronological order
df_sorted = df.sort_values(['player', 'year', 'week_of_season'], ascending=[True, True, True])

In [13]:
# Group by player and calculate rolling averages
results = []

# Get current date info for filtering last year's data
current_year = df['year'].max()  # Use the most recent year in the data
last_year_cutoff = current_year - 1  # Look at roughly last year of data


for player, group in df_sorted.groupby('player'):
    # Get all tournament entries (including cuts) in chronological order
    all_entries = group.dropna(subset=['pos']).copy()
    
    # Filter for last year's data for cut percentage calculation
    # recent_entries = all_entries[all_entries['year'] >= current_year] # this is the old version that was just pulling current year values but was supposed to be prior year
    recent_entries = all_entries[all_entries['year'] == last_year_cutoff]
    # Calculate cut percentage over the last year
    if len(recent_entries) > 0:
        cuts_made = len(recent_entries[~recent_entries['pos'].str.upper().isin(['CUT', 'MC'])])
        total_tournaments = len(recent_entries)
        cut_percentage = (cuts_made / total_tournaments) * 100
    else:
        cut_percentage = np.nan
        total_tournaments = 0
    
    # Get numeric positions for averaging (this excludes NaN values from cuts if using "skip" method)
    positions = group['position_numeric'].dropna().tolist()
    
    if len(positions) == 0:
        continue

    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144
    
    recent_positions = recent_entries[recent_entries['position_numeric'].notna()]['position_numeric'].tolist()


    top_5_count = len([pos for pos in recent_positions if pos <= 5])
    top_10_count = len([pos for pos in recent_positions if pos <= 10]) 
    top_20_count = len([pos for pos in recent_positions if pos <= 20])
    # Calculate average for last 3 games


    # Calculate percentages based on tournaments finished (not including cuts)
    num_recent_positions = len(recent_positions)
    if num_recent_positions > 0:
        top_5_percentage = (top_5_count / num_recent_positions) * 100
        top_10_percentage = (top_10_count / num_recent_positions) * 100
        top_20_percentage = (top_20_count / num_recent_positions) * 100
    else:
        top_5_percentage = 0.0
        top_10_percentage = 0.0
        top_20_percentage = 0.0

    last_1_avg = np.mean(positions[-1:]) if len(positions) >= 1 else np.nan
    last_3_avg = np.mean(positions[-3:]) if len(positions) >= 1 else np.nan
    
    # Calculate average for last 5 games
    last_5_avg = np.mean(positions[-5:]) if len(positions) >= 1 else np.nan
    
    # Calculate average for last 10 games
    last_10_avg = np.mean(positions[-10:]) if len(positions) >= 1 else np.nan

    # Count of games with valid positions (excludes cuts if using "skip" method)
    games_with_positions = len(positions)
    
    # Count of all tournament entries
    total_entries = len(all_entries)
    last_5_pos  = positions[-5:]
    last_10_pos = positions[-10:]

    results.append({
        'player': player,
        'total_tournaments': total_entries,
        'games_with_positions': games_with_positions,
        'tournaments_last_year': total_tournaments, #recent_entries = all_entries[all_entries['year'] == last_year_cutoff]
        'cut_percentage_last_year': round(cut_percentage, 1) if not pd.isna(cut_percentage) else None,
        'last_3_avg_position': round(last_3_avg, 2) if not pd.isna(last_3_avg) else None,
        'last_5_avg_position': round(last_5_avg, 2) if not pd.isna(last_5_avg) else None,
        'last_10_avg_position': round(last_10_avg, 2) if not pd.isna(last_10_avg) else None,
        'top_5_count': round(top_5_count, 2),
        'top_10_count': round(top_10_count, 2),
        'top_20_count': round(top_20_count, 2),
        'top_5_percentage_last_year': round(top_5_percentage, 1),
        'top_10_percentage_last_year': round(top_10_percentage, 1),
        'top_20_percentage_last_year': round(top_20_percentage, 1),
         # top finish counts — last 5 starts
        # 'top_3_last_5'                    : sum(1 for p in last_5_pos  if p <= 3), # maybeb delete this 
        'top_5_last_5'                    : sum(1 for p in last_5_pos  if p <= 5),
        'top_10_last_5'                   : sum(1 for p in last_5_pos  if p <= 10),
        'top_20_last_5'                   : sum(1 for p in last_5_pos  if p <= 20),
        # top finish counts — last 10 starts
        # 'top_3_last_10'                   : sum(1 for p in last_10_pos if p <= 3), # maybeb delete this 
        'top_5_last_10'                   : sum(1 for p in last_10_pos if p <= 5),
        'top_10_last_10'                  : sum(1 for p in last_10_pos if p <= 10),
        'top_20_last_10'                  : sum(1 for p in last_10_pos if p <= 20),

    })

In [14]:
results

[{'player': 'A.J. Ewart',
  'total_tournaments': 6,
  'games_with_positions': 6,
  'tournaments_last_year': 1,
  'cut_percentage_last_year': 0.0,
  'last_3_avg_position': np.float64(30.0),
  'last_5_avg_position': np.float64(42.8),
  'last_10_avg_position': np.float64(49.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 1,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 1},
 {'player': 'A.J. Ewart (a)',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aaron Baddeley',
  'total_tournaments': 61,
  'games_with_positions': 60,
  'tournaments_last_year': 12,
  'cut_percentage_last_year': 41.7,
  'last_3_avg_position': np.float64(77.33),
  'last_5_avg_position': np.float64(78.4),
  'last_10_avg_position': np.float64(69.6),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aaron Beverly',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aaron Cockerill',
  'total_tournaments': 5,
  'games_with_positions': 5,
  'tournaments_last_year': 1,
  'cut_percentage_last_year': 0.0,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(73.6),
  'last_10_avg_position': np.float64(73.6),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aaron Jarvis (a)',
  'total_tournaments': 2,
  'games_with_positions': 2,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aaron Rai',
  'total_tournaments': 92,
  'games_with_positions': 92,
  'tournaments_last_year': 20,
  'cut_percentage_last_year': 80.0,
  'last_3_avg_position': np.float64(41.33),
  'last_5_avg_position': np.float64(39.2),
  'last_10_avg_position': np.float64(33.2),
  'top_5_count': 2,
  'top_10_count': 2,
  'top_20_count': 7,
  'top_5_percentage_last_year': 10.0,
  'top_10_percentage_last_year': 10.0,
  'top_20_percentage_last_year': 35.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 1,
  'top_10_last_10': 1,
  'top_20_last_10': 2},
 {'player': 'Aaron Wise',
  'total_tournaments': 38,
  'games_with_positions': 37,
  'tournaments_last_year': 5,
  'cut_percentage_last_year': 40.0,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(74.2),
  'last_10_avg_position': np.float64(77.1),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Abraham Ancer',
  'total_tournaments': 16,
  'games_with_positions': 16,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(57.67),
  'last_5_avg_position': np.float64(57.0),
  'last_10_avg_position': np.float64(54.3),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 1,
  'top_20_last_10': 1},
 {'player': "Adam D'Amario",
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Adam Hadwin',
  'total_tournaments': 90,
  'games_with_positions': 90,
  'tournaments_last_year': 26,
  'cut_percentage_last_year': 61.5,
  'last_3_avg_position': np.float64(53.67),
  'last_5_avg_position': np.float64(58.8),
  'last_10_avg_position': np.float64(65.8),
  'top_5_count': 0,
  'top_10_count': 1,
  'top_20_count': 2,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 3.8,
  'top_20_percentage_last_year': 7.7,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 1,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 1},
 {'player': 'Adam Long',
  'total_tournaments': 63,
  'games_with_positions': 62,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(78.4),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Adam Schenk',
  'total_tournaments': 115,
  'games_with_positions': 112,
  'tournaments_last_year': 24,
  'cut_percentage_last_year': 50.0,
  'last_3_avg_position': np.float64(72.33),
  'last_5_avg_position': np.float64(61.6),
  'last_10_avg_position': np.float64(58.5),
  'top_5_count': 2,
  'top_10_count': 3,
  'top_20_count': 3,
  'top_5_percentage_last_year': 8.7,
  'top_10_percentage_last_year': 13.0,
  'top_20_percentage_last_year': 13.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 1,
  'top_5_last_10': 1,
  'top_10_last_10': 1,
  'top_20_last_10': 2},
 {'player': 'Adam Scott',
  'total_tournaments': 72,
  'games_with_positions': 72,
  'tournaments_last_year': 18,
  'cut_percentage_last_year': 83.3,
  'last_3_avg_position': np.float64(15.0),
  'last_5_avg_position': np.float64(21.8),
  'last_10_avg_position': np.float64(34.1),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 4,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 22.2,
  'top_5_last_5': 1,
  'top_10_last_5': 1,
  'top_20_last_5': 2,
  'top_5_last_10': 1,
  'top_10_last_10': 1,
  'top_20_last_10': 3},
 {'player': 'Adam Svensson',
  'total_tournaments': 109,
  'games_with_positions': 109,
  'tournaments_last_year': 23,
  'cut_percentage_last_year': 43.5,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(72.0),
  'last_10_avg_position': np.float64(67.7),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 1,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 4.3,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Adria Arnaus',
  'total_tournaments': 7,
  'games_with_positions': 7,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(76.0),
  'last_5_avg_position': np.float64(71.0),
  'last_10_avg_position': np.float64(66.43),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Adrian Meronk',
  'total_tournaments': 13,
  'games_with_positions': 13,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(69.4),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 1},
 {'player': 'Adrian Otaegui',
  'total_tournaments': 6,
  'games_with_positions': 6,
  'tournaments_last_year': 1,
  'cut_percentage_last_year': 0.0,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(73.67),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Adrien Dumont de Chassart',
  'total_tournaments': 28,
  'games_with_positions': 28,
  'tournaments_last_year': 2,
  'cut_percentage_last_year': 0.0,
  'last_3_avg_position': np.float64(61.0),
  'last_5_avg_position': np.float64(55.2),
  'last_10_avg_position': np.float64(54.4),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 1,
  'top_10_last_10': 1,
  'top_20_last_10': 1},
 {'player': 'Adrien Dumont de Chassart (a)',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Adrien Saddier',
  'total_tournaments': 7,
  'games_with_positions': 7,
  'tournaments_last_year': 2,
  'cut_percentage_last_year': 50.0,
  'last_3_avg_position': np.float64(65.33),
  'last_5_avg_position': np.float64(69.2),
  'last_10_avg_position': np.float64(68.29),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aguri Iwasaki',
  'total_tournaments': 3,
  'games_with_positions': 3,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(73.33),
  'last_5_avg_position': np.float64(73.33),
  'last_10_avg_position': np.float64(73.33),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Akshay Bhatia',
  'total_tournaments': 76,
  'games_with_positions': 75,
  'tournaments_last_year': 25,
  'cut_percentage_last_year': 80.0,
  'last_3_avg_position': np.float64(6.67),
  'last_5_avg_position': np.float64(21.2),
  'last_10_avg_position': np.float64(31.6),
  'top_5_count': 1,
  'top_10_count': 4,
  'top_20_count': 7,
  'top_5_percentage_last_year': 4.2,
  'top_10_percentage_last_year': 16.7,
  'top_20_percentage_last_year': 29.2,
  'top_5_last_5': 2,
  'top_10_last_5': 3,
  'top_20_last_5': 4,
  'top_5_last_10': 2,
  'top_10_last_10': 3,
  'top_20_last_10': 6},
 {'player': 'Alan Morin',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Albin Choi',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Aldrich Potgieter',
  'total_tournaments': 24,
  'games_with_positions': 23,
  'tournaments_last_year': 17,
  'cut_percentage_last_year': 47.1,
  'last_3_avg_position': np.float64(55.0),
  'last_5_avg_position': np.float64(61.0),
  'last_10_avg_position': np.float64(63.7),
  'top_5_count': 2,
  'top_10_count': 3,
  'top_20_count': 4,
  'top_5_percentage_last_year': 12.5,
  'top_10_percentage_last_year': 18.8,
  'top_20_percentage_last_year': 25.0,
  'top_5_last_5': 1,
  'top_10_last_5': 1,
  'top_20_last_5': 1,
  'top_5_last_10': 1,
  'top_10_last_10': 1,
  'top_20_last_10': 1},
 {'player': 'Aldrich Potgieter (a)',
  'total_tournaments': 3,
  'games_with_positions': 3,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(74.67),
  'last_5_avg_position': np.float64(74.67),
  'last_10_avg_position': np.float64(74.67),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Alejandro Del Rey',
  'total_tournaments': 3,
  'games_with_positions': 3,
  'tournaments_last_year': 1,
  'cut_percentage_last_year': 100.0,
  'last_3_avg_position': np.float64(51.67),
  'last_5_avg_position': np.float64(51.67),
  'last_10_avg_position': np.float64(51.67),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 1,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 1},
 {'player': 'Alejandro Madariaga',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 1,
  'cut_percentage_last_year': 100.0,
  'last_3_avg_position': np.float64(46.0),
  'last_5_avg_position': np.float64(46.0),
  'last_10_avg_position': np.float64(46.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Alejandro Tosti',
  'total_tournaments': 45,
  'games_with_positions': 44,
  'tournaments_last_year': 15,
  'cut_percentage_last_year': 40.0,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 1,
  'top_10_count': 2,
  'top_20_count': 3,
  'top_5_percentage_last_year': 6.7,
  'top_10_percentage_last_year': 13.3,
  'top_20_percentage_last_year': 20.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Alex Cejka',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Alex Chiarella',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Alex Fitzpatrick',
  'total_tournaments': 2,
  'games_with_positions': 2,
  'tournaments_last_year': 1,
  'cut_percentage_last_year': 0.0,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,
  'top_20_percentage_last_year': 0.0,
  'top_5_last_5': 0,
  'top_10_last_5': 0,
  'top_20_last_5': 0,
  'top_5_last_10': 0,
  'top_10_last_10': 0,
  'top_20_last_10': 0},
 {'player': 'Alex Fitzpatrick (a)',
  'total_tournaments': 1,
  'games_with_positions': 1,
  'tournaments_last_year': 0,
  'cut_percentage_last_year': None,
  'last_3_avg_position': np.float64(80.0),
  'last_5_avg_position': np.float64(80.0),
  'last_10_avg_position': np.float64(80.0),
  'top_5_count': 0,
  'top_10_count': 0,
  'top_20_count': 0,
  'top_5_percentage_last_year': 0.0,
  'top_10_percentage_last_year': 0.0,

In [15]:
# Convert to DataFrame
results_df = pd.DataFrame(results)

# Sort by best average position over last 5 games (lower is better)
results_df = results_df.sort_values('last_5_avg_position')

# Display results
top_n = 20
'''
print(f"Top {top_n} Players by Average Finish Position")
print("=" * 90)
print(f"{'Player':<25} {'Tournaments':<12} {'Cut %':<8} {'Last 3 Avg':<12} {'Last 5 Avg':<12}")
print("-" * 90)
'''
for idx, row in results_df.head(top_n).iterrows():
    #top_5 = f"{row['top_5_percentage']:.2f}" if row['top_5_percentage'] is not None else "N/A"
    last_3 = f"{row['last_3_avg_position']:.2f}" if row['last_3_avg_position'] is not None else "N/A"
    last_5 = f"{row['last_5_avg_position']:.2f}" if row['last_5_avg_position'] is not None else "N/A"
    cut_pct = f"{row['cut_percentage_last_year']:.1f}%" if row['cut_percentage_last_year'] is not None else "N/A"
    tournaments = f"{row['tournaments_last_year']}"
    
    print(f"{row['player']:<25} {tournaments:<12} {cut_pct:<8} {last_3:<12} {last_5:<12}")

# print(f"\nTotal players analyzed: {len(results_df)}")
 # print(f"Cut percentage calculated over {current_year - last_year_cutoff + 1} year(s) of data")

# Save results to a new CSV
# results_df.to_csv('player_average_positions.csv', index=False)

Jackson Koivun            1            100.0%   4.00         4.00
Jake Knapp                22           72.7%    7.33         7.60
Scottie Scheffler         20           100.0%   13.00        8.80
Jacob Bridgeman           29           62.1%    12.33        11.60
Rory McIlroy              15           93.3%    13.00        11.60
Tommy Fleetwood           19           94.7%    20.00        13.00
John Keefer               0            nan%     13.00        13.00
Nicolai Højgaard          16           62.5%    11.00        13.80
Min Woo Lee               19           73.7%    15.33        17.20
Hideki Matsuyama          23           87.0%    23.67        18.00
Rickie Fowler             21           90.5%    18.33        18.40
Si Woo Kim                29           75.9%    16.67        19.40
Ryo Hisatsune             27           63.0%    29.33        19.60
Bryson DeChambeau         4            75.0%    30.67        19.60
Ryutaro Nagano            0            nan%     20.50        20.50
Akshay Bhatia             25           80.0%    6.67         21.20
Adam Scott                18           83.3%    15.00        21.80
Sahith Theegala           21           71.4%    15.33        22.60
Harris English            23           91.3%    24.67        24.00
Tyrrell Hatton            4            100.0%   26.67        24.00

In [16]:
#filtered_df = results_df[results_df['tournaments_last_year'] > 3]
filtered_df = results_df #[results_df['tournaments_last_year'] > 3]

In [17]:
filtered_df

,player,total_tournaments,games_with_positions,tournaments_last_year,cut_percentage_last_year,last_3_avg_position,last_5_avg_position,last_10_avg_position,top_5_count,top_10_count,top_20_count,top_5_percentage_last_year,top_10_percentage_last_year,top_20_percentage_last_year,top_5_last_5,top_10_last_5,top_20_last_5,top_5_last_10,top_10_last_10,top_20_last_10
464,Jackson Koivun,1,1,1,100.0,4.00,4.0,4.0,1,1,1,100.0,100.0,100.0,1,1,1,1,1,1
481,Jake Knapp,51,49,22,72.7,7.33,7.6,22.6,2,3,5,9.1,13.6,22.7,1,4,5,2,5,6
1004,Scottie Scheffler,80,80,20,100.0,13.00,8.8,5.4,12,17,19,60.0,85.0,95.0,3,3,4,8,8,9
471,Jacob Bridgeman,57,57,29,62.1,12.33,11.6,29.5,4,4,7,13.8,13.8,24.1,1,2,5,2,3,6
937,Rory McIlroy,63,62,15,93.3,13.00,11.6,21.2,5,8,12,33.3,53.3,80.0,1,2,4,2,4,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,A.J. Ewart (a),1,1,0,NaN,80.00,80.0,80.0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0
1183,Zander Lombard,1,1,0,NaN,80.00,80.0,80.0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0
31,Alex Chiarella,1,1,0,NaN,80.00,80.0,80.0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0
540,Joey Herrera,1,1,1,0.0,80.00,80.0,80.0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0
666,Kyle Wilshire,2,2,0,NaN,80.50,80.5,80.5,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0

In [18]:
filtered_df['last_3_avg_position_percentile'] = filtered_df['last_3_avg_position'].rank(pct=True,ascending=False)
filtered_df['last_5_avg_position_percentile'] = filtered_df['last_5_avg_position'].rank(pct=True,ascending=False)
filtered_df['last_10_avg_position_percentile'] = filtered_df['last_10_avg_position'].rank(pct=True,ascending=False)
filtered_df['cut_percentage_last_year_percentile'] = filtered_df['cut_percentage_last_year'].rank(pct=True,ascending=True)
filtered_df['top_5_percentage_last_year_percentile'] = filtered_df['top_5_percentage_last_year'].rank(pct=True,ascending=True)
filtered_df['top_10_percentage_last_year_percentile'] = filtered_df['top_10_percentage_last_year'].rank(pct=True,ascending=True)
filtered_df['top_20_percentage_last_year_percentile'] = filtered_df['top_20_percentage_last_year'].rank(pct=True,ascending=True)

#filtered_df['top_3_last_5_percentile'] = filtered_df['top_3_last_5'].rank(pct=True,ascending=True)
filtered_df['top_5_last_5_percentile'] = filtered_df['top_5_last_5'].rank(pct=True,ascending=True)
filtered_df['top_10_last_5_percentile'] = filtered_df['top_10_last_5'].rank(pct=True,ascending=True)
filtered_df['top_20_last_5_percentile'] = filtered_df['top_20_last_5'].rank(pct=True,ascending=True)


#filtered_df['top_3_last_10_percentile'] = filtered_df['top_3_last_10'].rank(pct=True,ascending=True)
filtered_df['top_5_last_10_percentile'] = filtered_df['top_5_last_10'].rank(pct=True,ascending=True)
filtered_df['top_10_last_10_percentile'] = filtered_df['top_10_last_10'].rank(pct=True,ascending=True)
filtered_df['top_20_last_10_percentile'] = filtered_df['top_20_last_10'].rank(pct=True,ascending=True)

In [19]:
# ok have 2 datasets; results and joined_df. 
# I need to join these 2 datasets together on player name

In [20]:
merged_dataset = pd.merge(joined_df, filtered_df, on='player', how='left')

In [21]:
merged_dataset = merged_dataset[merged_dataset['tournaments_last_year'] > 4]

In [22]:
metric_col_1 = 'SG_last_1_percentile'
metric_col_2 = 'SG_last_2_percentile'
metric_col_3 = 'SG_last_3_percentile'
metric_col_4 = 'SG_last_5_percentile'
metric_col_5 = 'SG_last_8_percentile'
metric_col_6 = 'SG_last_13_percentile'
metric_col_7 = 'SG_last_21_percentile'
metric_col_8 = 'SG_last_34_percentile'
metric_col_9 = 'SG_last_55_percentile'
metric_col_10 = 'dg_index_percentile'
metric_col_11 = 'owgr_rank_percentile'
metric_col_12 = 'last_3_avg_position_percentile'
metric_col_13 = 'last_5_avg_position_percentile'
metric_col_14 = 'last_10_avg_position_percentile'
metric_col_15 = 'cut_percentage_last_year_percentile'
metric_col_16 = 'top_5_percentage_last_year_percentile'
metric_col_17 = 'top_10_percentage_last_year_percentile'
metric_col_18 = 'top_20_percentage_last_year_percentile'

#metric_col_19 = 'top_3_last_5_percentile' 

metric_col_19 = 'top_5_last_5_percentile' 
metric_col_20 = 'top_10_last_5_percentile' 
metric_col_21 = 'top_20_last_5_percentile' 

#metric_col_22 = 'top_3_last_10_percentile' 
metric_col_22 = 'top_5_last_10_percentile' 
metric_col_23 = 'top_10_last_10_percentile' 
metric_col_24 = 'top_20_last_10_percentile'

In [23]:
'''
# First Version, there was too much weight on most recent events. 
# This is a problem because some events have worse fields and this makes less competitive fields have an advantage. 

weight_1 = 0.982   # SG_last_1_percentile
weight_2 = 1.35   # SG_last_2_percentile
weight_3 = 1.312   # SG_last_3_percentile
weight_4 = 1.033   # SG_last_5_percentile
weight_5 = 0.911   # SG_last_8_percentile
weight_6 = 0.455   # SG_last_13_percentile
weight_7 = 0.102   # SG_last_21_percentile
weight_8 = 0.28   # SG_last_34_percentile
weight_9 = 0.30   # SG_last_55_percentile
weight_10 = 1.3  # dg_index_percentile
weight_11 = 0.5  # owgr_rank_percentile
weight_12 = 1.7  # last_3_avg_position_percentile
weight_13 = 1.6  # last_5_avg_position_percentile
weight_14 = 1.45  # last_10_avg_position_percentile
weight_15 = 1.26  # cut_percentage_last_year_percentile
weight_16 = 0.7  # top_5_percentage_last_year_percentile
weight_17 = 0.98  # top_10_percentage_last_year_percentile
weight_18 = 0.923  # top_20_percentage_last_year_percentile

weight_19 = 1.623  # top_5_last_5_percentile
weight_20 = 1.423  # top_10_last_5_percentile
weight_21 = 1.283  # top_20_last_5_percentile  

weight_22 = 1.523  # top_5_last_10_percentile 
weight_23 = 1.323  # top_10_last_10_percentile
weight_24 = 1.483  # top_20_last_10_percentile 



# Calculate total weight for normalization
total_weight = (weight_1 + weight_2 + weight_3 + weight_4 + weight_5 + 
               weight_6 + weight_7 + weight_8 + weight_9 + weight_10 + weight_10
               + weight_11 + weight_12 + weight_13 + weight_14 + weight_15 + weight_16 + weight_17 + weight_18 +
               weight_19 + weight_20 + weight_21 + weight_22 + weight_23 + weight_24)
'''

'\n# First Version, there was too much weight on most recent events. \n# This is a problem because some events have worse fields and this makes less competitive fields have an advantage. \n\nweight_1 = 0.982   # SG_last_1_percentile\nweight_2 = 1.35   # SG_last_2_percentile\nweight_3 = 1.312   # SG_last_3_percentile\nweight_4 = 1.033   # SG_last_5_percentile\nweight_5 = 0.911   # SG_last_8_percentile\nweight_6 = 0.455   # SG_last_13_percentile\nweight_7 = 0.102   # SG_last_21_percentile\nweight_8 = 0.28   # SG_last_34_percentile\nweight_9 = 0.30   # SG_last_55_percentile\nweight_10 = 1.3  # dg_index_percentile\nweight_11 = 0.5  # owgr_rank_percentile\nweight_12 = 1.7  # last_3_avg_position_percentile\nweight_13 = 1.6  # last_5_avg_position_percentile\nweight_14 = 1.45  # last_10_avg_position_percentile\nweight_15 = 1.26  # cut_percentage_last_year_percentile\nweight_16 = 0.7  # top_5_percentage_last_year_percentile\nweight_17 = 0.98  # top_10_percentage_last_year_percentile\nweight_18 = 0.923  # top_20_percentage_last_year_percentile\n\nweight_19 = 1.623  # top_5_last_5_percentile\nweight_20 = 1.423  # top_10_last_5_percentile\nweight_21 = 1.283  # top_20_last_5_percentile  \n\nweight_22 = 1.523  # top_5_last_10_percentile \nweight_23 = 1.323  # top_10_last_10_percentile\nweight_24 = 1.483  # top_20_last_10_percentile \n\n\n\n# Calculate total weight for normalization\ntotal_weight = (weight_1 + weight_2 + weight_3 + weight_4 + weight_5 + \n               weight_6 + weight_7 + weight_8 + weight_9 + weight_10 + weight_10\n               + weight_11 + weight_12 + weight_13 + weight_14 + weight_15 + weight_16 + weight_17 + weight_18 +\n               weight_19 + weight_20 + weight_21 + weight_22 + weight_23 + weight_24)\n'

In [24]:
# First Version, there was too much weight on most recent events. 
# This is a problem because some events have worse fields and this makes less competitive fields have an advantage. 

weight_1	=	0.75	#	SG_last_1_percentile
weight_2	=	0.75	#	SG_last_2_percentile
weight_3	=	0.75	#	SG_last_3_percentile
weight_4	=	0.75	#	SG_last_5_percentile
weight_5	=	0.5	#	SG_last_8_percentile
weight_6	=	0.5	#	SG_last_13_percentile
weight_7	=	0.5	#	SG_last_21_percentile
weight_8	=	0.25	#	SG_last_34_percentile
weight_9	=	0.25	#	SG_last_55_percentile
weight_10 = 1.5     # dg_index_percentile
weight_11 = 0.5     # owgr_rank_percentile
weight_12 = 0.5     # last_3_avg_position_percentile
weight_13 = 0.75    # last_5_avg_position_percentile
weight_14 = 0.5     # last_10_avg_position_percentile
weight_15 = 0.75    # cut_percentage_last_year_percentile
weight_16 = 0.75    # top_5_percentage_last_year_percentile
weight_17 = 0.5     # top_10_percentage_last_year_percentile
weight_18 = 0.5     # top_20_percentage_last_year_percentile
weight_19 = 1       # top_5_last_5_percentile
weight_20 = 1.25    # top_10_last_5_percentile
weight_21 = 0.5     # top_20_last_5_percentile
weight_22 = 1       # top_5_last_10_percentile
weight_23 = 1.25    # top_10_last_10_percentile
weight_24 = 0.5     # top_20_last_10_percentile

# Calculate total weight for normalization
total_weight = (weight_1 + weight_2 + weight_3 + weight_4 + weight_5 + 
               weight_6 + weight_7 + weight_8 + weight_9 + weight_10 +
               weight_11 + weight_12 + weight_13 + weight_14 + weight_15 + weight_16 + weight_17 + weight_18 +
               weight_19 + weight_20 + weight_21 + weight_22 + weight_23 + weight_24)

In [25]:
# Normalize weights so they sum to 1
norm_weight_1 = weight_1 / total_weight
norm_weight_2 = weight_2 / total_weight
norm_weight_3 = weight_3 / total_weight
norm_weight_4 = weight_4 / total_weight
norm_weight_5 = weight_5 / total_weight
norm_weight_6 = weight_6 / total_weight
norm_weight_7 = weight_7 / total_weight
norm_weight_8 = weight_8 / total_weight
norm_weight_9 = weight_9 / total_weight
norm_weight_10 = weight_10 / total_weight
norm_weight_11 = weight_11 / total_weight
norm_weight_12 = weight_12 / total_weight
norm_weight_13 = weight_13 / total_weight
norm_weight_14 = weight_14 / total_weight
norm_weight_15 = weight_15 / total_weight
norm_weight_16 = weight_16 / total_weight
norm_weight_17 = weight_17 / total_weight
norm_weight_18 = weight_18 / total_weight
norm_weight_19 = weight_19 / total_weight
norm_weight_20 = weight_20 / total_weight
norm_weight_21 = weight_21 / total_weight
norm_weight_22 = weight_22 / total_weight
norm_weight_23 = weight_23 / total_weight
norm_weight_24 = weight_24 / total_weight


print("Normalized weights (should sum to 1.0):")
print(f"{metric_col_1}: {norm_weight_1:.3f}")
print(f"{metric_col_2}: {norm_weight_2:.3f}")
print(f"{metric_col_3}: {norm_weight_3:.3f}")
print(f"{metric_col_4}: {norm_weight_4:.3f}")
print(f"{metric_col_5}: {norm_weight_5:.3f}")
print(f"{metric_col_6}: {norm_weight_6:.3f}")
print(f"{metric_col_7}: {norm_weight_7:.3f}")
print(f"{metric_col_8}: {norm_weight_8:.3f}")
print(f"{metric_col_9}: {norm_weight_9:.3f}")
print(f"{metric_col_10}: {norm_weight_10:.3f}")
print(f"{metric_col_11}: {norm_weight_11:.3f}")
print(f"{metric_col_12}: {norm_weight_12:.3f}")
print(f"{metric_col_13}: {norm_weight_13:.3f}")
print(f"{metric_col_14}: {norm_weight_14:.3f}")
print(f"{metric_col_15}: {norm_weight_15:.3f}")
print(f"{metric_col_16}: {norm_weight_16:.3f}")
print(f"{metric_col_17}: {norm_weight_17:.3f}")
print(f"{metric_col_18}: {norm_weight_18:.3f}")
print(f"{metric_col_19}: {norm_weight_19:.3f}")
print(f"{metric_col_20}: {norm_weight_20:.3f}")
print(f"{metric_col_21}: {norm_weight_21:.3f}")
print(f"{metric_col_22}: {norm_weight_22:.3f}")
print(f"{metric_col_23}: {norm_weight_23:.3f}")
print(f"{metric_col_24}: {norm_weight_24:.3f}")
print(f"Total: {sum([norm_weight_1, norm_weight_2, norm_weight_3, norm_weight_4, norm_weight_5
                     , norm_weight_6, norm_weight_7, norm_weight_8, norm_weight_9, norm_weight_10
                     , norm_weight_11, norm_weight_12, norm_weight_13, norm_weight_14, norm_weight_15, norm_weight_16
                     , norm_weight_17, norm_weight_18, norm_weight_19, norm_weight_20, norm_weight_21
                     , norm_weight_22, norm_weight_23, norm_weight_24]):.3f}")
print()

Normalized weights (should sum to 1.0):
SG_last_1_percentile: 0.045
SG_last_2_percentile: 0.045
SG_last_3_percentile: 0.045
SG_last_5_percentile: 0.045
SG_last_8_percentile: 0.030
SG_last_13_percentile: 0.030
SG_last_21_percentile: 0.030
SG_last_34_percentile: 0.015
SG_last_55_percentile: 0.015
dg_index_percentile: 0.090
owgr_rank_percentile: 0.030
last_3_avg_position_percentile: 0.030
last_5_avg_position_percentile: 0.045
last_10_avg_position_percentile: 0.030
cut_percentage_last_year_percentile: 0.045
top_5_percentage_last_year_percentile: 0.045
top_10_percentage_last_year_percentile: 0.030
top_20_percentage_last_year_percentile: 0.030
top_5_last_5_percentile: 0.060
top_10_last_5_percentile: 0.075
top_20_last_5_percentile: 0.030
top_5_last_10_percentile: 0.060
top_10_last_10_percentile: 0.075
top_20_last_10_percentile: 0.030
Total: 1.000

In [26]:
# Calculate weighted composite score for each player
weighted_scores = []

for index, row in merged_dataset.iterrows():
    # Get the values for each metric (handle missing values)
    val_1 = row[metric_col_1] if not pd.isna(row[metric_col_1]) else 0
    val_2 = row[metric_col_2] if not pd.isna(row[metric_col_2]) else 0
    val_3 = row[metric_col_3] if not pd.isna(row[metric_col_3]) else 0
    val_4 = row[metric_col_4] if not pd.isna(row[metric_col_4]) else 0
    val_5 = row[metric_col_5] if not pd.isna(row[metric_col_5]) else 0
    val_6 = row[metric_col_6] if not pd.isna(row[metric_col_6]) else 0
    val_7 = row[metric_col_7] if not pd.isna(row[metric_col_7]) else 0
    val_8 = row[metric_col_8] if not pd.isna(row[metric_col_8]) else 0
    val_9 = row[metric_col_9] if not pd.isna(row[metric_col_9]) else 0
    val_10 = row[metric_col_10] if not pd.isna(row[metric_col_10]) else 0
    val_11 = row[metric_col_11] if not pd.isna(row[metric_col_11]) else 0
    val_12 = row[metric_col_12] if not pd.isna(row[metric_col_12]) else 0
    val_13 = row[metric_col_13] if not pd.isna(row[metric_col_13]) else 0
    val_14 = row[metric_col_14] if not pd.isna(row[metric_col_14]) else 0
    val_15 = row[metric_col_15] if not pd.isna(row[metric_col_15]) else 0
    val_16 = row[metric_col_16] if not pd.isna(row[metric_col_16]) else 0
    val_17 = row[metric_col_17] if not pd.isna(row[metric_col_17]) else 0
    val_18 = row[metric_col_18] if not pd.isna(row[metric_col_18]) else 0
    val_19 = row[metric_col_19] if not pd.isna(row[metric_col_19]) else 0
    val_20 = row[metric_col_20] if not pd.isna(row[metric_col_20]) else 0
    val_21 = row[metric_col_21] if not pd.isna(row[metric_col_21]) else 0
    val_22 = row[metric_col_22] if not pd.isna(row[metric_col_22]) else 0
    val_23 = row[metric_col_23] if not pd.isna(row[metric_col_23]) else 0
    val_24 = row[metric_col_24] if not pd.isna(row[metric_col_24]) else 0
    
    # Calculate weighted score
    weighted_score = (val_1 * norm_weight_1 + 
                     val_2 * norm_weight_2 + 
                     val_3 * norm_weight_3 + 
                     val_4 * norm_weight_4 + 
                     val_5 * norm_weight_5 + 
                     val_6 * norm_weight_6 + 
                     val_7 * norm_weight_7 + 
                     val_8 * norm_weight_8 + 
                     val_9 * norm_weight_9 + 
                     val_10 * norm_weight_10 +
                     val_11 * norm_weight_11 +
                     val_12 * norm_weight_12 +
                     val_13 * norm_weight_13 +
                     val_14 * norm_weight_14 +
                     val_15 * norm_weight_15 + 
                     val_16 * norm_weight_16 +
                     val_17 * norm_weight_17 +
                     val_18 * norm_weight_18 +
                     val_19 * norm_weight_19 +
                     val_20 * norm_weight_20 +
                     val_21 * norm_weight_21 +
                     val_22 * norm_weight_22 +
                     val_23 * norm_weight_23 +
                     val_24 * norm_weight_24)
    
    weighted_scores.append(weighted_score)

In [27]:
# Add weighted scores to dataframe
merged_dataset['weighted_composite'] = weighted_scores

# Calculate final percentile rank manually
# Sort the weighted scores and assign ranks
df_sorted = merged_dataset.sort_values('weighted_composite', ascending=False)
df_sorted['rank'] = range(1, len(df_sorted) + 1)

df_sorted['composite_percentile_rank'] = df_sorted['weighted_composite'].rank(pct=True,ascending=True)

In [28]:
df_sorted = df_sorted.round(4)
composite_with_percentile = df_sorted[['player', 'weighted_composite', 'composite_percentile_rank']].copy()
#composite_with_percentile.loc[composite_with_percentile['player'] == 'Ludvig Åberg', 'player'] = 'Ludvig Aberg'

# Enter updated player list here!

In [29]:
# Link to Tier List for Golfers 
# tier_df = pd.read_csv('/Users/brandon/Desktop/Golf_Data/eastlake_list.csv') # Mac Link
tier_df = pd.read_csv(r"C:\Users\brand\OneDrive\Documents\pga_stats\upload_staging\player_list\players_list.csv")

In [30]:
playerlist_metrics = pd.merge(
    tier_df, 
    composite_with_percentile, 
    on='player', 
    how='left'  # Keep all tier players, even if no composite score
)

In [31]:
# STEP 6: Analyze by tier
print("\n=== TOURNAMENT TIER ANALYSIS ===")
print("Best players in each Tier (by composite score):")
print("=" * 70)

for tier_num in sorted(playerlist_metrics['Tier'].unique()):
    tier_players = playerlist_metrics[playerlist_metrics['Tier'] == tier_num].sort_values('weighted_composite', ascending=False)
    
    print(f"\nTIER {tier_num} (Top 5):")
    print(f"{'Rank':<4} {'Player':<25} {'Composite':<12} {'Percentile':<12}")
    print("-" * 55)
    
    for i, (_, player) in enumerate(tier_players.iterrows(), 1):
        comp_score = f"{player['weighted_composite']:.4f}" if not pd.isna(player['weighted_composite']) else "N/A"
        pct_rank = f"{player['composite_percentile_rank']:.4f}%" if not pd.isna(player['composite_percentile_rank']) else "N/A"
        print(f"{i:<4} {player['player']:<25} {comp_score:<12} {pct_rank:<12}")

# STEP 7: Optimal picks for your competition
print("\n=== OPTIMAL PICKS FOR COMPETITION ===")
print("Best player from each tier:")
print("=" * 60)

optimal_picks = []
total_composite = 0

for tier_num in sorted(playerlist_metrics['Tier'].unique()):
    tier_players = playerlist_metrics[playerlist_metrics['Tier'] == tier_num].sort_values('weighted_composite', ascending=False)
    best_player = tier_players.iloc[0]
    
    optimal_picks.append({
        'Tier': tier_num,
        'player': best_player['player'],
        'composite_score': best_player['weighted_composite'],
        'percentile_rank': best_player['composite_percentile_rank']
    })
    
    total_composite += best_player['weighted_composite']
    
    comp_score = f"{best_player['weighted_composite']:.4f}" if not pd.isna(best_player['weighted_composite']) else "N/A"
    pct_rank = f"{best_player['composite_percentile_rank']:.4f}%" if not pd.isna(best_player['composite_percentile_rank']) else "N/A"
    
    print(f"Tier {tier_num}: {best_player['player']:<25} (Score: {comp_score}, Rank: {pct_rank})")

print(f"\nTotal Team Composite Score: {total_composite:.4f}")
print(f"Average Team Composite Score: {total_composite/6:.4f}")

=== TOURNAMENT TIER ANALYSIS ===
Best players in each Tier (by composite score):
======================================================================

TIER 1 (Top 5):
Rank Player                    Composite    Percentile
-------------------------------------------------------
1    Scottie Scheffler         0.9900       1.0000%
2    Tommy Fleetwood           0.9791       0.9955%
3    Rory McIlroy              0.9574       0.9548%

TIER 2 (Top 5):
Rank Player                    Composite    Percentile
-------------------------------------------------------
1    Collin Morikawa           0.9776       0.9864%
2    Si Woo Kim                0.9678       0.9729%
3    Robert MacIntyre          0.9649       0.9683%
4    Hideki Matsuyama          0.9554       0.9502%
5    Russell Henley            0.9466       0.9412%
6    Chris Gotterup            0.9432       0.9367%
7    Xander Schauffele         0.9343       0.9231%
8    Matt Fitzpatrick          0.9315       0.9140%
9    Viktor Hovland            0.9297       0.9095%
10   Ludvig Åberg              0.8469       0.8100%

TIER 3 (Top 5):
Rank Player                    Composite    Percentile
-------------------------------------------------------
1    Cameron Young             0.9780       0.9910%
2    Jacob Bridgeman           0.9592       0.9638%
3    Shane Lowry               0.9325       0.9186%
4    Jason Day                 0.8739       0.8688%
5    Justin Rose               0.8681       0.8643%
6    Patrick Cantlay           0.8476       0.8190%
7    Justin Thomas             0.8420       0.7964%
8    Ben Griffin               0.8405       0.7919%
9    Sam Burns                 0.8176       0.7376%
10   Brooks Koepka             N/A          N/A

TIER 4 (Top 5):
Rank Player                    Composite    Percentile
-------------------------------------------------------
1    Jake Knapp                0.9721       0.9819%
2    Akshay Bhatia             0.9715       0.9774%
3    Min Woo Lee               0.9582       0.9593%
4    Kurt Kitayama             0.9507       0.9457%
5    Sepp Straka               0.9427       0.9321%
6    Maverick McNealy          0.9228       0.9050%
7    Rickie Fowler             0.8837       0.8733%
8    Jordan Spieth             0.8488       0.8235%
9    Nicolai Højgaard          0.8397       0.7828%
10   Harris English            0.8056       0.7059%

TIER 5 (Top 5):
Rank Player                    Composite    Percentile
-------------------------------------------------------
1    Michael Thorbjornsen      0.9150       0.8824%
2    Adam Scott                0.9128       0.8778%
3    Alex Noren                0.8640       0.8507%
4    Ryan Gerard               0.8472       0.8145%
5    Aaron Rai                 0.8463       0.8054%
6    Wyndham Clark             0.8396       0.7783%
7    Max Homa                  0.8089       0.7195%
8    Rasmus Højgaard           0.8062       0.7104%
9    Nick Taylor               0.7840       0.6561%
10   J.J. Spaun                0.7787       0.6425%

TIER 6 (Top 5):
Rank Player                    Composite    Percentile
-------------------------------------------------------
1    Daniel Berger             0.9423       0.9276%
2    Ryo Hisatsune             0.9225       0.9005%
3    Nico Echavarria           0.9214       0.8959%
4    Pierceson Coody           0.9204       0.8914%
5    Ricky Castillo            0.9169       0.8869%
6    Ryan Fox                  0.8675       0.8597%
7    Lee Hodges                0.8660       0.8552%
8    Harry Hall                0.8598       0.8462%
9    Matt McCarty              0.8542       0.8416%
10   Stephan Jaeger            0.8521       0.8371%
11   Sahith Theegala           0.8519       0.8326%
12   Taylor Moore              0.8506       0.8281%
13   Keith Mitchell            0.8462       0.8009%
14   Corey Conners             0.8403       0.7873%
15   Andrew Novak              0.8387       0.7738%
16   Alex Smalley              0.8365       0.7647%
17   Patrick Rodgers           0.8355       0.7602%
18   Max Greyserman            0.8332       0.7557%
19   Max McGreevy              0.8192       0.7421%
20   Christiaan Bezuidenhout   0.8129       0.7330%
21   Takumi Kanaya             0.8108       0.7285%
22   Chad Ramey                0.8098       0.7240%
23   Aldrich Potgieter         0.8083       0.7149%
24   Lucas Glover              0.8039       0.6968%
25   Matti Schmid              0.8026       0.6923%
26   Sam Stevens               0.8025       0.6878%
27   Taylor Pendrith           0.7974       0.6787%
28   Andrew Putnam             0.7947       0.6742%
29   Garrick Higgo             0.7922       0.6697%
30   Michael Kim               0.7906       0.6652%
31   Mackenzie Hughes          0.7806       0.6516%
32   Kevin Roy                 0.7677       0.6335%
33   Eric Cole                 0.7675       0.6290%
34   Emiliano Grillo           0.7665       0.6244%
35   Joel Dahmen               0.7664       0.6199%
36   Chris Kirk                0.7654       0.6154%
37   William Mouw              0.7600       0.6109%
38   Tony Finau                0.7585       0.6063%
39   Chandler Phillips         0.7568       0.6018%
40   Mac Meissner              0.7523       0.5928%
41   Keegan Bradley            0.7511       0.5882%
42   Bud Cauley                0.7494       0.5837%
43   Steven Fisk               0.7488       0.5792%
44   Rico Hoey                 0.7455       0.5701%
45   J.T. Poston               0.7346       0.5611%
46   Denny McCarthy            0.7157       0.5520%
47   Johnny Keefer             0.7153       0.5475%
48   Davis Thompson            0.7096       0.5385%
49   Danny Walker              0.7037       0.5294%
50   Jhonattan Vegas           0.7030       0.5249%
51   Thorbjørn Olesen          0.7003       0.5158%
52   Vince Whaley              0.6897       0.4977%
53   Adam Schenk               0.6767       0.4706%
54   Mark Hubbard              0.6706       0.4661%
55   Tom Hoge                  0.6692       0.4615%
56   Matthieu Pavon            0.6614       0.4480%
57   Davis Riley               0.6604       0.4389%
58   Gary Woodland             0.6592       0.4344%
59   Sungjae Im                0.6545       0.4299%
60   Brian Harman              0.6198       0.3710%
61   Karl Vilips               0.6094       0.3529%
62   Kevin Yu                  0.5679       0.2896%
63   Joe Highsmith             0.5224       0.2217%
64   Brian Campbell            0.5023       0.1991%
65   Cam Davis                 0.4952       0.1855%
66   A.J. Ewart                N/A          N/A
67   Austin Smotherman         N/A          N/A
68   Erik Van Rooyen           N/A          N/A
69   Hao-Tong Li               N/A          N/A
70   Jordan Smith              N/A          N/A
71   Kristoffer Reitan         N/A          N/A
72   Marco Penge               N/A          N/A
73   Michael Brennan           N/A          N/A
74   S.H. Kim                  N/A          N/A
75   Sami Välimäki             N/A          N/A
76   Sudarshan Yellamaraju     N/A          N/A
77   Zach Bauchou              N/A          N/A
78   Zecheng Dou               N/A          N/A

=== OPTIMAL PICKS FOR COMPETITION ===
Best player from each tier:
============================================================
Tier 1: Scottie Scheffler         (Score: 0.9900, Rank: 1.0000%)
Tier 2: Collin Morikawa           (Score: 0.9776, Rank: 0.9864%)
Tier 3: Cameron Young             (Score: 0.9780, Rank: 0.9910%)
Tier 4: Jake Knapp                (Score: 0.9721, Rank: 0.9819%)
Tier 5: Michael Thorbjornsen      (Score: 0.9150, Rank: 0.8824%)
Tier 6: Daniel Berger             (Score: 0.9423, Rank: 0.9276%)

Total Team Composite Score: 5.7750
Average Team Composite Score: 0.9625

In [32]:
df_sorted

,player,pos,to_par,year,week_of_season,tournament,course,avg,updated_avg,total_sg_t,...,top_20_percentage_last_year_percentile,top_5_last_5_percentile,top_10_last_5_percentile,top_20_last_5_percentile,top_5_last_10_percentile,top_10_last_10_percentile,top_20_last_10_percentile,weighted_composite,rank,composite_percentile_rank
1005,Scottie Scheffler,T24,-2,2026,10.0,Arnold Palmer Invitational,Arnold Palmer's Bay Hill Club and Lodge,0.217,0.217,0.867,...,0.9949,0.9992,0.9962,0.9954,1.0000,1.0000,0.9996,0.9900,1,1.0000
1101,Tommy Fleetwood,49,6,2026,10.0,Arnold Palmer Invitational,Arnold Palmer's Bay Hill Club and Lodge,-1.783,-1.783,-7.133,...,0.9903,0.9992,0.9992,0.9954,0.9987,0.9979,0.9949,0.9791,2,0.9955
197,Cameron Young,T3,-12,2026,10.0,Arnold Palmer Invitational,Arnold Palmer's Bay Hill Club and Lodge,2.717,2.717,10.867,...,0.9751,0.9760,0.9861,0.9617,0.9975,0.9979,0.9949,0.9780,3,0.9910
255,Collin Morikawa,5,-11,2026,10.0,Arnold Palmer Invitational,Arnold Palmer's Bay Hill Club and Lodge,2.467,2.467,9.867,...,0.9874,0.9958,0.9962,0.9853,0.9853,0.9802,0.9823,0.9776,4,0.9864
482,Jake Knapp,6,-13,2026,7.0,The Genesis Invitational,The Riviera Country Club,1.904,1.904,7.614,...,0.9141,0.9760,0.9992,0.9996,0.9853,0.9966,0.9903,0.9721,5,0.9819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,Ryan Palmer,T21,-16,2025,41.0,The RSM Classic,Sea Island Golf Club,None,-2,None,...,0.4166,0.4794,0.4608,0.4153,0.4579,0.4313,0.3787,0.4045,217,0.0226
272,Cristobal Del Solar,CUT,-6,2025,41.0,The RSM Classic,Sea Island Golf Club,None,-2,None,...,0.4166,0.4794,0.4608,0.4153,0.4579,0.4313,0.3787,0.4038,218,0.0181
1000,Scott Piercy,CUT,-3,2025,41.0,The RSM Classic,Sea Island Golf Club,None,-2,None,...,0.4166,0.4794,0.4608,0.4153,0.4579,0.4313,0.3787,0.3995,219,0.0136
231,Chez Reavie,71,-6,2025,41.0,The RSM Classic,Sea Island Golf Club,None,-2,None,...,0.4166,0.4794,0.4608,0.4153,0.4579,0.4313,0.3787,0.3983,220,0.0090
406,Gordon Sargent,CUT,1,2026,9.0,Cognizant Classic in The Palm Beaches,PGA National Resort,None,-2,None,...,0.4166,0.4794,0.4608,0.4153,0.4579,0.4313,0.3787,0.3973,221,0.0045

In [33]:
# Add this dataframe 
merged_dataset

,player,pos,to_par,year,week_of_season,tournament,course,avg,updated_avg,total_sg_t,...,top_5_percentage_last_year_percentile,top_10_percentage_last_year_percentile,top_20_percentage_last_year_percentile,top_5_last_5_percentile,top_10_last_5_percentile,top_20_last_5_percentile,top_5_last_10_percentile,top_10_last_10_percentile,top_20_last_10_percentile,weighted_composite
2,Aaron Baddeley,T72,2,2025,31.0,Wyndham Championship,Sedgefield Country Club,-1.204,-1.204,-4.816,...,0.447346,0.431340,0.416596,0.47936,0.460826,0.415333,0.457877,0.431340,0.378686,0.487527
6,Aaron Rai,T23,-7,2026,9.0,Cognizant Classic in The Palm Beaches,PGA National Resort,1.008,1.008,4.033,...,0.962089,0.924600,0.959983,0.47936,0.460826,0.415333,0.945661,0.900590,0.902696,0.846263
7,Aaron Wise,CUT,7,2026,9.0,Cognizant Classic in The Palm Beaches,PGA National Resort,None,-2,None,...,0.447346,0.431340,0.416596,0.47936,0.460826,0.415333,0.457877,0.431340,0.378686,0.419735
10,Adam Hadwin,CUT,3,2026,9.0,Cognizant Classic in The Palm Beaches,PGA National Resort,None,-2,None,...,0.447346,0.864364,0.847094,0.47936,0.460826,0.887532,0.457877,0.431340,0.813816,0.560148
12,Adam Schenk,T60,0,2026,9.0,Cognizant Classic in The Palm Beaches,PGA National Resort,-0.742,-0.742,-2.967,...,0.947767,0.942713,0.871946,0.47936,0.460826,0.887532,0.945661,0.900590,0.902696,0.676666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,William Mouw,T6,-11,2026,9.0,Cognizant Classic in The Palm Beaches,PGA National Resort,2.008,2.008,8.033,...,0.447346,0.883319,0.863100,0.47936,0.949452,0.887532,0.457877,0.900590,0.902696,0.759991
1166,Wyndham Clark,T41,-3,2026,7.0,The Genesis Invitational,The Riviera Country Club,-0.597,-0.597,-2.386,...,0.954507,0.913227,0.948189,0.47936,0.460826,0.887532,0.945661,0.900590,0.948189,0.839587
1167,Xander Schauffele,T24,-2,2026,10.0,Arnold Palmer Invitational,Arnold Palmer's Bay Hill Club and Lodge,0.217,0.217,0.867,...,0.929655,0.978096,0.982308,0.47936,0.949452,0.961668,0.945661,0.992839,0.982308,0.934286
1178,Zac Blair,T50,-4,2026,2.0,Sony Open in Hawaii,Waialae Country Club,0.218,0.218,0.871,...,0.447346,0.945240,0.901432,0.47936,0.986099,0.985257,0.457877,0.954928,0.948189,0.804465
1182,Zach Johnson,T70,-10,2026,3.0,The American Express,PGA West,0.385,0.385,0.770,...,0.447346,0.889638,0.868997,0.47936,0.460826,0.415333,0.457877,0.431340,0.378686,0.642770

In [34]:
player_record = df_sorted.loc[df_sorted['player'] == 'Jake Knapp']
print(player_record)

         player pos  to_par  year  week_of_season                tournament  \
482  Jake Knapp   6     -13  2026             7.0  The Genesis Invitational

                       course    avg updated_avg total_sg_t  ...  \
482  The Riviera Country Club  1.904       1.904      7.614  ...

    top_20_percentage_last_year_percentile top_5_last_5_percentile  \
482                                 0.9141                   0.976

     top_10_last_5_percentile  top_20_last_5_percentile  \
482                    0.9992                    0.9996

     top_5_last_10_percentile  top_10_last_10_percentile  \
482                    0.9853                     0.9966

     top_20_last_10_percentile  weighted_composite  rank  \
482                     0.9903              0.9721     5

     composite_percentile_rank
482                     0.9819

[1 rows x 77 columns]

In [35]:
# ── Merge ──────────────────────────────────────────────────────────────────
merged_dataset = pd.merge(joined_df, filtered_df, on='player', how='left')
merged_dataset = merged_dataset[merged_dataset['tournaments_last_year'] > 3]

# ── Composite Score ────────────────────────────────────────────────────────
weights = {
    'SG_last_1_percentile'                   : weight_1,
    'SG_last_2_percentile'                   : weight_2,
    'SG_last_3_percentile'                   : weight_3,
    'SG_last_5_percentile'                   : weight_4,
    'SG_last_8_percentile'                   : weight_5,
    'SG_last_13_percentile'                  : weight_6,
    'SG_last_21_percentile'                  : weight_7,
    'SG_last_34_percentile'                  : weight_8,
    'SG_last_55_percentile'                  : weight_9,
    'dg_index_percentile'                    : weight_10,
    'owgr_rank_percentile'                   : weight_11,
    'last_3_avg_position_percentile'         : weight_12,
    'last_5_avg_position_percentile'         : weight_13,
    'last_10_avg_position_percentile'        : weight_14,
    'cut_percentage_last_year_percentile'    : weight_15,
    'top_5_percentage_last_year_percentile'  : weight_16,
    'top_10_percentage_last_year_percentile' : weight_17,
    'top_20_percentage_last_year_percentile' : weight_18,
    'top_5_last_5_percentile'               : weight_19,
    'top_10_last_5_percentile'              : weight_20,
    'top_20_last_5_percentile'              : weight_21,            
    'top_5_last_10_percentile'              : weight_22,
    'top_10_last_10_percentile'             : weight_23,
    'top_20_last_10_percentile'             : weight_24,
}
total_weight = sum(weights.values())
norm_weights = {col: w / total_weight for col, w in weights.items()}

def _composite(row):
    return sum(
        (row[col] if not pd.isna(row.get(col)) else 0) * nw
        for col, nw in norm_weights.items()
        if col in row.index
    )

merged_dataset['composite_score']           = merged_dataset.apply(_composite, axis=1)
merged_dataset['composite_percentile_rank'] = merged_dataset['composite_score'].rank(pct=True, ascending=True)
merged_dataset = merged_dataset.round(4)

print(f'✅ merged_dataset ready — {len(merged_dataset):,} players')

# ── golfer_profile() definition ────────────────────────────────────────────
def golfer_profile(
    player_name,
    tournament_name = None,
    last_n_finishes = 15,
    min_events      = 5,
):
    """
    Print a full scouting report for a given player.

    Parameters
    ----------
    player_name     : str   — player name (case-insensitive)
    tournament_name : str   — optional event name to pull historical finishes
    last_n_finishes : int   — how many recent results to display (default 10)
    min_events      : int   — minimum events required to show percentile rankings
    """
    name_lower = player_name.strip().lower()
    lb = df[df['player'].str.lower() == name_lower].copy()

    if lb.empty:
        print(f"\n❌  No leaderboard data found for '{player_name}'. Check spelling.\n")
        return

    canonical_name = lb['player'].iloc[0]
    lb = lb.sort_values(['year', 'week_of_season'])

    def _pos_numeric(pos, cut_penalty=80):
        if pd.isna(pos): return np.nan
        s = str(pos).upper().strip()
        if s in ('CUT', 'MC', 'WD', 'DQ'): return cut_penalty
        if s.startswith('T'):
            try: return int(s[1:])
            except ValueError: return np.nan
        try: return int(s)
        except ValueError: return np.nan

    lb['_pos_num'] = lb['pos'].apply(_pos_numeric)

    # ── Header ────────────────────────────────────────────────────────────
    print('\n' + '═' * 65)
    print(f'  🏌️  GOLFER PROFILE: {canonical_name.upper()}')
    print('═' * 65)

    # Want to add more stats here 
    print('datagolf ranking: ' + str(merged_dataset.loc[merged_dataset['player'] == canonical_name]['dg_rank'].iloc[0]))
    print(merged_dataset.loc[merged_dataset['player'] == canonical_name][['dg_rank']].to_string(index=False))


    # ── Section 1: Recent Finishes ────────────────────────────────────────
    print(f'\n📋  LAST {last_n_finishes} FINISHES')
    print('-' * 65)
    recent = lb.tail(last_n_finishes)[['year', 'tournament', 'course', 'pos', 'to_par']].copy()
    recent = recent.iloc[::-1].reset_index(drop=True)
    print(f"  {'#':<4} {'Year':<6} {'Pos':<6} {'To Par':<9} {'Tournament':<30} {'Course'}")
    print('  ' + '-' * 62)
    for i, row in recent.iterrows():
        print(f"  {i+1:<4} {int(row['year']):<6} {str(row['pos']):<6} "
              f"{str(row['to_par']) if not pd.isna(row['to_par']) else 'N/A':<9} "
              f"{str(row['tournament'])[:28] if not pd.isna(row['tournament']) else 'N/A':<30} "
              f"{str(row['course'])[:20] if not pd.isna(row['course']) else 'N/A'}")

    # ── Section 2: Rolling Average Finish ────────────────────────────────
    print('\n📊  AVERAGE FINISH POSITION')
    print('-' * 65)
    valid_pos = lb['_pos_num'].dropna().tolist()

    def _avg(lst, n):
        tail = lst[-n:]
        return round(np.mean(tail), 2) if tail else None
    
    def _top_count(lst, n, threshold):
        tail = lst[-n:]
        return sum(1 for p in tail if p <= threshold)

    last3_avg  = _avg(valid_pos,  3)
    last5_avg  = _avg(valid_pos,  5)
    last10_avg = _avg(valid_pos, 10)

    print(f"  Last  3 starts : {_avg(valid_pos,  3) or 'N/A'}")
    print(f"  Last  5 starts : {_avg(valid_pos,  5) or 'N/A'}")
    print(f"  Last 10 starts : {_avg(valid_pos, 10) or 'N/A'}")

    print(f"  Last  3 starts : avg finish = {last3_avg  or 'N/A'}")
    print()
    print(f"  {'Metric':<25} {'Last 5':>8} {'Last 10':>8}")
    print(f"  {'-'*42}")
    print(f"  {'Avg Finish':<25} {str(last5_avg)  if last5_avg  is not None else 'N/A':>8} {str(last10_avg) if last10_avg is not None else 'N/A':>8}")
    print(f"  {'Top 3 Finishes':<25} {_top_count(valid_pos,  5, 3):>8} {_top_count(valid_pos, 10, 3):>8}")
    print(f"  {'Top 5 Finishes':<25} {_top_count(valid_pos,  5, 5):>8} {_top_count(valid_pos, 10, 5):>8}")
    print(f"  {'Top 10 Finishes':<25} {_top_count(valid_pos,  5, 10):>8} {_top_count(valid_pos, 10, 10):>8}")


    print(f"\n  {'Year':<8} {'Events':<8} {'Cuts Made':<12} {'Cut %':<9} {'Avg Finish':<12} {'Top 5':<7} {'Top 10':<7} {'Top 20'}")
    print('  ' + '-' * 60)
    for year, grp in lb.groupby('year', sort=True):
        total_ev   = len(grp)
        cuts_miss  = grp['pos'].str.upper().isin(['CUT', 'MC']).sum()
        cuts_made  = total_ev - cuts_miss
        cut_pct    = round(cuts_made / total_ev * 100, 1) if total_ev else 0
        num_pos    = grp['_pos_num'].dropna()
        avg_fin    = round(num_pos.mean(), 1) if not num_pos.empty else 'N/A'
        print(f"  {int(year):<8} {total_ev:<8} {cuts_made:<12} {cut_pct:<9} {avg_fin:<12} "
              f"{int((num_pos <= 5).sum()):<7} {int((num_pos <= 10).sum()):<7} {int((num_pos <= 20).sum())}")

    # ── Section 3: Event History ──────────────────────────────────────────
    if tournament_name:
        print(f'\n🏆  HISTORY AT: {tournament_name.upper()}')
        print('-' * 65)
        t_hist = lb[lb['tournament'].str.lower().str.contains(tournament_name.strip().lower(), na=False)]
        t_hist = t_hist.sort_values('year', ascending=False)
        if t_hist.empty:
            print(f"  No results found for '{tournament_name}'.")
        else:
            print(f"  {'Year':<8} {'Pos':<8} {'To Par':<10} {'Course'}")
            print('  ' + '-' * 40)
            for _, row in t_hist.iterrows():
                print(f"  {int(row['year']):<8} {str(row['pos']):<8} "
                      f"{str(row['to_par']) if not pd.isna(row['to_par']) else 'N/A':<10} "
                      f"{str(row['course'])[:25] if not pd.isna(row['course']) else 'N/A'}")
            ev_num = t_hist['_pos_num'].dropna()
            if not ev_num.empty:
                print(f'\n  Avg finish at {tournament_name}: {round(ev_num.mean(), 1)}')

    # ── Section 4: SG & Finish Percentile Rankings ────────────────────────
    print(f'\n📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with {min_events}+ events)')
    print('-' * 65)

    player_row = merged_dataset[merged_dataset['player'].str.lower() == name_lower]

    if player_row.empty:
        print(f"  ⚠️  '{canonical_name}' not found in merged_dataset (may have < {min_events} events).")
    else:
        row = player_row.iloc[0]

        def _bar(pct, width=20):
            if pd.isna(pct): return '[  N/A  ]'
            filled = int(round(pct * width))
            return '[' + '█' * filled + '░' * (width - filled) + f']  {pct*100:.1f}th'

        sg_cols = {
            'SG Last 1 Event'   : 'SG_last_1_percentile',
            'SG Last 3 Events'  : 'SG_last_3_percentile',
            'SG Last 5 Events'  : 'SG_last_5_percentile',
            'SG Last 8 Events'  : 'SG_last_8_percentile',
            'SG Last 13 Events' : 'SG_last_13_percentile',
            'SG Last 21 Events' : 'SG_last_21_percentile',
            'DG Index'          : 'dg_index_percentile',
            'OWGR Rank'         : 'owgr_rank_percentile',
        }
        finish_cols = {
            'Avg Finish Last 3'       : 'last_3_avg_position_percentile',
            'Avg Finish Last 5'       : 'last_5_avg_position_percentile',
            'Avg Finish Last 10'      : 'last_10_avg_position_percentile',
            'Cut % Last Year'         : 'cut_percentage_last_year_percentile',
            'Top 5% Last Year'        : 'top_5_percentage_last_year_percentile',
            'Top 10% Last Year'       : 'top_10_percentage_last_year_percentile',
            'Top 20% Last Year'       : 'top_20_percentage_last_year_percentile',
            'Top 5 Finishes (Last 5)' : 'top_5_last_5_percentile',
            'Top 10 Finishes (Last 5)': 'top_10_last_5_percentile',
            'Top 20 Finishes (Last 5)': 'top_20_last_5_percentile',
            'Top 5 Finishes (Last 10)': 'top_5_last_10_percentile',
            'Top 10 Finishes(Last 10)': 'top_10_last_10_percentile',
            'Top 20 Finishes(Last 10)': 'top_20_last_10_percentile',
        }

        print(f"\n  {'Metric':<28} Percentile Bar")
        print('  ' + '-' * 55)
        print('  — Strokes Gained —')
        for label, col in sg_cols.items():
            print(f"  {label:<28} {_bar(row.get(col, np.nan))}")
        print('\n  — Finish Position —')
        for label, col in finish_cols.items():
            print(f"  {label:<28} {_bar(row.get(col, np.nan))}")

        # ── Section 5: Composite Summary ──────────────────────────────────
        print('\n🎯  COMPOSITE SCORE SUMMARY')
        print('-' * 65)
        comp_val = row.get('composite_score', np.nan)
        if not pd.isna(comp_val):
            comp_pct = (merged_dataset['composite_score'] <= comp_val).mean()
            print(f'  Composite Score  : {comp_val:.4f}')
            print(f'  Composite Pctile : {comp_pct*100:.1f}th percentile')
        else:
            print('  Composite Score  : N/A')

        tier_val = row.get('tier', row.get('Tier', 'N/A'))
        print(f'  Tier             : {tier_val}')

        all_valid = lb['_pos_num'].dropna()
        total_ev  = len(lb)
        cuts_miss = lb['pos'].str.upper().isin(['CUT','MC']).sum()
        print(f'\n  Career Events    : {total_ev}')
        print(f'  Career Cuts Miss : {cuts_miss}  ({round(cuts_miss/total_ev*100,1) if total_ev else 0}%)')
        print(f'  Career Avg Finish: {round(all_valid.mean(), 1) if not all_valid.empty else "N/A"}')

    print('\n' + '═' * 65 + '\n')

print('✅ golfer_profile() is ready to use')

✅ merged_dataset ready — 239 players
✅ golfer_profile() is ready to use

In [36]:
# ── EDIT THESE ────────────────────────────────────────────────────────────
PLAYER_NAME     = 'Kurt Kitayama'
TOURNAMENT_NAME = 'Arnold Palmer Invitational'           # e.g. 'The Masters'  or  None
LAST_N_FINISHES = 15
# ──────────────────────────────────────────────────────────────────────────

golfer_profile(
    player_name     = PLAYER_NAME,
    tournament_name = TOURNAMENT_NAME,
    last_n_finishes = LAST_N_FINISHES,
)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: KURT KITAYAMA
═════════════════════════════════════════════════════════════════
datagolf ranking: 28.0
 dg_rank
    28.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T18    -3        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T2     -17       The Genesis Invitational       The Riviera Country
  3    2026   T24    -8        WM Phoenix Open                TPC Scottsdale
  4    2026   T48    -9        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   CUT    -10       The American Express           PGA West
  6    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  7    2025   T15    -13       Black Desert Championship      Black Desert Resort
  8    2025   T48    -2        Baycurrent Classic             Yokohama Country Clu
  9    2025   T19    0         BMW Championship               Caves Valley Golf Cl
  10   2025   T9     -9        FedEx St. Jude Championship    TPC Southwind
  11   2025   T31    -7        Wyndham Championship           Sedgefield Country C
  12   2025   1      -23       3M Open                        TPC Twin Cities
  13   2025   T5     -16       John Deere Classic             TPC Deere Run
  14   2025   T51    -10       Rocket Mortgage Classic        Detroit Golf Club
  15   2025   CUT    -1        RBC Canadian Open              TPC Toronto at Ospre

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 14.67
  Last  5 starts : 34.4
  Last 10 starts : 30.3
  Last  3 starts : avg finish = 14.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    34.4     30.3
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     16       8            50.0      48.1         3       3       6
  2023     18       9            50.0      56.3         2       2       3
  2024     19       15           78.9      37.1         1       3       4
  2025     22       15           68.2      44.6         3       4       6
  2026     6        5            83.3      35.3         1       1       2

🏆  HISTORY AT: ARNOLD PALMER INVITATIONAL
-----------------------------------------------------------------
  Year     Pos      To Par     Course
  ----------------------------------------
  2026     T18      -3         Arnold Palmer's Bay Hill
  2024     CUT      7          NaN
  2023     1        -9         NaN

  Avg finish at Arnold Palmer Invitational: 33.0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  92.6th
  SG Last 3 Events             [████████████████████]  99.2th
  SG Last 5 Events             [███████████████████░]  96.1th
  SG Last 8 Events             [███████████████████░]  96.3th
  SG Last 13 Events            [████████████████████]  99.2th
  SG Last 21 Events            [████████████████████]  97.6th
  DG Index                     [███████████████████░]  93.4th
  OWGR Rank                    [███████████████████░]  92.7th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.3th
  Avg Finish Last 5            [███████████████████░]  95.2th
  Avg Finish Last 10           [███████████████████░]  97.0th
  Cut % Last Year              [███████████████░░░░░]  74.7th
  Top 5% Last Year             [████████████████████]  97.7th
  Top 10% Last Year            [███████████████████░]  96.3th
  Top 20% Last Year            [███████████████████░]  93.8th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [████████████████████]  98.2th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9507
  Composite Pctile : 95.0th percentile
  Tier             : N/A

  Career Events    : 81
  Career Cuts Miss : 29  (35.8%)
  Career Avg Finish: 45.4

═════════════════════════════════════════════════════════════════

In [37]:
# Build players list from a specific tier
tier = 1
players = tier_df[tier_df['Tier'] == tier]['player'].tolist()

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: RORY MCILROY
═════════════════════════════════════════════════════════════════
datagolf ranking: 3.0
 dg_rank
     3.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   W/D    -4        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T2     -17       The Genesis Invitational       The Riviera Country
  3    2026   T14    -17       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2025   T23    -6        TOUR Championship              East Lake Golf Club
  5    2025   T12    -3        BMW Championship               Caves Valley Golf Cl
  6    2025   T7     -10       The Open Championship          Royal Portrush Golf
  7    2025   T2     -13       Genesis Scottish Open          The Renaissance Club
  8    2025   T6     -12       Travelers Championship         TPC River Highlands
  9    2025   T19    7         U.S. Open                      Oakmont Country Club
  10   2025   CUT    9         RBC Canadian Open              TPC Toronto at Ospre
  11   2025   T47    3         PGA Championship               Quail Hollow Club
  12   2025   T7     -10       Truist Championship            The Philadelphia Cri
  13   2025   1      -11       Masters Tournament             Augusta National Gol
  14   2025   T5     -15       Texas Childrens Houston Open   Memorial Park Golf C
  15   2025   1      -12       THE PLAYERS Championship       TPC Sawgrass

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 13.0
  Last  5 starts : 11.6
  Last 10 starts : 21.2
  Last  3 starts : avg finish = 13.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    11.6     21.2
  Top 3 Finishes                   1        2
  Top 5 Finishes                   1        2
  Top 10 Finishes                  2        4

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     14       12           85.7      20.2         5       8       11
  2023     15       13           86.7      20.9         6       10      10
  2024     16       16           100.0     16.8         5       6       10
  2025     15       14           93.3      16.2         5       8       12
  2026     3        3            100.0     8.0          1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [████████████████████]  97.9th
  SG Last 5 Events             [███████████████████░]  97.2th
  SG Last 8 Events             [████████████████████]  98.7th
  SG Last 13 Events            [████████████████████]  98.3th
  SG Last 21 Events            [████████████████████]  99.3th
  DG Index                     [████████████████████]  99.5th
  OWGR Rank                    [████████████████████]  99.8th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.5th
  Avg Finish Last 5            [████████████████████]  99.7th
  Avg Finish Last 10           [████████████████████]  99.1th
  Cut % Last Year              [██████████████████░░]  88.2th
  Top 5% Last Year             [████████████████████]  99.5th
  Top 10% Last Year            [████████████████████]  99.8th
  Top 20% Last Year            [████████████████████]  99.4th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  98.6th
  Top 20 Finishes (Last 5)     [████████████████████]  99.5th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  99.3th
  Top 20 Finishes(Last 10)     [████████████████████]  99.5th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9574
  Composite Pctile : 95.8th percentile
  Tier             : N/A

  Career Events    : 63
  Career Cuts Miss : 5  (7.9%)
  Career Avg Finish: 18.1

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: SCOTTIE SCHEFFLER
═════════════════════════════════════════════════════════════════
datagolf ranking: 1.0
 dg_rank
     1.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T24    -2        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T12    -11       The Genesis Invitational       The Riviera Country
  3    2026   T3     -15       WM Phoenix Open                TPC Scottsdale
  4    2026   T4     -20       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   1      -27       The American Express           PGA West
  6    2025   1      -19       Procore Championship           Silverado Resort
  7    2025   T4     -14       TOUR Championship              East Lake Golf Club
  8    2025   1      -15       BMW Championship               Caves Valley Golf Cl
  9    2025   T3     -15       FedEx St. Jude Championship    TPC Southwind
  10   2025   1      -17       The Open Championship          Royal Portrush Golf
  11   2025   T8     -9        Genesis Scottish Open          The Renaissance Club
  12   2025   T6     -12       Travelers Championship         TPC River Highlands
  13   2025   T7     4         U.S. Open                      Oakmont Country Club
  14   2025   1      -10       The Memorial Tournament        Muirfield Village Go
  15   2025   T4     -8        Charles Schwab Challenge       Colonial Country Clu

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 13.0
  Last  5 starts : 8.8
  Last 10 starts : 5.4
  Last  3 starts : avg finish = 13.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                     8.8      5.4
  Top 3 Finishes                   2        6
  Top 5 Finishes                   3        8
  Top 10 Finishes                  3        8

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     19       16           84.2      21.6         9       10      14
  2023     19       19           100.0     6.7          11      15      18
  2024     17       17           100.0     7.8          12      14      15
  2025     20       20           100.0     6.0          12      17      19
  2026     5        5            100.0     8.8          3       3       4

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  89.9th
  SG Last 3 Events             [████████████████████]  99.2th
  SG Last 5 Events             [████████████████████]  99.8th
  SG Last 8 Events             [████████████████████]  99.9th
  SG Last 13 Events            [████████████████████]  99.8th
  SG Last 21 Events            [████████████████████]  99.9th
  DG Index                     [████████████████████]  100.0th
  OWGR Rank                    [████████████████████]  100.0th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.5th
  Avg Finish Last 5            [████████████████████]  99.8th
  Avg Finish Last 10           [████████████████████]  99.9th
  Cut % Last Year              [███████████████████░]  94.4th
  Top 5% Last Year             [████████████████████]  99.9th
  Top 10% Last Year            [████████████████████]  99.9th
  Top 20% Last Year            [████████████████████]  99.5th
  Top 5 Finishes (Last 5)      [████████████████████]  99.9th
  Top 10 Finishes (Last 5)     [████████████████████]  99.6th
  Top 20 Finishes (Last 5)     [████████████████████]  99.5th
  Top 5 Finishes (Last 10)     [████████████████████]  100.0th
  Top 10 Finishes(Last 10)     [████████████████████]  100.0th
  Top 20 Finishes(Last 10)     [████████████████████]  100.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9900
  Composite Pctile : 100.0th percentile
  Tier             : N/A

  Career Events    : 80
  Career Cuts Miss : 3  (3.8%)
  Career Avg Finish: 10.4

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: TOMMY FLEETWOOD
═════════════════════════════════════════════════════════════════
datagolf ranking: 5.0
 dg_rank
     5.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   49     6         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T7     -12       The Genesis Invitational       The Riviera Country
  3    2026   T4     -20       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2025   1      -18       TOUR Championship              East Lake Golf Club
  5    2025   T4     -10       BMW Championship               Caves Valley Golf Cl
  6    2025   T3     -15       FedEx St. Jude Championship    TPC Southwind
  7    2025   T16    -7        The Open Championship          Royal Portrush Golf
  8    2025   T34    -4        Genesis Scottish Open          The Renaissance Club
  9    2025   T2     -14       Travelers Championship         TPC River Highlands
  10   2025   CUT    9         U.S. Open                      Oakmont Country Club
  11   2025   T16    1         The Memorial Tournament        Muirfield Village Go
  12   2025   T4     -8        Charles Schwab Challenge       Colonial Country Clu
  13   2025   T41    2         PGA Championship               Quail Hollow Club
  14   2025   T4     -12       Truist Championship            The Philadelphia Cri
  15   2025   7      -13       RBC Heritage                   Harbour Town Golf Li

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 20.0
  Last  5 starts : 13.0
  Last 10 starts : 20.0
  Last  3 starts : avg finish = 20.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    13.0     20.0
  Top 3 Finishes                   1        3
  Top 5 Finishes                   3        5
  Top 10 Finishes                  4        6

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     13       11           84.6      34.2         2       3       6
  2023     17       14           82.4      27.6         5       7       10
  2024     17       16           94.1      24.9         2       4       9
  2025     19       18           94.7      19.1         7       8       13
  2026     3        3            100.0     20.0         1       2       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [█████████████████░░░]  83.9th
  SG Last 3 Events             [███████████████████░]  97.4th
  SG Last 5 Events             [████████████████████]  99.6th
  SG Last 8 Events             [████████████████████]  99.6th
  SG Last 13 Events            [████████████████████]  99.5th
  SG Last 21 Events            [████████████████████]  99.6th
  DG Index                     [████████████████████]  99.0th
  OWGR Rank                    [████████████████████]  99.5th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  98.4th
  Avg Finish Last 5            [████████████████████]  99.5th
  Avg Finish Last 10           [████████████████████]  99.3th
  Cut % Last Year              [██████████████████░░]  88.4th
  Top 5% Last Year             [████████████████████]  99.7th
  Top 10% Last Year            [████████████████████]  99.4th
  Top 20% Last Year            [████████████████████]  99.0th
  Top 5 Finishes (Last 5)      [████████████████████]  99.9th
  Top 10 Finishes (Last 5)     [████████████████████]  99.9th
  Top 20 Finishes (Last 5)     [████████████████████]  99.5th
  Top 5 Finishes (Last 10)     [████████████████████]  99.9th
  Top 10 Finishes(Last 10)     [████████████████████]  99.8th
  Top 20 Finishes(Last 10)     [████████████████████]  99.5th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9791
  Composite Pctile : 99.6th percentile
  Tier             : N/A

  Career Events    : 69
  Career Cuts Miss : 7  (10.1%)
  Career Avg Finish: 25.5

═════════════════════════════════════════════════════════════════

In [56]:
# ── Tier 1 ────────────────────────────────────────────────────────
players = [
    'Michael Thorbjornsen',
    'Adam Scott',
    'Daniel Berger',
    'Ryo Hisatsune'
]
# ──────────────────────────────────────────────────────────────────────────

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: MICHAEL THORBJORNSEN
═════════════════════════════════════════════════════════════════
datagolf ranking: 74.0
 dg_rank
    74.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T33    -1        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    1         Cognizant Classic in The Pal   PGA National Resort
  3    2026   T3     -15       WM Phoenix Open                TPC Scottsdale
  4    2026   T78    9         ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T18    -11       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   CUT    -7        The American Express           PGA West
  7    2025   T7     -18       The RSM Classic                Sea Island Golf Club
  8    2025   T31    -16       World Wide Technology Champi   El Cardonal at Diama
  9    2025   T37    -9        Black Desert Championship      Black Desert Resort
  10   2025   3      -16       Baycurrent Classic             Yokohama Country Clu
  11   2025   T29    -11       Sanderson Farms Championship   The Country Club of
  12   2025   T13    -10       Procore Championship           Silverado Resort
  13   2025   T38    -5        Wyndham Championship           Sedgefield Country C
  14   2025   CUT    3         3M Open                        TPC Twin Cities
  15   2025   T21    -13       John Deere Classic             TPC Deere Run

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 38.67
  Last  5 starts : 42.4
  Last 10 starts : 37.0
  Last  3 starts : avg finish = 38.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    42.4     37.0
  Top 3 Finishes                   1        2
  Top 5 Finishes                   1        2
  Top 10 Finishes                  1        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2024     9        6            66.7      43.4         1       3       3
  2025     22       16           72.7      44.9         2       3       4
  2026     6        4            66.7      48.7         1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  88.3th
  SG Last 3 Events             [███████████████████░]  94.7th
  SG Last 5 Events             [██████████████████░░]  89.1th
  SG Last 8 Events             [█████████████████░░░]  87.1th
  SG Last 13 Events            [██████████████████░░]  92.1th
  SG Last 21 Events            [███████████████████░]  93.2th
  DG Index                     [█████████████████░░░]  83.0th
  OWGR Rank                    [█████████████████░░░]  86.1th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  93.0th
  Avg Finish Last 5            [███████████████████░]  92.5th
  Avg Finish Last 10           [███████████████████░]  94.9th
  Cut % Last Year              [████████████████░░░░]  78.0th
  Top 5% Last Year             [███████████████████░]  95.9th
  Top 10% Last Year            [███████████████████░]  95.0th
  Top 20% Last Year            [██████████████████░░]  89.8th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [███████████████████░]  96.9th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9150
  Composite Pctile : 88.3th percentile
  Tier             : N/A

  Career Events    : 37
  Career Cuts Miss : 11  (29.7%)
  Career Avg Finish: 45.2

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ADAM SCOTT
═════════════════════════════════════════════════════════════════
datagolf ranking: 29.0
 dg_rank
    29.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T11    -6        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   4      -16       The Genesis Invitational       The Riviera Country
  3    2026   T30    -8        Farmers Insurance Open         Torrey Pines Golf Co
  4    2026   T24    -18       The American Express           PGA West
  5    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  6    2025   T27    -7        Baycurrent Classic             Yokohama Country Clu
  7    2025   T55    -3        Wyndham Championship           Sedgefield Country C
  8    2025   T53    -10       3M Open                        TPC Twin Cities
  9    2025   CUT    9         The Open Championship          Royal Portrush Golf
  10   2025   T17    -6        Genesis Scottish Open          The Renaissance Club
  11   2025   T30    -4        Travelers Championship         TPC River Highlands
  12   2025   T12    6         U.S. Open                      Oakmont Country Club
  13   2025   T31    5         The Memorial Tournament        Muirfield Village Go
  14   2025   T19    -2        PGA Championship               Quail Hollow Club
  15   2025   T34    -4        Truist Championship            The Philadelphia Cri

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 15.0
  Last  5 starts : 21.8
  Last 10 starts : 34.1
  Last  3 starts : avg finish = 15.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    21.8     34.1
  Top 3 Finishes                   0        0
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     15       13           86.7      39.4         3       3       4
  2023     17       15           88.2      33.5         2       5       6
  2024     17       15           88.2      28.1         3       4       8
  2025     18       15           83.3      40.8         0       0       4
  2026     5        5            100.0     21.8         1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  96.5th
  SG Last 3 Events             [████████████████████]  99.3th
  SG Last 5 Events             [████████████████████]  99.2th
  SG Last 8 Events             [████████████████████]  97.7th
  SG Last 13 Events            [████████████████████]  98.2th
  SG Last 21 Events            [███████████████████░]  96.6th
  DG Index                     [███████████████████░]  93.2th
  OWGR Rank                    [██████████████████░░]  87.8th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.2th
  Avg Finish Last 5            [████████████████████]  98.7th
  Avg Finish Last 10           [███████████████████░]  95.7th
  Cut % Last Year              [█████████████████░░░]  84.6th
  Top 5% Last Year             [█████████░░░░░░░░░░░]  44.7th
  Top 10% Last Year            [█████████░░░░░░░░░░░]  43.1th
  Top 20% Last Year            [██████████████████░░]  91.0th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9128
  Composite Pctile : 87.9th percentile
  Tier             : N/A

  Career Events    : 72
  Career Cuts Miss : 9  (12.5%)
  Career Avg Finish: 34.5

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: DANIEL BERGER
═════════════════════════════════════════════════════════════════
datagolf ranking: 49.0
 dg_rank
    49.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   2      -15       Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T32    -6        Cognizant Classic in The Pal   PGA National Resort
  3    2026   CUT    2         The Genesis Invitational       The Riviera Country
  4    2026   T16    -10       WM Phoenix Open                TPC Scottsdale
  5    2026   T75    2         ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  6    2026   T56    -14       The American Express           PGA West
  7    2026   T6     -11       Sony Open in Hawaii            Waialae Country Club
  8    2025   T51    -11       The RSM Classic                Sea Island Golf Club
  9    2025   T30    -4        The Open Championship          Royal Portrush Golf
  10   2025   T55    0         Genesis Scottish Open          The Renaissance Club
  11   2025   T42    -1        Travelers Championship         TPC River Highlands
  12   2025   T46    13        U.S. Open                      Oakmont Country Club
  13   2025   CUT    9         The Memorial Tournament        Muirfield Village Go
  14   2025   CUT    2         Charles Schwab Challenge       Colonial Country Clu
  15   2025   T33    0         PGA Championship               Quail Hollow Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 38.0
  Last  5 starts : 41.0
  Last 10 starts : 40.3
  Last  3 starts : avg finish = 38.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    41.0     40.3
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     11       8            72.7      34.6         3       3       5
  2024     20       12           60.0      50.1         1       2       4
  2025     20       16           80.0      36.8         2       2       6
  2026     7        6            85.7      38.1         1       2       3

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  100.0th
  SG Last 3 Events             [███████████████████░]  96.8th
  SG Last 5 Events             [███████████████████░]  95.0th
  SG Last 8 Events             [███████████████████░]  95.6th
  SG Last 13 Events            [███████████████████░]  93.3th
  SG Last 21 Events            [███████████████████░]  95.8th
  DG Index                     [██████████████████░░]  88.6th
  OWGR Rank                    [██████████████████░░]  91.9th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  93.3th
  Avg Finish Last 5            [███████████████████░]  93.4th
  Avg Finish Last 10           [███████████████████░]  93.1th
  Cut % Last Year              [█████████████████░░░]  82.7th
  Top 5% Last Year             [███████████████████░]  96.2th
  Top 10% Last Year            [██████████████████░░]  92.5th
  Top 20% Last Year            [███████████████████░]  94.4th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9423
  Composite Pctile : 93.3th percentile
  Tier             : N/A

  Career Events    : 58
  Career Cuts Miss : 16  (27.6%)
  Career Avg Finish: 41.2

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: RYO HISATSUNE
═════════════════════════════════════════════════════════════════
datagolf ranking: 87.0
 dg_rank
    87.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T33    -1        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T45    -1        The Genesis Invitational       The Riviera Country
  3    2026   T10    -12       WM Phoenix Open                TPC Scottsdale
  4    2026   T8     -18       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T2     -16       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T44    -15       The American Express           PGA West
  7    2026   CUT    0         Sony Open in Hawaii            Waialae Country Club
  8    2025   CUT    -2        The RSM Classic                Sea Island Golf Club
  9    2025   T52    2         Butterfield Bermuda Champion   Port Royal Golf Cour
  10   2025   T40    -15       World Wide Technology Champi   El Cardonal at Diama
  11   2025   CUT    2         Black Desert Championship      Black Desert Resort
  12   2025   T72    7         Baycurrent Classic             Yokohama Country Clu
  13   2025   T48    -8        Sanderson Farms Championship   The Country Club of
  14   2025   T13    -10       Procore Championship           Silverado Resort
  15   2025   CUT    7         Wyndham Championship           Sedgefield Country C

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 29.33
  Last  5 starts : 19.6
  Last 10 starts : 39.4
  Last  3 starts : avg finish = 29.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    19.6     39.4
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  3        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     1        1            100.0     12.0         0       0       1
  2023     1        1            100.0     6.0          0       1       1
  2024     24       16           66.7      47.6         1       1       5
  2025     27       17           63.0      52.9         2       4       6
  2026     7        6            85.7      31.7         1       3       3

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  88.3th
  SG Last 3 Events             [███████████████████░]  95.0th
  SG Last 5 Events             [████████████████████]  99.4th
  SG Last 8 Events             [███████████████████░]  97.0th
  SG Last 13 Events            [██████████████████░░]  90.8th
  SG Last 21 Events            [██████████████████░░]  90.9th
  DG Index                     [████████████████░░░░]  79.8th
  OWGR Rank                    [█████████████████░░░]  84.6th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  96.0th
  Avg Finish Last 5            [████████████████████]  99.0th
  Avg Finish Last 10           [███████████████████░]  93.7th
  Cut % Last Year              [██████████████░░░░░░]  70.3th
  Top 5% Last Year             [███████████████████░]  93.4th
  Top 10% Last Year            [███████████████████░]  95.2th
  Top 20% Last Year            [██████████████████░░]  91.0th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  99.6th
  Top 20 Finishes (Last 5)     [████████████████████]  98.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9225
  Composite Pctile : 90.4th percentile
  Tier             : N/A

  Career Events    : 60
  Career Cuts Miss : 19  (31.7%)
  Career Avg Finish: 46.8

═════════════════════════════════════════════════════════════════

In [39]:
# ── Tier 2 ────────────────────────────────────────────────────────
tier = 2
players = tier_df[tier_df['Tier'] == tier]['player'].tolist()

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: CHRIS GOTTERUP
═════════════════════════════════════════════════════════════════
datagolf ranking: 32.0
 dg_rank
    32.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T18    -3        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    3         The Genesis Invitational       The Riviera Country
  3    2026   1      -16       WM Phoenix Open                TPC Scottsdale
  4    2026   T37    -11       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T18    -11       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   1      -16       Sony Open in Hawaii            Waialae Country Club
  7    2025   T40    -4        Baycurrent Classic             Yokohama Country Clu
  8    2025   T10    -12       TOUR Championship              East Lake Golf Club
  9    2025   T33    6         BMW Championship               Caves Valley Golf Cl
  10   2025   T54    1         FedEx St. Jude Championship    TPC Southwind
  11   2025   T10    -18       3M Open                        TPC Twin Cities
  12   2025   3      -12       The Open Championship          Royal Portrush Golf
  13   2025   1      -15       Genesis Scottish Open          The Renaissance Club
  14   2025   T21    -13       John Deere Classic             TPC Deere Run
  15   2025   T26    -15       Rocket Mortgage Classic        Detroit Golf Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 33.0
  Last  5 starts : 30.8
  Last 10 starts : 29.2
  Last  3 starts : avg finish = 33.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    30.8     29.2
  Top 3 Finishes                   1        2
  Top 5 Finishes                   1        2
  Top 10 Finishes                  1        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     9        8            88.9      42.4         1       1       1
  2023     2        0            0.0       80.0         0       0       0
  2024     21       11           52.4      65.4         0       0       0
  2025     24       15           62.5      44.7         2       4       6
  2026     6        5            83.3      25.8         2       2       4

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  92.6th
  SG Last 3 Events             [███████████████████░]  96.0th
  SG Last 5 Events             [████████████████████]  97.7th
  SG Last 8 Events             [████████████████████]  98.3th
  SG Last 13 Events            [████████████████████]  98.4th
  SG Last 21 Events            [████████████████████]  98.5th
  DG Index                     [██████████████████░░]  92.4th
  OWGR Rank                    [████████████████████]  98.5th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  94.7th
  Avg Finish Last 5            [███████████████████░]  96.4th
  Avg Finish Last 10           [███████████████████░]  97.5th
  Cut % Last Year              [██████████████░░░░░░]  70.0th
  Top 5% Last Year             [███████████████████░]  94.3th
  Top 10% Last Year            [███████████████████░]  95.8th
  Top 20% Last Year            [███████████████████░]  92.9th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [████████████████████]  98.5th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  98.2th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9432
  Composite Pctile : 94.1th percentile
  Tier             : N/A

  Career Events    : 62
  Career Cuts Miss : 23  (37.1%)
  Career Avg Finish: 50.4

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: COLLIN MORIKAWA
═════════════════════════════════════════════════════════════════
datagolf ranking: 9.0
 dg_rank
     9.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   5      -11       Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T7     -12       The Genesis Invitational       The Riviera Country
  3    2026   T54    -3        WM Phoenix Open                TPC Scottsdale
  4    2026   1      -22       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   CUT    0         Sony Open in Hawaii            Waialae Country Club
  6    2025   T14    -10       Baycurrent Classic             Yokohama Country Clu
  7    2025   T43    -5        Procore Championship           Silverado Resort
  8    2025   T19    -8        TOUR Championship              East Lake Golf Club
  9    2025   T33    6         BMW Championship               Caves Valley Golf Cl
  10   2025   T22    -6        FedEx St. Jude Championship    TPC Southwind
  11   2025   CUT    7         The Open Championship          Royal Portrush Golf
  12   2025   CUT    4         Genesis Scottish Open          The Renaissance Club
  13   2025   T8     -19       Rocket Mortgage Classic        Detroit Golf Club
  14   2025   T42    -1        Travelers Championship         TPC River Highlands
  15   2025   T23    8         U.S. Open                      Oakmont Country Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 22.0
  Last  5 starts : 29.4
  Last 10 starts : 27.8
  Last  3 starts : avg finish = 22.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    29.4     27.8
  Top 3 Finishes                   1        1
  Top 5 Finishes                   2        2
  Top 10 Finishes                  3        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     16       13           81.2      36.0         5       5       6
  2023     19       15           78.9      27.8         4       7       10
  2024     19       17           89.5      25.2         7       8       12
  2025     20       18           90.0      28.4         2       4       11
  2026     5        4            80.0      29.4         2       3       3

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  99.5th
  SG Last 3 Events             [████████████████████]  98.8th
  SG Last 5 Events             [████████████████████]  98.7th
  SG Last 8 Events             [███████████████████░]  97.1th
  SG Last 13 Events            [███████████████████░]  95.7th
  SG Last 21 Events            [███████████████████░]  96.9th
  DG Index                     [████████████████████]  98.0th
  OWGR Rank                    [████████████████████]  99.2th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  97.9th
  Avg Finish Last 5            [███████████████████░]  96.8th
  Avg Finish Last 10           [████████████████████]  97.9th
  Cut % Last Year              [█████████████████░░░]  87.1th
  Top 5% Last Year             [███████████████████░]  96.2th
  Top 10% Last Year            [███████████████████░]  96.8th
  Top 20% Last Year            [████████████████████]  98.7th
  Top 5 Finishes (Last 5)      [████████████████████]  99.6th
  Top 10 Finishes (Last 5)     [████████████████████]  99.6th
  Top 20 Finishes (Last 5)     [████████████████████]  98.5th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  98.2th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9776
  Composite Pctile : 98.7th percentile
  Tier             : N/A

  Career Events    : 79
  Career Cuts Miss : 12  (15.2%)
  Career Avg Finish: 29.1

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: HIDEKI MATSUYAMA
═════════════════════════════════════════════════════════════════
datagolf ranking: 10.0
 dg_rank
    10.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T41    1         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T28    -6        The Genesis Invitational       The Riviera Country
  3    2026   2      -16       WM Phoenix Open                TPC Scottsdale
  4    2026   T8     -18       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T11    -12       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T13    -9        Sony Open in Hawaii            Waialae Country Club
  7    2025   T20    -8        Baycurrent Classic             Yokohama Country Clu
  8    2025   29     3         TOUR Championship              East Lake Golf Club
  9    2025   T26    2         BMW Championship               Caves Valley Golf Cl
  10   2025   T17    -7        FedEx St. Jude Championship    TPC Southwind
  11   2025   T19    -10       Wyndham Championship           Sedgefield Country C
  12   2025   T16    -7        The Open Championship          Royal Portrush Golf
  13   2025   T13    -18       Rocket Mortgage Classic        Detroit Golf Club
  14   2025   T30    -4        Travelers Championship         TPC River Highlands
  15   2025   T42    12        U.S. Open                      Oakmont Country Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 23.67
  Last  5 starts : 18.0
  Last 10 starts : 19.5
  Last  3 starts : avg finish = 23.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    18.0     19.5
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  2        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     18       17           94.4      28.9         3       4       8
  2023     21       17           81.0      35.4         1       2       7
  2024     18       17           94.4      23.2         2       7       9
  2025     23       20           87.0      31.3         1       1       9
  2026     6        6            100.0     17.2         1       2       4

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [█████████████████░░░]  86.3th
  SG Last 3 Events             [████████████████████]  98.0th
  SG Last 5 Events             [████████████████████]  98.9th
  SG Last 8 Events             [███████████████████░]  96.0th
  SG Last 13 Events            [███████████████████░]  97.4th
  SG Last 21 Events            [███████████████████░]  95.6th
  DG Index                     [████████████████████]  97.7th
  OWGR Rank                    [███████████████████░]  97.2th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  97.6th
  Avg Finish Last 5            [████████████████████]  99.2th
  Avg Finish Last 10           [████████████████████]  99.5th
  Cut % Last Year              [█████████████████░░░]  85.8th
  Top 5% Last Year             [██████████████████░░]  90.8th
  Top 10% Last Year            [█████████████████░░░]  87.0th
  Top 20% Last Year            [███████████████████░]  96.9th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  98.6th
  Top 20 Finishes (Last 5)     [████████████████████]  98.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [████████████████████]  99.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9554
  Composite Pctile : 95.4th percentile
  Tier             : N/A

  Career Events    : 86
  Career Cuts Miss : 9  (10.5%)
  Career Avg Finish: 29.1

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: LUDVIG ÅBERG
═════════════════════════════════════════════════════════════════
datagolf ranking: nan
 dg_rank
     NaN

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T3     -12       Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T20    -9        The Genesis Invitational       The Riviera Country
  3    2026   T37    -11       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   CUT    6         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   W/D    -9        The American Express           PGA West
  6    2025   T21    -7        TOUR Championship              East Lake Golf Club
  7    2025   T7     -7        BMW Championship               Caves Valley Golf Cl
  8    2025   T9     -9        FedEx St. Jude Championship    TPC Southwind
  9    2025   T23    -6        The Open Championship          Royal Portrush Golf
  10   2025   T8     -9        Genesis Scottish Open          The Renaissance Club
  11   2025   T36    -2        Travelers Championship         TPC River Highlands
  12   2025   CUT    8         U.S. Open                      Oakmont Country Club
  13   2025   T13    -13       RBC Canadian Open              TPC Toronto at Ospre
  14   2025   T16    1         The Memorial Tournament        Muirfield Village Go
  15   2025   CUT    3         PGA Championship               Quail Hollow Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 20.0
  Last  5 starts : 32.2
  Last 10 starts : 24.4
  Last  3 starts : avg finish = 20.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    32.2     24.4
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        4

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2023     10       9            90.0      26.4         3       4       5
  2024     18       17           94.4      20.4         4       7       12
  2025     20       16           80.0      33.9         2       6       8
  2026     5        4            80.0      35.0         1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  99.7th
  SG Last 3 Events             [████████████████████]  98.7th
  SG Last 5 Events             [███████████████████░]  93.2th
  SG Last 8 Events             [███████████████████░]  96.8th
  SG Last 13 Events            [███████████████████░]  96.7th
  SG Last 21 Events            [██████████████████░░]  91.8th
  DG Index                     [  N/A  ]
  OWGR Rank                    [  N/A  ]

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  98.4th
  Avg Finish Last 5            [███████████████████░]  95.9th
  Avg Finish Last 10           [████████████████████]  98.5th
  Cut % Last Year              [█████████████████░░░]  82.7th
  Top 5% Last Year             [███████████████████░]  96.5th
  Top 10% Last Year            [████████████████████]  98.7th
  Top 20% Last Year            [███████████████████░]  97.2th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [████████████████████]  99.3th
  Top 20 Finishes(Last 10)     [████████████████████]  98.2th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8469
  Composite Pctile : 80.8th percentile
  Tier             : N/A

  Career Events    : 53
  Career Cuts Miss : 7  (13.2%)
  Career Avg Finish: 27.7

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: MATT FITZPATRICK
═════════════════════════════════════════════════════════════════
datagolf ranking: 11.0
 dg_rank
    11.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T41    1         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T24    -7        The Genesis Invitational       The Riviera Country
  3    2026   9      -13       WM Phoenix Open                TPC Scottsdale
  4    2026   T14    -17       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T63    -13       The American Express           PGA West
  6    2025   T17    -1        BMW Championship               Caves Valley Golf Cl
  7    2025   T32    -4        FedEx St. Jude Championship    TPC Southwind
  8    2025   T8     -13       Wyndham Championship           Sedgefield Country C
  9    2025   T4     -11       The Open Championship          Royal Portrush Golf
  10   2025   T4     -12       Genesis Scottish Open          The Renaissance Club
  11   2025   T8     -19       Rocket Mortgage Classic        Detroit Golf Club
  12   2025   T17    -6        Travelers Championship         TPC River Highlands
  13   2025   T38    11        U.S. Open                      Oakmont Country Club
  14   2025   T31    5         The Memorial Tournament        Muirfield Village Go
  15   2025   T8     -4        PGA Championship               Quail Hollow Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 24.67
  Last  5 starts : 30.2
  Last 10 starts : 21.6
  Last  3 starts : avg finish = 24.67


In [41]:
# ── Tier 3 ────────────────────────────────────────────────────────
tier = 3
players = tier_df[tier_df['Tier'] == tier]['player'].tolist()

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: BEN GRIFFIN
═════════════════════════════════════════════════════════════════
datagolf ranking: 16.0
 dg_rank
    16.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    3         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T41    -3        The Genesis Invitational       The Riviera Country
  3    2026   T28    -7        WM Phoenix Open                TPC Scottsdale
  4    2026   T37    -11       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T24    -18       The American Express           PGA West
  6    2026   T19    -8        Sony Open in Hawaii            Waialae Country Club
  7    2025   1      -29       World Wide Technology Champi   El Cardonal at Diama
  8    2025   2      -18       Procore Championship           Silverado Resort
  9    2025   T10    -12       TOUR Championship              East Lake Golf Club
  10   2025   T12    -3        BMW Championship               Caves Valley Golf Cl
  11   2025   T9     -9        FedEx St. Jude Championship    TPC Southwind
  12   2025   T11    -12       Wyndham Championship           Sedgefield Country C
  13   2025   CUT    2         The Open Championship          Royal Portrush Golf
  14   2025   CUT    -3        John Deere Classic             TPC Deere Run
  15   2025   T13    -18       Rocket Mortgage Classic        Detroit Golf Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 49.67
  Last  5 starts : 42.0
  Last 10 starts : 25.4
  Last  3 starts : avg finish = 49.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    42.0     25.4
  Top 3 Finishes                   0        2
  Top 5 Finishes                   0        2
  Top 10 Finishes                  0        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     7        5            71.4      39.9         2       2       2
  2023     26       19           73.1      41.7         1       2       6
  2024     28       22           78.6      37.3         2       5       9
  2025     29       23           79.3      32.1         6       11      16
  2026     6        5            83.3      38.2         0       0       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [██████████████████░░]  88.1th
  SG Last 5 Events             [██████████████████░░]  91.6th
  SG Last 8 Events             [███████████████████░]  96.0th
  SG Last 13 Events            [████████████████████]  97.9th
  SG Last 21 Events            [████████████████████]  99.2th
  DG Index                     [███████████████████░]  96.5th
  OWGR Rank                    [███████████████████░]  97.0th

  — Finish Position —
  Avg Finish Last 3            [█████████████████░░░]  87.1th
  Avg Finish Last 5            [███████████████████░]  92.9th
  Avg Finish Last 10           [████████████████████]  98.2th
  Cut % Last Year              [████████████████░░░░]  82.1th
  Top 5% Last Year             [████████████████████]  98.8th
  Top 10% Last Year            [████████████████████]  99.2th
  Top 20% Last Year            [████████████████████]  98.8th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  98.2th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8405
  Composite Pctile : 79.1th percentile
  Tier             : N/A

  Career Events    : 96
  Career Cuts Miss : 22  (22.9%)
  Career Avg Finish: 37.2

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: BROOKS KOEPKA
═════════════════════════════════════════════════════════════════
datagolf ranking: 136.0
 dg_rank
   136.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T9     -10       Cognizant Classic in The Pal   PGA National Resort
  2    2026   CUT    2         WM Phoenix Open                TPC Scottsdale
  3    2026   T56    -4        Farmers Insurance Open         Torrey Pines Golf Co
  4    2025   CUT    7         The Open Championship          Royal Portrush Golf
  5    2025   T12    6         U.S. Open                      Oakmont Country Club
  6    2025   CUT    9         PGA Championship               Quail Hollow Club
  7    2025   CUT    5         Masters Tournament             Augusta National Gol
  8    2024   T26    6         U.S. Open                      Oakmont Country Club
  9    2024   T26    -9        PGA Championship               Quail Hollow Club
  10   2024   T45    9         Masters Tournament             Augusta National Gol
  11   2023   T17    -1        U.S. Open                      Oakmont Country Club
  12   2023   1      -9        PGA Championship               Quail Hollow Club
  13   2023   T2     -8        Masters Tournament             Augusta National Gol
  14   2022   55     12        U.S. Open                      Oakmont Country Club
  15   2022   T55    8         PGA Championship               Quail Hollow Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 48.33
  Last  5 starts : 47.4
  Last 10 starts : 49.4
  Last  3 starts : avg finish = 48.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    47.4     49.4
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        0
  Top 10 Finishes                  1        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     11       6            54.5      51.7         1       1       3
  2023     3        3            100.0     6.7          2       2       3
  2024     3        3            100.0     32.3         0       0       0
  2025     4        1            25.0      63.0         0       0       1
  2026     3        2            66.7      48.3         0       1       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  98.7th
  SG Last 3 Events             [██████████████████░░]  91.4th
  SG Last 5 Events             [███████████████████░]  92.6th
  SG Last 8 Events             [██████████████████░░]  90.7th
  SG Last 13 Events            [███████████████████░]  95.5th
  SG Last 21 Events            [███████████████████░]  93.6th
  DG Index                     [██████████████░░░░░░]  67.8th
  OWGR Rank                    [██████████░░░░░░░░░░]  49.9th

  — Finish Position —
  Avg Finish Last 3            [██████████████████░░]  87.8th
  Avg Finish Last 5            [██████████████████░░]  88.2th
  Avg Finish Last 10           [█████████████████░░░]  86.8th
  Cut % Last Year              [██████████░░░░░░░░░░]  48.2th
  Top 5% Last Year             [█████████░░░░░░░░░░░]  44.7th
  Top 10% Last Year            [█████████░░░░░░░░░░░]  43.1th
  Top 20% Last Year            [███████████████████░]  92.9th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [█████████░░░░░░░░░░░]  45.8th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.7784
  Composite Pctile : 64.4th percentile
  Tier             : N/A

  Career Events    : 24
  Career Cuts Miss : 9  (37.5%)
  Career Avg Finish: 45.1

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: CAMERON YOUNG
═════════════════════════════════════════════════════════════════
datagolf ranking: 7.0
 dg_rank
     7.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T3     -12       Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T7     -12       The Genesis Invitational       The Riviera Country
  3    2026   T41    -5        WM Phoenix Open                TPC Scottsdale
  4    2026   T55    -7        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T22    -10       Farmers Insurance Open         Torrey Pines Golf Co
  6    2025   T9     -12       Procore Championship           Silverado Resort
  7    2025   T4     -14       TOUR Championship              East Lake Golf Club
  8    2025   11     -5        BMW Championship               Caves Valley Golf Cl
  9    2025   5      -11       FedEx St. Jude Championship    TPC Southwind
  10   2025   1      -22       Wyndham Championship           Sedgefield Country C
  11   2025   CUT    4         The Open Championship          Royal Portrush Golf
  12   2025   T46    -11       Rocket Mortgage Classic        Detroit Golf Club
  13   2025   T52    1         Travelers Championship         TPC River Highlands
  14   2025   T4     3         U.S. Open                      Oakmont Country Club
  15   2025   T4     -16       RBC Canadian Open              TPC Toronto at Ospre

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 17.0
  Last  5 starts : 25.6
  Last 10 starts : 15.8
  Last  3 starts : avg finish = 17.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    25.6     15.8
  Top 3 Finishes                   1        2
  Top 5 Finishes                   1        4
  Top 10 Finishes                  2        6

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     20       15           75.0      35.6         5       5       9
  2023     20       17           85.0      41.7         0       3       6
  2024     19       18           94.7      34.7         2       6       7
  2025     25       18           72.0      40.0         5       8       11
  2026     5        5            100.0     25.6         1       2       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  99.7th
  SG Last 3 Events             [████████████████████]  99.4th
  SG Last 5 Events             [████████████████████]  99.0th
  SG Last 8 Events             [████████████████████]  99.8th
  SG Last 13 Events            [████████████████████]  99.7th
  SG Last 21 Events            [████████████████████]  99.5th
  DG Index                     [████████████████████]  98.5th
  OWGR Rank                    [███████████████████░]  96.5th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  98.7th
  Avg Finish Last 5            [████████████████████]  97.8th
  Avg Finish Last 10           [████████████████████]  99.7th
  Cut % Last Year              [███████████████░░░░░]  77.3th
  Top 5% Last Year             [████████████████████]  98.7th
  Top 10% Last Year            [████████████████████]  98.7th
  Top 20% Last Year            [████████████████████]  97.5th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  98.6th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [████████████████████]  99.8th
  Top 10 Finishes(Last 10)     [████████████████████]  99.8th
  Top 20 Finishes(Last 10)     [████████████████████]  99.5th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9780
  Composite Pctile : 99.2th percentile
  Tier             : N/A

  Career Events    : 89
  Career Cuts Miss : 16  (18.0%)
  Career Avg Finish: 37.5

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JACOB BRIDGEMAN
═════════════════════════════════════════════════════════════════
datagolf ranking: 30.0
 dg_rank
    30.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T18    -3        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   1      -18       The Genesis Invitational       The Riviera Country
  3    2026   T18    -9        WM Phoenix Open                TPC Scottsdale
  4    2026   T8     -18       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T13    -20       The American Express           PGA West
  6    2026   T4     -12       Sony Open in Hawaii            Waialae Country Club
  7    2025   CUT    0         The RSM Classic                Sea Island Golf Club
  8    2025   T46    -14       World Wide Technology Champi   El Cardonal at Diama
  9    2025   CUT    -3        Sanderson Farms Championship   The Country Club of
  10   2025   T27    0         TOUR Championship              East Lake Golf Club
  11   2025   T19    0         BMW Championship               Caves Valley Golf Cl
  12   2025   T17    -7        FedEx St. Jude Championship    TPC Southwind
  13   2025   T38    -5        Wyndham Championship           Sedgefield Country C
  14   2025   CUT    -3        3M Open                        TPC Twin Cities
  15   2025   T75    6         Genesis Scottish Open          The Renaissance Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 12.33
  Last  5 starts : 11.6
  Last 10 starts : 29.5
  Last  3 starts : avg finish = 12.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    11.6     29.5
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        2
  Top 10 Finishes                  2        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     2        2            100.0     54.5         0       0       0
  2024     20       12           60.0      47.8         0       0       6
  2025     29       18           62.1      48.5         4       4       7
  2026     6        6            100.0     10.3         2       3       6

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  92.6th
  SG Last 3 Events             [████████████████████]  99.5th
  SG Last 5 Events             [████████████████████]  99.7th
  SG Last 8 Events             [████████████████████]  98.8th
  SG Last 13 Events            [███████████████████░]  97.5th
  SG Last 21 Events            [███████████████████░]  95.1th
  DG Index                     [███████████████████░]  92.9th
  OWGR Rank                    [███████████████████░]  94.9th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.7th
  Avg Finish Last 5            [████████████████████]  99.7th
  Avg Finish Last 10           [███████████████████░]  97.4th
  Cut % Last Year              [██████████████░░░░░░]  69.7th
  Top 5% Last Year             [████████████████████]  97.8th
  Top 10% Last Year            [███████████████████░]  94.9th
  Top 20% Last Year            [██████████████████░░]  92.3th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  98.6th
  Top 20 Finishes (Last 5)     [████████████████████]  100.0th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  99.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9592
  Composite Pctile : 96.7th percentile
  Tier             : N/A

  Career Events    : 57
  Career Cuts Miss : 19  (33.3%)
  Career Avg Finish: 44.5

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JASON DAY
═════════════════════════════════════════════════════════════════
datagolf ranking: 43.0
 dg_rank
    43.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    4         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    5         The Genesis Invitational       The Riviera Country
  3    2026   T24    -14       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   T38    -7        Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T2     -23       The American Express           PGA West
  6    2025   T20    -12       Black Desert Championship      Black Desert Resort
  7    2025   T23    1         BMW Championship               Caves Valley Golf Cl
  8    2025   T56    2         FedEx St. Jude Championship    TPC Southwind
  9    2025   CUT    2         The Open Championship          Royal Portrush Golf
  10   2025   CUT    -2        John Deere Classic             TPC Deere Run
  11   2025   T4     -13       Travelers Championship         TPC River Highlands
  12   2025   T23    8         U.S. Open                      Oakmont Country Club
  13   2025   CUT    6         PGA Championship               Quail Hollow Club
  14   2025   T49    -4        RBC Heritage                   Harbour Town Golf Li
  15   2025   T8     -5        Masters Tournament             Augusta National Gol

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 61.33
  Last  5 starts : 44.8
  Last 10 starts : 48.3

In [43]:
# Build players list from a specific tier
tier = 4
players = tier_df[tier_df['Tier'] == tier]['player'].tolist()

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: AKSHAY BHATIA
═════════════════════════════════════════════════════════════════
datagolf ranking: 17.0
 dg_rank
    17.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   1      -15       Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T16    -10       The Genesis Invitational       The Riviera Country
  3    2026   T3     -15       WM Phoenix Open                TPC Scottsdale
  4    2026   T6     -19       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   CUT    1         Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   CUT    -1        The American Express           PGA West
  7    2025   CUT    1         Sanderson Farms Championship   The Country Club of
  8    2025   T11    -11       Procore Championship           Silverado Resort
  9    2025   T13    -10       TOUR Championship              East Lake Golf Club
  10   2025   T26    2         BMW Championship               Caves Valley Golf Cl
  11   2025   T6     -10       FedEx St. Jude Championship    TPC Southwind
  12   2025   W/D    -2        Wyndham Championship           Sedgefield Country C
  13   2025   T25    -14       3M Open                        TPC Twin Cities
  14   2025   T30    -4        The Open Championship          Royal Portrush Golf
  15   2025   T26    -15       Rocket Mortgage Classic        Detroit Golf Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 6.67
  Last  5 starts : 21.2
  Last 10 starts : 31.6
  Last  3 starts : avg finish = 6.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    21.2     31.6
  Top 3 Finishes                   2        2
  Top 5 Finishes                   2        2
  Top 10 Finishes                  3        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     2        2            100.0     31.0         0       0       1
  2023     18       12           66.7      50.7         1       2       3
  2024     25       18           72.0      39.0         3       3       11
  2025     25       20           80.0      36.1         1       4       7
  2026     6        4            66.7      31.0         2       3       4

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  100.0th
  SG Last 3 Events             [████████████████████]  99.9th
  SG Last 5 Events             [████████████████████]  99.5th
  SG Last 8 Events             [████████████████████]  98.3th
  SG Last 13 Events            [████████████████████]  98.2th
  SG Last 21 Events            [███████████████████░]  96.0th
  DG Index                     [███████████████████░]  96.2th
  OWGR Rank                    [███████████████████░]  95.4th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.9th
  Avg Finish Last 5            [████████████████████]  98.7th
  Avg Finish Last 10           [███████████████████░]  96.5th
  Cut % Last Year              [█████████████████░░░]  82.7th
  Top 5% Last Year             [██████████████████░░]  90.5th
  Top 10% Last Year            [███████████████████░]  95.8th
  Top 20% Last Year            [███████████████████░]  94.1th
  Top 5 Finishes (Last 5)      [████████████████████]  99.6th
  Top 10 Finishes (Last 5)     [████████████████████]  99.6th
  Top 20 Finishes (Last 5)     [████████████████████]  99.5th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  99.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9715
  Composite Pctile : 97.9th percentile
  Tier             : N/A

  Career Events    : 76
  Career Cuts Miss : 20  (26.3%)
  Career Avg Finish: 40.0

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: HARRIS ENGLISH
═════════════════════════════════════════════════════════════════
datagolf ranking: 19.0
 dg_rank
    19.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T24    -2        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T22    -8        The Genesis Invitational       The Riviera Country
  3    2026   T28    -7        WM Phoenix Open                TPC Scottsdale
  4    2026   T24    -14       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T22    -10       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T27    -17       The American Express           PGA West
  7    2025   T47    -12       The RSM Classic                Sea Island Golf Club
  8    2025   T43    -5        Procore Championship           Silverado Resort
  9    2025   T13    -10       TOUR Championship              East Lake Golf Club
  10   2025   T12    -3        BMW Championship               Caves Valley Golf Cl
  11   2025   T48    -1        FedEx St. Jude Championship    TPC Southwind
  12   2025   2      -13       The Open Championship          Royal Portrush Golf
  13   2025   T22    -5        Genesis Scottish Open          The Renaissance Club
  14   2025   T4     -13       Travelers Championship         TPC River Highlands
  15   2025   T59    18        U.S. Open                      Oakmont Country Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 24.67
  Last  5 starts : 24.0
  Last 10 starts : 26.2
  Last  3 starts : avg finish = 24.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    24.0     26.2
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        0
  Top 10 Finishes                  0        0

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     12       8            66.7      49.8         0       1       2
  2023     21       15           71.4      46.2         2       4       6
  2024     23       18           78.3      40.6         0       3       8
  2025     23       21           91.3      32.8         4       4       10
  2026     6        6            100.0     24.5         0       0       0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  89.9th
  SG Last 3 Events             [███████████████████░]  96.1th
  SG Last 5 Events             [████████████████████]  98.4th
  SG Last 8 Events             [███████████████████░]  97.4th
  SG Last 13 Events            [███████████████████░]  97.3th
  SG Last 21 Events            [████████████████████]  98.0th
  DG Index                     [███████████████████░]  95.7th
  OWGR Rank                    [███████████████████░]  96.2th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  97.3th
  Avg Finish Last 5            [████████████████████]  98.4th
  Avg Finish Last 10           [████████████████████]  98.2th
  Cut % Last Year              [██████████████████░░]  88.0th
  Top 5% Last Year             [████████████████████]  98.2th
  Top 10% Last Year            [███████████████████░]  96.0th
  Top 20% Last Year            [███████████████████░]  97.4th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [█████████░░░░░░░░░░░]  45.8th
  Top 10 Finishes(Last 10)     [█████████░░░░░░░░░░░]  43.1th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8056
  Composite Pctile : 70.7th percentile
  Tier             : N/A

  Career Events    : 85
  Career Cuts Miss : 17  (20.0%)
  Career Avg Finish: 40.0

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JAKE KNAPP
═════════════════════════════════════════════════════════════════
datagolf ranking: 15.0
 dg_rank
    15.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   6      -13       The Genesis Invitational       The Riviera Country
  2    2026   8      -14       WM Phoenix Open                TPC Scottsdale
  3    2026   T8     -18       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   T5     -15       Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T11    -10       Sony Open in Hawaii            Waialae Country Club
  6    2025   T62    5         FedEx St. Jude Championship    TPC Southwind
  7    2025   CUT    -1        Wyndham Championship           Sedgefield Country C
  8    2025   T3     -20       3M Open                        TPC Twin Cities
  9    2025   T22    -5        Genesis Scottish Open          The Renaissance Club
  10   2025   T21    -13       John Deere Classic             TPC Deere Run
  11   2025   T4     -21       Rocket Mortgage Classic        Detroit Golf Club
  12   2025   T27    -10       RBC Canadian Open              TPC Toronto at Ospre
  13   2025   CUT    2         Charles Schwab Challenge       Colonial Country Clu
  14   2025   CUT    2         PGA Championship               Quail Hollow Club
  15   2025   T39    -11       THE CJ CUP Byron Nelson        TPC Craig Ranch

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 7.33
  Last  5 starts : 7.6
  Last 10 starts : 22.6
  Last  3 starts : avg finish = 7.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                     7.6     22.6
  Top 3 Finishes                   0        1
  Top 5 Finishes                   1        2
  Top 10 Finishes                  4        5

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2023     1        0            0.0       80.0         0       0       0
  2024     23       18           78.3      50.3         3       4       4
  2025     22       16           72.7      41.4         2       3       5
  2026     5        5            100.0     7.6          1       4       5

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  99.0th
  SG Last 3 Events             [████████████████████]  99.8th
  SG Last 5 Events             [████████████████████]  99.9th
  SG Last 8 Events             [████████████████████]  99.5th
  SG Last 13 Events            [████████████████████]  99.4th
  SG Last 21 Events            [████████████████████]  99.0th
  DG Index                     [███████████████████░]  96.7th
  OWGR Rank                    [██████████████████░░]  89.9th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.8th
  Avg Finish Last 5            [████████████████████]  99.9th
  Avg Finish Last 10           [████████████████████]  98.8th
  Cut % Last Year              [████████████████░░░░]  78.0th
  Top 5% Last Year             [███████████████████░]  95.5th
  Top 10% Last Year            [███████████████████░]  94.7th
  Top 20% Last Year            [██████████████████░░]  91.4th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  99.9th
  Top 20 Finishes (Last 5)     [████████████████████]  100.0th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  99.7th
  Top 20 Finishes(Last 10)     [████████████████████]  99.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9721
  Composite Pctile : 98.3th percentile
  Tier             : N/A

  Career Events    : 51
  Career Cuts Miss : 12  (23.5%)
  Career Avg Finish: 42.6

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JORDAN SPIETH
═════════════════════════════════════════════════════════════════
datagolf ranking: 36.0
 dg_rank
    36.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T11    -6        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T12    -11       The Genesis Invitational       The Riviera Country
  3    2026   CUT    3         WM Phoenix Open                TPC Scottsdale
  4    2026   T29    -13       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T24    -7        Sony Open in Hawaii            Waialae Country Club
  6    2025   T38    -3        FedEx St. Jude Championship    TPC Southwind
  7    2025   T31    -7        Wyndham Championship           Sedgefield Country C
  8    2025   T40    -2        The Open Championship          Royal Portrush Golf
  9    2025   W/D    0         Travelers Championship         TPC River Highlands
  10   2025   T23    8         U.S. Open                      Oakmont Country Club
  11   2025   T7     -1        The Memorial Tournament        Muirfield Village Go
  12   2025   T36    -2        Charles Schwab Challenge       Colonial Country Clu
  13   2025   CUT    2         PGA Championship               Quail Hollow Club
  14   2025   T34    -4        Truist Championship            The Philadelphia Cri
  15   2025   4      -19       THE CJ CUP Byron Nelson        TPC Craig Ranch

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 34.33
  Last  5 starts : 31.2
  Last 10 starts : 29.5
  Last  3 starts : avg finish = 34.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    31.2     29.5
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        0
  Top 10 Finishes                  0        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     18       13           72.2      37.9         2       4       7
  2023     18       12           66.7      35.1         5       7       9
  2024     20       13           65.0      51.8         1       3       3
  2025     19       17           89.5      32.6         2       4       7
  2026     5        4            80.0      31.2         0       0       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  96.5th
  SG Last 3 Events             [███████████████████░]  94.0th
  SG Last 5 Events             [███████████████████░]  96.5th
  SG Last 8 Events             [███████████████████░]  95.6th
  SG Last 13 Events            [███████████████████░]  95.9th
  SG Last 21 Events            [████████████████████]  97.7th
  DG Index                     [██████████████████░░]  91.4th
  OWGR Rank                    [█████████████████░░░]  84.8th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  94.3th
  Avg Finish Last 5            [███████████████████░]  96.0th
  Avg Finish Last 10           [███████████████████░]  97.4th
  Cut % Last Year              [█████████████████░░░]  86.8th
  Top 5% Last Year             [███████████████████░]  96.8th
  Top 10% Last Year            [███████████████████░]  97.2th
  Top 20% Last Year            [███████████████████░]  96.8th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [█████████░░░░░░░░░░░]  45.8th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8488
  Composite Pctile : 82.0th percentile
  Tier             : N/A

  Career Events    : 80
  Career Cuts Miss : 21  (26.2%)
  Career Avg Finish: 39.1

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: KURT KITAYAMA
═════════════════════════════════════════════════════════════════
datagolf ranking: 28.0
 dg_rank
    28.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T18    -3        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T2     -17       The Genesis Invitational       The Riviera Country
  3    2026   T24    -8        WM Phoenix Open                TPC Scottsdale
  4    2026   T48    -9        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   CUT    -10       The American Express           PGA West
  6    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  7    2025   T15    -13       Black Desert Championship      Black Desert Resort
  8    2025   T48    -2        Baycurrent Classic             Yokohama Country Clu
  9    2025   T19    0         BMW Championship               Caves Valley Golf Cl
  10   2025   T9     -9        FedEx St. Jude Championship    TPC Southwind
  11   2025   T31    -7        Wyndham Championship           Sedgefield Country C
  12   2025   1      -23       3M Open                        TPC Twin Cities
  13   2025   T5     -16       John Deere Classic             TPC Deere Run
  14   2025   T51    -10       Rocket Mortgage Classic        Detroit Golf Club
  15   2025   CUT    -1        RBC Canadian Open              TPC Toronto at Ospre

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 14.67
  Last  5 starts : 34.4
  Last 10 starts : 30.3
  Last  3 starts : avg finish = 14.67


In [44]:
# ── Tier 4 ────────────────────────────────────────────────────────
players = [

    'Adam Scott', 
    'Akshay Bhatia',
    'Jacob Bridgeman',
    'Jason Day',
    'Jordan Spieth',
    'Justin Thomas',
    'Keegan Bradley',
    'Maverick McNealy', 
    'Pierceson Coody',
    'Sepp Straka', 
   
]
# ──────────────────────────────────────────────────────────────────────────

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ADAM SCOTT
═════════════════════════════════════════════════════════════════
datagolf ranking: 29.0
 dg_rank
    29.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T11    -6        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   4      -16       The Genesis Invitational       The Riviera Country
  3    2026   T30    -8        Farmers Insurance Open         Torrey Pines Golf Co
  4    2026   T24    -18       The American Express           PGA West
  5    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  6    2025   T27    -7        Baycurrent Classic             Yokohama Country Clu
  7    2025   T55    -3        Wyndham Championship           Sedgefield Country C
  8    2025   T53    -10       3M Open                        TPC Twin Cities
  9    2025   CUT    9         The Open Championship          Royal Portrush Golf
  10   2025   T17    -6        Genesis Scottish Open          The Renaissance Club
  11   2025   T30    -4        Travelers Championship         TPC River Highlands
  12   2025   T12    6         U.S. Open                      Oakmont Country Club
  13   2025   T31    5         The Memorial Tournament        Muirfield Village Go
  14   2025   T19    -2        PGA Championship               Quail Hollow Club
  15   2025   T34    -4        Truist Championship            The Philadelphia Cri

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 15.0
  Last  5 starts : 21.8
  Last 10 starts : 34.1
  Last  3 starts : avg finish = 15.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    21.8     34.1
  Top 3 Finishes                   0        0
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     15       13           86.7      39.4         3       3       4
  2023     17       15           88.2      33.5         2       5       6
  2024     17       15           88.2      28.1         3       4       8
  2025     18       15           83.3      40.8         0       0       4
  2026     5        5            100.0     21.8         1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  96.5th
  SG Last 3 Events             [████████████████████]  99.3th
  SG Last 5 Events             [████████████████████]  99.2th
  SG Last 8 Events             [████████████████████]  97.7th
  SG Last 13 Events            [████████████████████]  98.2th
  SG Last 21 Events            [███████████████████░]  96.6th
  DG Index                     [███████████████████░]  93.2th
  OWGR Rank                    [██████████████████░░]  87.8th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.2th
  Avg Finish Last 5            [████████████████████]  98.7th
  Avg Finish Last 10           [███████████████████░]  95.7th
  Cut % Last Year              [█████████████████░░░]  84.6th
  Top 5% Last Year             [█████████░░░░░░░░░░░]  44.7th
  Top 10% Last Year            [█████████░░░░░░░░░░░]  43.1th
  Top 20% Last Year            [██████████████████░░]  91.0th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9128
  Composite Pctile : 87.9th percentile
  Tier             : N/A

  Career Events    : 72
  Career Cuts Miss : 9  (12.5%)
  Career Avg Finish: 34.5

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: AKSHAY BHATIA
═════════════════════════════════════════════════════════════════
datagolf ranking: 17.0
 dg_rank
    17.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   1      -15       Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T16    -10       The Genesis Invitational       The Riviera Country
  3    2026   T3     -15       WM Phoenix Open                TPC Scottsdale
  4    2026   T6     -19       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   CUT    1         Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   CUT    -1        The American Express           PGA West
  7    2025   CUT    1         Sanderson Farms Championship   The Country Club of
  8    2025   T11    -11       Procore Championship           Silverado Resort
  9    2025   T13    -10       TOUR Championship              East Lake Golf Club
  10   2025   T26    2         BMW Championship               Caves Valley Golf Cl
  11   2025   T6     -10       FedEx St. Jude Championship    TPC Southwind
  12   2025   W/D    -2        Wyndham Championship           Sedgefield Country C
  13   2025   T25    -14       3M Open                        TPC Twin Cities
  14   2025   T30    -4        The Open Championship          Royal Portrush Golf
  15   2025   T26    -15       Rocket Mortgage Classic        Detroit Golf Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 6.67
  Last  5 starts : 21.2
  Last 10 starts : 31.6
  Last  3 starts : avg finish = 6.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    21.2     31.6
  Top 3 Finishes                   2        2
  Top 5 Finishes                   2        2
  Top 10 Finishes                  3        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     2        2            100.0     31.0         0       0       1
  2023     18       12           66.7      50.7         1       2       3
  2024     25       18           72.0      39.0         3       3       11
  2025     25       20           80.0      36.1         1       4       7
  2026     6        4            66.7      31.0         2       3       4

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  100.0th
  SG Last 3 Events             [████████████████████]  99.9th
  SG Last 5 Events             [████████████████████]  99.5th
  SG Last 8 Events             [████████████████████]  98.3th
  SG Last 13 Events            [████████████████████]  98.2th
  SG Last 21 Events            [███████████████████░]  96.0th
  DG Index                     [███████████████████░]  96.2th
  OWGR Rank                    [███████████████████░]  95.4th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.9th
  Avg Finish Last 5            [████████████████████]  98.7th
  Avg Finish Last 10           [███████████████████░]  96.5th
  Cut % Last Year              [█████████████████░░░]  82.7th
  Top 5% Last Year             [██████████████████░░]  90.5th
  Top 10% Last Year            [███████████████████░]  95.8th
  Top 20% Last Year            [███████████████████░]  94.1th
  Top 5 Finishes (Last 5)      [████████████████████]  99.6th
  Top 10 Finishes (Last 5)     [████████████████████]  99.6th
  Top 20 Finishes (Last 5)     [████████████████████]  99.5th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  99.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9715
  Composite Pctile : 97.9th percentile
  Tier             : N/A

  Career Events    : 76
  Career Cuts Miss : 20  (26.3%)
  Career Avg Finish: 40.0

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JACOB BRIDGEMAN
═════════════════════════════════════════════════════════════════
datagolf ranking: 30.0
 dg_rank
    30.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T18    -3        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   1      -18       The Genesis Invitational       The Riviera Country
  3    2026   T18    -9        WM Phoenix Open                TPC Scottsdale
  4    2026   T8     -18       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T13    -20       The American Express           PGA West
  6    2026   T4     -12       Sony Open in Hawaii            Waialae Country Club
  7    2025   CUT    0         The RSM Classic                Sea Island Golf Club
  8    2025   T46    -14       World Wide Technology Champi   El Cardonal at Diama
  9    2025   CUT    -3        Sanderson Farms Championship   The Country Club of
  10   2025   T27    0         TOUR Championship              East Lake Golf Club
  11   2025   T19    0         BMW Championship               Caves Valley Golf Cl
  12   2025   T17    -7        FedEx St. Jude Championship    TPC Southwind
  13   2025   T38    -5        Wyndham Championship           Sedgefield Country C
  14   2025   CUT    -3        3M Open                        TPC Twin Cities
  15   2025   T75    6         Genesis Scottish Open          The Renaissance Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 12.33
  Last  5 starts : 11.6
  Last 10 starts : 29.5
  Last  3 starts : avg finish = 12.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    11.6     29.5
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        2
  Top 10 Finishes                  2        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     2        2            100.0     54.5         0       0       0
  2024     20       12           60.0      47.8         0       0       6
  2025     29       18           62.1      48.5         4       4       7
  2026     6        6            100.0     10.3         2       3       6

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  92.6th
  SG Last 3 Events             [████████████████████]  99.5th
  SG Last 5 Events             [████████████████████]  99.7th
  SG Last 8 Events             [████████████████████]  98.8th
  SG Last 13 Events            [███████████████████░]  97.5th
  SG Last 21 Events            [███████████████████░]  95.1th
  DG Index                     [███████████████████░]  92.9th
  OWGR Rank                    [███████████████████░]  94.9th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.7th
  Avg Finish Last 5            [████████████████████]  99.7th
  Avg Finish Last 10           [███████████████████░]  97.4th
  Cut % Last Year              [██████████████░░░░░░]  69.7th
  Top 5% Last Year             [████████████████████]  97.8th
  Top 10% Last Year            [███████████████████░]  94.9th
  Top 20% Last Year            [██████████████████░░]  92.3th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  98.6th
  Top 20 Finishes (Last 5)     [████████████████████]  100.0th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  99.0th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9592
  Composite Pctile : 96.7th percentile
  Tier             : N/A

  Career Events    : 57
  Career Cuts Miss : 19  (33.3%)
  Career Avg Finish: 44.5

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JASON DAY
═════════════════════════════════════════════════════════════════
datagolf ranking: 43.0
 dg_rank
    43.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    4         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    5         The Genesis Invitational       The Riviera Country
  3    2026   T24    -14       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   T38    -7        Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T2     -23       The American Express           PGA West
  6    2025   T20    -12       Black Desert Championship      Black Desert Resort
  7    2025   T23    1         BMW Championship               Caves Valley Golf Cl
  8    2025   T56    2         FedEx St. Jude Championship    TPC Southwind
  9    2025   CUT    2         The Open Championship          Royal Portrush Golf
  10   2025   CUT    -2        John Deere Classic             TPC Deere Run
  11   2025   T4     -13       Travelers Championship         TPC River Highlands
  12   2025   T23    8         U.S. Open                      Oakmont Country Club
  13   2025   CUT    6         PGA Championship               Quail Hollow Club
  14   2025   T49    -4        RBC Heritage                   Harbour Town Golf Li
  15   2025   T8     -5        Masters Tournament             Augusta National Gol

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 61.33
  Last  5 starts : 44.8
  Last 10 starts : 48.3
  Last  3 starts : avg finish = 61.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    44.8     48.3
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     18       11           61.1      54.1         1       1       3
  2023     17       13           76.5      36.1         2       5       8
  2024     18       15           83.3      37.4         1       3       4
  2025     17       14           82.4      35.1         2       4       6
  2026     5        3            60.0      44.8         1       1       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [█████████████████░░░]  83.1th
  SG Last 5 Events             [████████████████████]  97.9th
  SG Last 8 Events             [████████████████████]  97.6th
  SG Last 13 Events            [███████████████████░]  96.5th
  SG Last 21 Events            [███████████████████░]  97.0th
  DG Index                     [██████████████████░░]  89.9th
  OWGR Rank                    [██████████████████░░]  90.4th

  — Finish Position —
  Avg Finish Last 3            [███████████████░░░░░]  75.1th
  Avg Finish Last 5            [██████████████████░░]  90.1th
  Avg Finish Last 10           [██████████████████░░]  87.7th
  Cut % Last Year              [█████████████████░░░]  84.3th
  Top 5% Last Year             [███████████████████░]  97.1th
  Top 10% Last Year            [███████████████████░]  97.4th
  Top 20% Last Year            [███████████████████░]  96.2th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8739
  Composite Pctile : 86.6th percentile
  Tier             : N/A

  Career Events    : 75
  Career Cuts Miss : 19  (25.3%)
  Career Avg Finish: 40.9

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: JORDAN SPIETH
═════════════════════════════════════════════════════════════════
datagolf ranking: 36.0
 dg_rank
    36.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T11    -6        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T12    -11       The Genesis Invitational       The Riviera Country
  3    2026   CUT    3         WM Phoenix Open                TPC Scottsdale
  4    2026   T29    -13       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T24    -7        Sony Open in Hawaii            Waialae Country Club
  6    2025   T38    -3        FedEx St. Jude Championship    TPC Southwind
  7    2025   T31    -7        Wyndham Championship           Sedgefield Country C
  8    2025   T40    -2        The Open Championship          Royal Portrush Golf
  9    2025   W/D    0         Travelers Championship         TPC River Highlands
  10   2025   T23    8         U.S. Open                      Oakmont Country Club
  11   2025   T7     -1        The Memorial Tournament        Muirfield Village Go
  12   2025   T36    -2        Charles Schwab Challenge       Colonial Country Clu
  13   2025   CUT    2         PGA Championship               Quail Hollow Club
  14   2025   T34    -4        Truist Championship            The Philadelphia Cri
  15   2025   4      -19       THE CJ CUP Byron Nelson        TPC Craig Ranch

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 34.33
  Last  5 starts : 31.2
  Last 10 starts : 29.5

In [45]:
# Build players list from a specific tier
tier = 5
players = tier_df[tier_df['Tier'] == tier]['player'].tolist()

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: AARON RAI
═════════════════════════════════════════════════════════════════
datagolf ranking: 63.0
 dg_rank
    63.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T23    -7        Cognizant Classic in The Pal   PGA National Resort
  2    2026   T28    -6        The Genesis Invitational       The Riviera Country
  3    2026   T73    1         ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   T50    -4        Sony Open in Hawaii            Waialae Country Club
  5    2025   T22    -6        FedEx St. Jude Championship    TPC Southwind
  6    2025   T5     -14       Wyndham Championship           Sedgefield Country C
  7    2025   T34    -3        The Open Championship          Royal Portrush Golf
  8    2025   T47    -2        Genesis Scottish Open          The Renaissance Club
  9    2025   T17    -6        Travelers Championship         TPC River Highlands
  10   2025   T33    9         U.S. Open                      Oakmont Country Club
  11   2025   CUT    9         The Memorial Tournament        Muirfield Village Go
  12   2025   CUT    1         Charles Schwab Challenge       Colonial Country Clu
  13   2025   T19    -2        PGA Championship               Quail Hollow Club
  14   2025   T23    -6        Truist Championship            The Philadelphia Cri
  15   2025   T38    -6        RBC Heritage                   Harbour Town Golf Li

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 41.33
  Last  5 starts : 39.2
  Last 10 starts : 33.2
  Last  3 starts : avg finish = 41.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    39.2     33.2
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     23       17           73.9      52.6         0       1       3
  2023     24       16           66.7      46.5         1       3       6
  2024     21       18           85.7      31.1         4       6       10
  2025     20       16           80.0      35.3         2       2       7
  2026     4        4            100.0     43.5         0       0       0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  95.5th
  SG Last 3 Events             [██████████████████░░]  88.6th
  SG Last 5 Events             [██████████████████░░]  92.2th
  SG Last 8 Events             [███████████████████░]  95.1th
  SG Last 13 Events            [███████████████████░]  95.5th
  SG Last 21 Events            [███████████████████░]  96.5th
  DG Index                     [█████████████████░░░]  85.6th
  OWGR Rank                    [██████████████████░░]  91.6th

  — Finish Position —
  Avg Finish Last 3            [██████████████████░░]  91.8th
  Avg Finish Last 5            [███████████████████░]  94.4th
  Avg Finish Last 10           [███████████████████░]  96.2th
  Cut % Last Year              [█████████████████░░░]  82.7th
  Top 5% Last Year             [███████████████████░]  96.2th
  Top 10% Last Year            [██████████████████░░]  92.5th
  Top 20% Last Year            [███████████████████░]  96.0th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8463
  Composite Pctile : 80.3th percentile
  Tier             : N/A

  Career Events    : 92
  Career Cuts Miss : 21  (22.8%)
  Career Avg Finish: 42.0

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ADAM SCOTT
═════════════════════════════════════════════════════════════════
datagolf ranking: 29.0
 dg_rank
    29.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T11    -6        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   4      -16       The Genesis Invitational       The Riviera Country
  3    2026   T30    -8        Farmers Insurance Open         Torrey Pines Golf Co
  4    2026   T24    -18       The American Express           PGA West
  5    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  6    2025   T27    -7        Baycurrent Classic             Yokohama Country Clu
  7    2025   T55    -3        Wyndham Championship           Sedgefield Country C
  8    2025   T53    -10       3M Open                        TPC Twin Cities
  9    2025   CUT    9         The Open Championship          Royal Portrush Golf
  10   2025   T17    -6        Genesis Scottish Open          The Renaissance Club
  11   2025   T30    -4        Travelers Championship         TPC River Highlands
  12   2025   T12    6         U.S. Open                      Oakmont Country Club
  13   2025   T31    5         The Memorial Tournament        Muirfield Village Go
  14   2025   T19    -2        PGA Championship               Quail Hollow Club
  15   2025   T34    -4        Truist Championship            The Philadelphia Cri

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 15.0
  Last  5 starts : 21.8
  Last 10 starts : 34.1
  Last  3 starts : avg finish = 15.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    21.8     34.1
  Top 3 Finishes                   0        0
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     15       13           86.7      39.4         3       3       4
  2023     17       15           88.2      33.5         2       5       6
  2024     17       15           88.2      28.1         3       4       8
  2025     18       15           83.3      40.8         0       0       4
  2026     5        5            100.0     21.8         1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  96.5th
  SG Last 3 Events             [████████████████████]  99.3th
  SG Last 5 Events             [████████████████████]  99.2th
  SG Last 8 Events             [████████████████████]  97.7th
  SG Last 13 Events            [████████████████████]  98.2th
  SG Last 21 Events            [███████████████████░]  96.6th
  DG Index                     [███████████████████░]  93.2th
  OWGR Rank                    [██████████████████░░]  87.8th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  99.2th
  Avg Finish Last 5            [████████████████████]  98.7th
  Avg Finish Last 10           [███████████████████░]  95.7th
  Cut % Last Year              [█████████████████░░░]  84.6th
  Top 5% Last Year             [█████████░░░░░░░░░░░]  44.7th
  Top 10% Last Year            [█████████░░░░░░░░░░░]  43.1th
  Top 20% Last Year            [██████████████████░░]  91.0th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9128
  Composite Pctile : 87.9th percentile
  Tier             : N/A

  Career Events    : 72
  Career Cuts Miss : 9  (12.5%)
  Career Avg Finish: 34.5

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ALEX NOREN
═════════════════════════════════════════════════════════════════
datagolf ranking: 24.0
 dg_rank
    24.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T24    -2        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T12    -11       The Genesis Invitational       The Riviera Country
  3    2026   T29    -13       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   CUT    0         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   CUT    -7        The American Express           PGA West
  6    2025   CUT    -1        Black Desert Championship      Black Desert Resort
  7    2025   T27    -7        Baycurrent Classic             Yokohama Country Clu
  8    2025   T3     -15       Wyndham Championship           Sedgefield Country C
  9    2025   T7     -19       3M Open                        TPC Twin Cities
  10   2025   CUT    1         Genesis Scottish Open          The Renaissance Club
  11   2025   CUT    -3        Rocket Mortgage Classic        Detroit Golf Club
  12   2025   T30    -4        Travelers Championship         TPC River Highlands
  13   2025   CUT    -2        RBC Canadian Open              TPC Toronto at Ospre
  14   2025   T39    7         The Memorial Tournament        Muirfield Village Go
  15   2025   T17    -3        PGA Championship               Quail Hollow Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 21.67
  Last  5 starts : 45.0
  Last 10 starts : 42.2
  Last  3 starts : avg finish = 21.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    45.0     42.2
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     17       13           76.5      41.9         1       2       4
  2023     22       12           54.5      51.7         2       3       5
  2024     17       14           82.4      30.8         1       4       8
  2025     11       7            63.6      44.9         1       2       3
  2026     5        3            60.0      45.0         0       0       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  89.9th
  SG Last 3 Events             [███████████████████░]  97.4th
  SG Last 5 Events             [██████████████████░░]  90.5th
  SG Last 8 Events             [██████████████████░░]  91.5th
  SG Last 13 Events            [██████████████████░░]  90.0th
  SG Last 21 Events            [██████████████████░░]  91.9th
  DG Index                     [███████████████████░]  94.4th
  OWGR Rank                    [███████████████████░]  96.0th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  98.0th
  Avg Finish Last 5            [██████████████████░░]  89.9th
  Avg Finish Last 10           [██████████████████░░]  92.2th
  Cut % Last Year              [██████████████░░░░░░]  70.8th
  Top 5% Last Year             [███████████████████░]  95.5th
  Top 10% Last Year            [███████████████████░]  96.3th
  Top 20% Last Year            [███████████████████░]  93.8th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8640
  Composite Pctile : 84.9th percentile
  Tier             : N/A

  Career Events    : 72
  Career Cuts Miss : 23  (31.9%)
  Career Avg Finish: 42.9

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: J.J. SPAUN
═════════════════════════════════════════════════════════════════
datagolf ranking: 31.0
 dg_rank
    31.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    3         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    4         The Genesis Invitational       The Riviera Country
  3    2026   T45    -10       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   CUT    0         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  6    2025   T11    -22       World Wide Technology Champi   El Cardonal at Diama
  7    2025   6      -15       Procore Championship           Silverado Resort
  8    2025   T25    -4        TOUR Championship              East Lake Golf Club
  9    2025   T23    1         BMW Championship               Caves Valley Golf Cl
  10   2025   2      -16       FedEx St. Jude Championship    TPC Southwind
  11   2025   T23    -6        The Open Championship          Royal Portrush Golf
  12   2025   CUT    2         Genesis Scottish Open          The Renaissance Club
  13   2025   T14    -7        Travelers Championship         TPC River Highlands
  14   2025   1      -1        U.S. Open                      Oakmont Country Club
  15   2025   CUT    6         The Memorial Tournament        Muirfield Village Go

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 68.33
  Last  5 starts : 65.0
  Last 10 starts : 39.2
  Last  3 starts : avg finish = 68.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    65.0     39.2
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     26       18           69.2      46.5         1       2       4
  2023     22       15           68.2      44.6         1       2       5
  2024     22       12           54.5      51.6         1       4       4
  2025     25       22           88.0      26.9         5       7       11
  2026     5        2            40.0      65.0         0       0       0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [███████████████░░░░░]  75.5th
  SG Last 5 Events             [████████████████░░░░]  79.3th
  SG Last 8 Events             [█████████████████░░░]  85.9th
  SG Last 13 Events            [██████████████████░░]  90.2th
  SG Last 21 Events            [███████████████████░]  93.4th
  DG Index                     [███████████████████░]  92.7th
  OWGR Rank                    [███████████████████░]  97.5th

  — Finish Position —
  Avg Finish Last 3            [█████████████░░░░░░░]  67.5th
  Avg Finish Last 5            [██████████████░░░░░░]  70.9th
  Avg Finish Last 10           [███████████████████░]  93.9th
  Cut % Last Year              [█████████████████░░░]  86.3th
  Top 5% Last Year             [████████████████████]  98.9th
  Top 10% Last Year            [████████████████████]  98.5th
  Top 20% Last Year            [████████████████████]  97.6th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.7787
  Composite Pctile : 64.9th percentile
  Tier             : N/A

  Career Events    : 100
  Career Cuts Miss : 31  (31.0%)
  Career Avg Finish: 43.3

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: MAX HOMA
═════════════════════════════════════════════════════════════════
datagolf ranking: 90.0
 dg_rank
    90.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T13    -9        Cognizant Classic in The Pal   PGA National Resort
  2    2026   T37    -4        The Genesis Invitational       The Riviera Country
  3    2026   T66    0         WM Phoenix Open                TPC Scottsdale
  4    2026   CUT    1         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T27    -17       The American Express           PGA West
  6    2025   T9     -15       Black Desert Championship      Black Desert Resort
  7    2025   T40    -4        Baycurrent Classic             Yokohama Country Clu
  8    2025   T18    -13       Sanderson Farms Championship   The Country Club of
  9    2025   T19    -9        Procore Championship           Silverado Resort
  10   2025   CUT    1         Wyndham Championship           Sedgefield Country C
  11   2025   T39    -12       3M Open                        TPC Twin Cities
  12   2025   T5     -16       John Deere Classic             TPC Deere Run
  13   2025   CUT    -3        Rocket Mortgage Classic        Detroit Golf Club
  14   2025   T54    2         Travelers Championship         TPC River Highlands
  15   2025   CUT    -2        RBC Canadian Open              TPC Toronto at Ospre

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------

In [46]:
# ── Tier 5 ────────────────────────────────────────────────────────
players = [
    'Alex Noren',
    'Harry Hall',
    'J.J. Spaun',
    'Keith Mitchell', 
    'Michael Thorbjornsen', 
    'Nick Taylor',
    'Nico Echavarria',
    'Nicolai Højgaard', 
    'Ryan Gerard',
    'Patrick Rodgers',
    'Corey Conners',
    'J.T. Poston', 
    'Max Homa',
    'Wyndham Clark', 
    'Taylor Pendrith',
    'Sahith Theegala', 
]
# ──────────────────────────────────────────────────────────────────────────

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ALEX NOREN
═════════════════════════════════════════════════════════════════
datagolf ranking: 24.0
 dg_rank
    24.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T24    -2        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T12    -11       The Genesis Invitational       The Riviera Country
  3    2026   T29    -13       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   CUT    0         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   CUT    -7        The American Express           PGA West
  6    2025   CUT    -1        Black Desert Championship      Black Desert Resort
  7    2025   T27    -7        Baycurrent Classic             Yokohama Country Clu
  8    2025   T3     -15       Wyndham Championship           Sedgefield Country C
  9    2025   T7     -19       3M Open                        TPC Twin Cities
  10   2025   CUT    1         Genesis Scottish Open          The Renaissance Club
  11   2025   CUT    -3        Rocket Mortgage Classic        Detroit Golf Club
  12   2025   T30    -4        Travelers Championship         TPC River Highlands
  13   2025   CUT    -2        RBC Canadian Open              TPC Toronto at Ospre
  14   2025   T39    7         The Memorial Tournament        Muirfield Village Go
  15   2025   T17    -3        PGA Championship               Quail Hollow Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 21.67
  Last  5 starts : 45.0
  Last 10 starts : 42.2
  Last  3 starts : avg finish = 21.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    45.0     42.2
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     17       13           76.5      41.9         1       2       4
  2023     22       12           54.5      51.7         2       3       5
  2024     17       14           82.4      30.8         1       4       8
  2025     11       7            63.6      44.9         1       2       3
  2026     5        3            60.0      45.0         0       0       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  89.9th
  SG Last 3 Events             [███████████████████░]  97.4th
  SG Last 5 Events             [██████████████████░░]  90.5th
  SG Last 8 Events             [██████████████████░░]  91.5th
  SG Last 13 Events            [██████████████████░░]  90.0th
  SG Last 21 Events            [██████████████████░░]  91.9th
  DG Index                     [███████████████████░]  94.4th
  OWGR Rank                    [███████████████████░]  96.0th

  — Finish Position —
  Avg Finish Last 3            [████████████████████]  98.0th
  Avg Finish Last 5            [██████████████████░░]  89.9th
  Avg Finish Last 10           [██████████████████░░]  92.2th
  Cut % Last Year              [██████████████░░░░░░]  70.8th
  Top 5% Last Year             [███████████████████░]  95.5th
  Top 10% Last Year            [███████████████████░]  96.3th
  Top 20% Last Year            [███████████████████░]  93.8th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8640
  Composite Pctile : 84.9th percentile
  Tier             : N/A

  Career Events    : 72
  Career Cuts Miss : 23  (31.9%)
  Career Avg Finish: 42.9

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: HARRY HALL
═════════════════════════════════════════════════════════════════
datagolf ranking: 26.0
 dg_rank
    26.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T9     -8        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    2         The Genesis Invitational       The Riviera Country
  3    2026   CUT    5         WM Phoenix Open                TPC Scottsdale
  4    2026   T24    -14       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T24    -18       The American Express           PGA West
  6    2026   T6     -11       Sony Open in Hawaii            Waialae Country Club
  7    2025   T17    -9        TOUR Championship              East Lake Golf Club
  8    2025   6      -8        BMW Championship               Caves Valley Golf Cl
  9    2025   T22    -6        FedEx St. Jude Championship    TPC Southwind
  10   2025   T15    -11       Wyndham Championship           Sedgefield Country C
  11   2025   T28    -5        The Open Championship          Royal Portrush Golf
  12   2025   T17    -6        Genesis Scottish Open          The Renaissance Club
  13   2025   T13    -18       Rocket Mortgage Classic        Detroit Golf Club
  14   2025   T9     -9        Travelers Championship         TPC River Highlands
  15   2025   T24    -11       RBC Canadian Open              TPC Toronto at Ospre

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 56.33
  Last  5 starts : 43.4
  Last 10 starts : 28.3
  Last  3 starts : avg finish = 56.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    43.4     28.3
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        0
  Top 10 Finishes                  1        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     6        1            16.7      77.2         0       0       0
  2023     22       13           59.1      56.5         1       2       2
  2024     20       13           65.0      50.0         0       0       3
  2025     23       20           87.0      29.5         0       5       11
  2026     6        4            66.7      37.2         0       2       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████████████████]  98.5th
  SG Last 3 Events             [█████████████████░░░]  86.0th
  SG Last 5 Events             [███████████████████░]  93.9th
  SG Last 8 Events             [████████████████████]  97.7th
  SG Last 13 Events            [████████████████████]  99.0th
  SG Last 21 Events            [████████████████████]  99.4th
  DG Index                     [███████████████████░]  93.9th
  OWGR Rank                    [█████████████████░░░]  86.6th

  — Finish Position —
  Avg Finish Last 3            [████████████████░░░░]  80.9th
  Avg Finish Last 5            [██████████████████░░]  91.2th
  Avg Finish Last 10           [████████████████████]  97.7th
  Cut % Last Year              [█████████████████░░░]  85.8th
  Top 5% Last Year             [█████████░░░░░░░░░░░]  44.7th
  Top 10% Last Year            [███████████████████░]  97.1th
  Top 20% Last Year            [████████████████████]  97.8th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [█████████░░░░░░░░░░░]  45.8th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [████████████████████]  98.2th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8598
  Composite Pctile : 84.5th percentile
  Tier             : N/A

  Career Events    : 77
  Career Cuts Miss : 26  (33.8%)
  Career Avg Finish: 46.8

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: J.J. SPAUN
═════════════════════════════════════════════════════════════════
datagolf ranking: 31.0
 dg_rank
    31.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    3         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    4         The Genesis Invitational       The Riviera Country
  3    2026   T45    -10       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   CUT    0         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  6    2025   T11    -22       World Wide Technology Champi   El Cardonal at Diama
  7    2025   6      -15       Procore Championship           Silverado Resort
  8    2025   T25    -4        TOUR Championship              East Lake Golf Club
  9    2025   T23    1         BMW Championship               Caves Valley Golf Cl
  10   2025   2      -16       FedEx St. Jude Championship    TPC Southwind
  11   2025   T23    -6        The Open Championship          Royal Portrush Golf
  12   2025   CUT    2         Genesis Scottish Open          The Renaissance Club
  13   2025   T14    -7        Travelers Championship         TPC River Highlands
  14   2025   1      -1        U.S. Open                      Oakmont Country Club
  15   2025   CUT    6         The Memorial Tournament        Muirfield Village Go

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 68.33
  Last  5 starts : 65.0
  Last 10 starts : 39.2
  Last  3 starts : avg finish = 68.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    65.0     39.2
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     26       18           69.2      46.5         1       2       4
  2023     22       15           68.2      44.6         1       2       5
  2024     22       12           54.5      51.6         1       4       4
  2025     25       22           88.0      26.9         5       7       11
  2026     5        2            40.0      65.0         0       0       0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [███████████████░░░░░]  75.5th
  SG Last 5 Events             [████████████████░░░░]  79.3th
  SG Last 8 Events             [█████████████████░░░]  85.9th
  SG Last 13 Events            [██████████████████░░]  90.2th
  SG Last 21 Events            [███████████████████░]  93.4th
  DG Index                     [███████████████████░]  92.7th
  OWGR Rank                    [███████████████████░]  97.5th

  — Finish Position —
  Avg Finish Last 3            [█████████████░░░░░░░]  67.5th
  Avg Finish Last 5            [██████████████░░░░░░]  70.9th
  Avg Finish Last 10           [███████████████████░]  93.9th
  Cut % Last Year              [█████████████████░░░]  86.3th
  Top 5% Last Year             [████████████████████]  98.9th
  Top 10% Last Year            [████████████████████]  98.5th
  Top 20% Last Year            [████████████████████]  97.6th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.7787
  Composite Pctile : 64.9th percentile
  Tier             : N/A

  Career Events    : 100
  Career Cuts Miss : 31  (31.0%)
  Career Avg Finish: 43.3

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: KEITH MITCHELL
═════════════════════════════════════════════════════════════════
datagolf ranking: 57.0
 dg_rank
    57.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T33    -1        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T6     -11       Cognizant Classic in The Pal   PGA National Resort
  3    2026   T41    -5        WM Phoenix Open                TPC Scottsdale
  4    2026   T52    -8        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T11    -12       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T44    -15       The American Express           PGA West
  7    2026   T66    -1        Sony Open in Hawaii            Waialae Country Club
  8    2025   T18    -17       The RSM Classic                Sea Island Golf Club
  9    2025   T63    -9        World Wide Technology Champi   El Cardonal at Diama
  10   2025   T10    -11       Baycurrent Classic             Yokohama Country Clu
  11   2025   CUT    -3        Sanderson Farms Championship   The Country Club of
  12   2025   T53    -3        Procore Championship           Silverado Resort
  13   2025   CUT    -2        Wyndham Championship           Sedgefield Country C
  14   2025   CUT    -3        3M Open                        TPC Twin Cities
  15   2025   T50    -1        Genesis Scottish Open          The Renaissance Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 26.67
  Last  5 starts : 28.6
  Last 10 starts : 34.4
  Last  3 starts : avg finish = 26.67

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    28.6     34.4
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        0
  Top 10 Finishes                  1        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     19       16           84.2      37.6         0       5       7
  2023     22       16           72.7      45.6         2       3       4
  2024     24       16           66.7      41.1         1       4       12
  2025     23       17           73.9      44.5         0       2       5
  2026     7        7            100.0     36.1         0       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  88.3th
  SG Last 3 Events             [███████████████████░]  97.2th
  SG Last 5 Events             [████████████████████]  98.0th
  SG Last 8 Events             [███████████████████░]  95.5th
  SG Last 13 Events            [██████████████████░░]  88.9th
  SG Last 21 Events            [██████████████████░░]  90.0th
  DG Index                     [█████████████████░░░]  86.6th
  OWGR Rank                    [███████████████░░░░░]  72.9th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  96.8th
  Avg Finish Last 5            [███████████████████░]  97.2th
  Avg Finish Last 10           [███████████████████░]  95.6th
  Cut % Last Year              [████████████████░░░░]  79.1th
  Top 5% Last Year             [█████████░░░░░░░░░░░]  44.7th
  Top 10% Last Year            [██████████████████░░]  90.4th
  Top 20% Last Year            [██████████████████░░]  90.8th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [███████████████████░]  96.2th
  Top 5 Finishes (Last 10)     [█████████░░░░░░░░░░░]  45.8th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  96.9th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8462
  Composite Pctile : 79.9th percentile
  Tier             : N/A

  Career Events    : 95
  Career Cuts Miss : 23  (24.2%)
  Career Avg Finish: 41.9

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: MICHAEL THORBJORNSEN
═════════════════════════════════════════════════════════════════
datagolf ranking: 74.0
 dg_rank
    74.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T33    -1        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    1         Cognizant Classic in The Pal   PGA National Resort
  3    2026   T3     -15       WM Phoenix Open                TPC Scottsdale
  4    2026   T78    9         ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T18    -11       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   CUT    -7        The American Express           PGA West
  7    2025   T7     -18       The RSM Classic                Sea Island Golf Club
  8    2025   T31    -16       World Wide Technology Champi   El Cardonal at Diama
  9    2025   T37    -9        Black Desert Championship      Black Desert Resort
  10   2025   3      -16       Baycurrent Classic             Yokohama Country Clu
  11   2025   T29    -11       Sanderson Farms Championship   The Country Club of
  12   2025   T13    -10       Procore Championship           Silverado Resort
  13   2025   T38    -5        Wyndham Championship           Sedgefield Country C
  14   2025   CUT    3         3M Open                        TPC Twin Cities
  15   2025   T21    -13       John Deere Classic             TPC Deere Run

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------

In [47]:
# Build players list from a specific tier
tier = 6
players = tier_df[tier_df['Tier'] == tier]['player'].tolist()

for name in players:
    if merged_dataset[merged_dataset['player'].str.lower() == name.lower()].shape[0] > 0:
        golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ADAM SCHENK
═════════════════════════════════════════════════════════════════
datagolf ranking: 388.0
 dg_rank
   388.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T60    0         Cognizant Classic in The Pal   PGA National Resort
  2    2026   CUT    7         WM Phoenix Open                TPC Scottsdale
  3    2026   77     5         ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   T11    -12       Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   CUT    2         The American Express           PGA West
  6    2026   CUT    8         Sony Open in Hawaii            Waialae Country Club
  7    2025   CUT    2         The RSM Classic                Sea Island Golf Club
  8    2025   1      -12       Butterfield Bermuda Champion   Port Royal Golf Cour
  9    2025   T69    -8        World Wide Technology Champi   El Cardonal at Diama
  10   2025   T47    -7        Black Desert Championship      Black Desert Resort
  11   2025   T21    -12       Sanderson Farms Championship   The Country Club of
  12   2025   T30    -7        Procore Championship           Silverado Resort
  13   2025   CUT    4         Wyndham Championship           Sedgefield Country C
  14   2025   CUT    4         3M Open                        TPC Twin Cities
  15   2025   CUT    -3        John Deere Classic             TPC Deere Run

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 72.33
  Last  5 starts : 61.6
  Last 10 starts : 58.5
  Last  3 starts : avg finish = 72.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    61.6     58.5
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     30       14           46.7      61.1         0       1       2
  2023     27       18           66.7      44.0         3       7       9
  2024     28       16           57.1      56.1         1       1       5
  2025     24       12           50.0      56.7         2       3       3
  2026     6        3            50.0      64.7         0       0       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [█████████████████░░░]  85.7th
  SG Last 3 Events             [░░░░░░░░░░░░░░░░░░░░]  0.4th
  SG Last 5 Events             [████████████████░░░░]  78.0th
  SG Last 8 Events             [███████████████░░░░░]  77.4th
  SG Last 13 Events            [████████████████░░░░]  81.8th
  SG Last 21 Events            [████████████████░░░░]  79.5th
  DG Index                     [███░░░░░░░░░░░░░░░░░]  16.3th
  OWGR Rank                    [█████████████░░░░░░░]  66.6th

  — Finish Position —
  Avg Finish Last 3            [████████████░░░░░░░░]  62.0th
  Avg Finish Last 5            [███████████████░░░░░]  75.4th
  Avg Finish Last 10           [███████████████░░░░░]  77.3th
  Cut % Last Year              [████████████░░░░░░░░]  61.0th
  Top 5% Last Year             [███████████████████░]  94.8th
  Top 10% Last Year            [███████████████████░]  94.3th
  Top 20% Last Year            [█████████████████░░░]  87.2th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.6767
  Composite Pctile : 47.7th percentile
  Tier             : N/A

  Career Events    : 115
  Career Cuts Miss : 52  (45.2%)
  Career Avg Finish: 55.1

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ALDRICH POTGIETER
═════════════════════════════════════════════════════════════════
datagolf ranking: 226.0
 dg_rank
   226.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    11        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   5      -15       The Genesis Invitational       The Riviera Country
  3    2026   CUT    5         WM Phoenix Open                TPC Scottsdale
  4    2026   T60    -5        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   CUT    2         Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   CUT    -6        The American Express           PGA West
  7    2025   W/D    0         Black Desert Championship      Black Desert Resort
  8    2025   T33    -6        Baycurrent Classic             Yokohama Country Clu
  9    2025   T59    3         FedEx St. Jude Championship    TPC Southwind
  10   2025   CUT    5         The Open Championship          Royal Portrush Golf
  11   2025   CUT    2         Genesis Scottish Open          The Renaissance Club
  12   2025   1      -22       Rocket Mortgage Classic        Detroit Golf Club
  13   2025   T6     -7        Charles Schwab Challenge       Colonial Country Clu
  14   2025   CUT    0         THE CJ CUP Byron Nelson        TPC Craig Ranch
  15   2025   T47    3         Valero Texas Open              TPC San Antonio

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 55.0
  Last  5 starts : 61.0
  Last 10 starts : 63.7
  Last  3 starts : avg finish = 55.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    61.0     63.7
  Top 3 Finishes                   0        0
  Top 5 Finishes                   1        1
  Top 10 Finishes                  1        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2023     1        0            0.0       80.0         0       0       0
  2025     17       8            47.1      55.2         2       3       4
  2026     6        2            33.3      64.2         1       1       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [██████████████████░░]  88.1th
  SG Last 5 Events             [████████████████░░░░]  81.7th
  SG Last 8 Events             [███████████████░░░░░]  73.1th
  SG Last 13 Events            [████████████████░░░░]  82.0th
  SG Last 21 Events            [█████████████████░░░]  82.6th
  DG Index                     [█████████░░░░░░░░░░░]  47.1th
  OWGR Rank                    [█████████████████░░░]  83.0th

  — Finish Position —
  Avg Finish Last 3            [█████████████████░░░]  83.2th
  Avg Finish Last 5            [███████████████░░░░░]  76.0th
  Avg Finish Last 10           [██████████████░░░░░░]  71.6th
  Cut % Last Year              [████████████░░░░░░░░]  58.3th
  Top 5% Last Year             [███████████████████░]  97.4th
  Top 10% Last Year            [███████████████████░]  96.5th
  Top 20% Last Year            [███████████████████░]  92.9th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [████████████████░░░░]  81.4th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8083
  Composite Pctile : 71.5th percentile
  Tier             : N/A

  Career Events    : 24
  Career Cuts Miss : 14  (58.3%)
  Career Avg Finish: 58.6

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ALEX SMALLEY
═════════════════════════════════════════════════════════════════
datagolf ranking: 89.0
 dg_rank
    89.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T52    -3        Cognizant Classic in The Pal   PGA National Resort
  2    2026   T35    -6        WM Phoenix Open                TPC Scottsdale
  3    2026   T19    -15       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   CUT    2         Farmers Insurance Open         Torrey Pines Golf Co
  5    2026   T44    -15       The American Express           PGA West
  6    2026   T40    -5        Sony Open in Hawaii            Waialae Country Club
  7    2025   T62    -10       The RSM Classic                Sea Island Golf Club
  8    2025   T3     -10       Butterfield Bermuda Champion   Port Royal Golf Cour
  9    2025   CUT    3         Black Desert Championship      Black Desert Resort
  10   2025   T4     -14       Baycurrent Classic             Yokohama Country Clu
  11   2025   CUT    5         Sanderson Farms Championship   The Country Club of
  12   2025   CUT    4         Procore Championship           Silverado Resort
  13   2025   CUT    -1        Wyndham Championship           Sedgefield Country C
  14   2025   T44    -11       3M Open                        TPC Twin Cities
  15   2025   T34    -4        Genesis Scottish Open          The Renaissance Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 35.33
  Last  5 starts : 46.0
  Last 10 starts : 41.9
  Last  3 starts : avg finish = 35.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    46.0     41.9
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        2
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     27       17           63.0      47.5         1       3       7
  2023     25       16           64.0      47.8         2       3       5
  2024     23       8            34.8      61.1         1       1       3
  2025     25       14           56.0      47.9         2       3       8
  2026     6        5            83.3      45.0         0       0       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  88.8th
  SG Last 3 Events             [███████████████████░]  96.2th
  SG Last 5 Events             [███████████████████░]  96.2th
  SG Last 8 Events             [███████████████████░]  93.1th
  SG Last 13 Events            [████████████████░░░░]  82.0th
  SG Last 21 Events            [██████████████████░░]  87.7th
  DG Index                     [████████████████░░░░]  79.4th
  OWGR Rank                    [██████████████░░░░░░]  71.1th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  93.9th
  Avg Finish Last 5            [██████████████████░░]  89.4th
  Avg Finish Last 10           [██████████████████░░]  92.3th
  Cut % Last Year              [█████████████░░░░░░░]  66.3th
  Top 5% Last Year             [███████████████████░]  94.0th
  Top 10% Last Year            [███████████████████░]  93.6th
  Top 20% Last Year            [███████████████████░]  95.0th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8365
  Composite Pctile : 76.6th percentile
  Tier             : N/A

  Career Events    : 106
  Career Cuts Miss : 46  (43.4%)
  Career Avg Finish: 50.4

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ANDREW NOVAK
═════════════════════════════════════════════════════════════════
datagolf ranking: 98.0
 dg_rank
    98.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T38    0         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T47    0         The Genesis Invitational       The Riviera Country
  3    2026   CUT    7         WM Phoenix Open                TPC Scottsdale
  4    2026   T48    -9        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T7     -14       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   CUT    -10       The American Express           PGA West
  7    2025   T7     -18       The RSM Classic                Sea Island Golf Club
  8    2025   T25    -4        TOUR Championship              East Lake Golf Club
  9    2025   48     20        BMW Championship               Caves Valley Golf Cl
  10   2025   T6     -10       FedEx St. Jude Championship    TPC Southwind
  11   2025   CUT    0         Wyndham Championship           Sedgefield Country C
  12   2025   T63    4         The Open Championship          Royal Portrush Golf
  13   2025   T13    -7        Genesis Scottish Open          The Renaissance Club
  14   2025   T30    -4        Travelers Championship         TPC River Highlands
  15   2025   T42    12        U.S. Open                      Oakmont Country Club

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 55.0
  Last  5 starts : 44.0
  Last 10 starts : 38.6
  Last  3 starts : avg finish = 55.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    44.0     38.6
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        0
  Top 10 Finishes                  1        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     19       8            42.1      64.3         0       0       2
  2023     21       14           66.7      53.1         0       2       3
  2024     23       18           78.3      38.5         1       5       9
  2025     26       18           69.2      40.9         3       5       10
  2026     6        4            66.7      50.0         0       1       1

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [█████████████████░░░]  87.3th
  SG Last 3 Events             [████████████████░░░░]  78.9th
  SG Last 5 Events             [██████████████████░░]  91.8th
  SG Last 8 Events             [█████████████████░░░]  85.5th
  SG Last 13 Events            [█████████████████░░░]  86.8th
  SG Last 21 Events            [███████████████████░]  93.8th
  DG Index                     [███████████████░░░░░]  77.2th
  OWGR Rank                    [██████████████████░░]  88.6th

  — Finish Position —
  Avg Finish Last 3            [█████████████████░░░]  83.2th
  Avg Finish Last 5            [██████████████████░░]  90.9th
  Avg Finish Last 10           [███████████████████░]  94.2th
  Cut % Last Year              [███████████████░░░░░]  75.2th
  Top 5% Last Year             [███████████████████░]  96.9th
  Top 10% Last Year            [███████████████████░]  96.5th
  Top 20% Last Year            [███████████████████░]  96.7th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [███████████████████░]  95.0th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [█████████░░░░░░░░░░░]  45.8th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8387
  Composite Pctile : 77.4th percentile
  Tier             : N/A

  Career Events    : 95
  Career Cuts Miss : 33  (34.7%)
  Career Avg Finish: 48.4

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: ANDREW PUTNAM
═════════════════════════════════════════════════════════════════
datagolf ranking: 153.0
 dg_rank
   153.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T44    2         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   CUT    3         Cognizant Classic in The Pal   PGA National Resort
  3    2026   CUT    3         Farmers Insurance Open         Torrey Pines Golf Co
  4    2026   T2     -23       The American Express           PGA West
  5    2025   T25    -15       The RSM Classic                Sea Island Golf Club
  6    2025   T67    7         Butterfield Bermuda Champion   Port Royal Golf Cour
  7    2025   T40    -15       World Wide Technology Champi   El Cardonal at Diama
  8    2025   CUT    3         Black Desert Championship      Black Desert Resort
  9    2025   T65    4         Baycurrent Classic             Yokohama Country Clu
  10   2025   CUT    -1        Sanderson Farms Championship   The Country Club of
  11   2025   CUT    0         Procore Championship           Silverado Resort
  12   2025   CUT    -2        Wyndham Championship           Sedgefield Country C
  13   2025   CUT    -4        3M Open                        TPC Twin Cities
  14   2025   CUT    0         Genesis Scottish Open          The Renaissance Club
  15   2025   W/D    0         John Deere Classic             TPC Deere Run

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 68.0
  Last  5 starts : 46.2
  Last 10 starts : 56.3
  Last  3 starts : avg finish = 68.0

  Metric                      Last 5  Last 10

In [48]:
# ── Tier 6 ────────────────────────────────────────────────────────
players = [
    'Ryo Hisatsune',
    'Matt McCarty',
    
    'Aaron Rai',
    'Rico Hoey', 
    'Max McGreevy',
     
    'Ryan Fox',
    'Sam Stevens',
    'Daniel Berger', 
    'Andrew Novak',
    'Lucas Glover',
    'Tom Hoge', 
    'Max Greyserman', 
    'Michael Kim', 
    'Denny McCarthy', 
    'Brian Harman',
    'Tony Finau',
   
]
# ──────────────────────────────────────────────────────────────────────────

for name in players:
    golfer_profile(player_name=name, last_n_finishes=15)

═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: RYO HISATSUNE
═════════════════════════════════════════════════════════════════
datagolf ranking: 87.0
 dg_rank
    87.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T33    -1        Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T45    -1        The Genesis Invitational       The Riviera Country
  3    2026   T10    -12       WM Phoenix Open                TPC Scottsdale
  4    2026   T8     -18       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T2     -16       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T44    -15       The American Express           PGA West
  7    2026   CUT    0         Sony Open in Hawaii            Waialae Country Club
  8    2025   CUT    -2        The RSM Classic                Sea Island Golf Club
  9    2025   T52    2         Butterfield Bermuda Champion   Port Royal Golf Cour
  10   2025   T40    -15       World Wide Technology Champi   El Cardonal at Diama
  11   2025   CUT    2         Black Desert Championship      Black Desert Resort
  12   2025   T72    7         Baycurrent Classic             Yokohama Country Clu
  13   2025   T48    -8        Sanderson Farms Championship   The Country Club of
  14   2025   T13    -10       Procore Championship           Silverado Resort
  15   2025   CUT    7         Wyndham Championship           Sedgefield Country C

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 29.33
  Last  5 starts : 19.6
  Last 10 starts : 39.4
  Last  3 starts : avg finish = 29.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    19.6     39.4
  Top 3 Finishes                   1        1
  Top 5 Finishes                   1        1
  Top 10 Finishes                  3        3

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     1        1            100.0     12.0         0       0       1
  2023     1        1            100.0     6.0          0       1       1
  2024     24       16           66.7      47.6         1       1       5
  2025     27       17           63.0      52.9         2       4       6
  2026     7        6            85.7      31.7         1       3       3

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [██████████████████░░]  88.3th
  SG Last 3 Events             [███████████████████░]  95.0th
  SG Last 5 Events             [████████████████████]  99.4th
  SG Last 8 Events             [███████████████████░]  97.0th
  SG Last 13 Events            [██████████████████░░]  90.8th
  SG Last 21 Events            [██████████████████░░]  90.9th
  DG Index                     [████████████████░░░░]  79.8th
  OWGR Rank                    [█████████████████░░░]  84.6th

  — Finish Position —
  Avg Finish Last 3            [███████████████████░]  96.0th
  Avg Finish Last 5            [████████████████████]  99.0th
  Avg Finish Last 10           [███████████████████░]  93.7th
  Cut % Last Year              [██████████████░░░░░░]  70.3th
  Top 5% Last Year             [███████████████████░]  93.4th
  Top 10% Last Year            [███████████████████░]  95.2th
  Top 20% Last Year            [██████████████████░░]  91.0th
  Top 5 Finishes (Last 5)      [████████████████████]  97.6th
  Top 10 Finishes (Last 5)     [████████████████████]  99.6th
  Top 20 Finishes (Last 5)     [████████████████████]  98.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [████████████████████]  98.0th
  Top 20 Finishes(Last 10)     [███████████████████░]  94.8th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.9225
  Composite Pctile : 90.4th percentile
  Tier             : N/A

  Career Events    : 60
  Career Cuts Miss : 19  (31.7%)
  Career Avg Finish: 46.8

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: MATT MCCARTY
═════════════════════════════════════════════════════════════════
datagolf ranking: 50.0
 dg_rank
    50.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T41    1         Arnold Palmer Invitational     Arnold Palmer's Bay
  2    2026   T24    -7        The Genesis Invitational       The Riviera Country
  3    2026   CUT    2         WM Phoenix Open                TPC Scottsdale
  4    2026   T67    -3        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T18    -11       Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T2     -23       The American Express           PGA West
  7    2026   T55    -3        Sony Open in Hawaii            Waialae Country Club
  8    2025   T3     -16       Black Desert Championship      Black Desert Resort
  9    2025   T14    -10       Baycurrent Classic             Yokohama Country Clu
  10   2025   T43    -5        Procore Championship           Silverado Resort
  11   2025   T8     -13       Wyndham Championship           Sedgefield Country C
  12   2025   T68    -7        3M Open                        TPC Twin Cities
  13   2025   CUT    3         The Open Championship          Royal Portrush Golf
  14   2025   T22    -5        Genesis Scottish Open          The Renaissance Club
  15   2025   CUT    -3        John Deere Classic             TPC Deere Run

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 48.33
  Last  5 starts : 46.0
  Last 10 starts : 34.7
  Last  3 starts : avg finish = 48.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    46.0     34.7
  Top 3 Finishes                   0        2
  Top 5 Finishes                   0        2
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     1        0            0.0       80.0         0       0       0
  2024     3        2            66.7      48.0         1       1       1
  2025     25       17           68.0      46.7         2       3       9
  2026     7        6            85.7      41.0         1       1       2

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [█████████████████░░░]  86.3th
  SG Last 3 Events             [█████████████████░░░]  86.5th
  SG Last 5 Events             [██████████████████░░]  89.8th
  SG Last 8 Events             [███████████████████░]  96.7th
  SG Last 13 Events            [███████████████████░]  96.0th
  SG Last 21 Events            [███████████████████░]  95.5th
  DG Index                     [██████████████████░░]  88.3th
  OWGR Rank                    [██████████████████░░]  89.6th

  — Finish Position —
  Avg Finish Last 3            [██████████████████░░]  87.8th
  Avg Finish Last 5            [██████████████████░░]  89.4th
  Avg Finish Last 10           [███████████████████░]  95.5th
  Cut % Last Year              [███████████████░░░░░]  74.2th
  Top 5% Last Year             [███████████████████░]  94.0th
  Top 10% Last Year            [███████████████████░]  93.6th
  Top 20% Last Year            [███████████████████░]  96.4th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [██████████████████░░]  88.8th
  Top 5 Finishes (Last 10)     [████████████████████]  98.5th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [███████████████████░]  96.9th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8542
  Composite Pctile : 83.7th percentile
  Tier             : N/A

  Career Events    : 36
  Career Cuts Miss : 11  (30.6%)
  Career Avg Finish: 46.6

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: AARON RAI
═════════════════════════════════════════════════════════════════
datagolf ranking: 63.0
 dg_rank
    63.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T23    -7        Cognizant Classic in The Pal   PGA National Resort
  2    2026   T28    -6        The Genesis Invitational       The Riviera Country
  3    2026   T73    1         ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  4    2026   T50    -4        Sony Open in Hawaii            Waialae Country Club
  5    2025   T22    -6        FedEx St. Jude Championship    TPC Southwind
  6    2025   T5     -14       Wyndham Championship           Sedgefield Country C
  7    2025   T34    -3        The Open Championship          Royal Portrush Golf
  8    2025   T47    -2        Genesis Scottish Open          The Renaissance Club
  9    2025   T17    -6        Travelers Championship         TPC River Highlands
  10   2025   T33    9         U.S. Open                      Oakmont Country Club
  11   2025   CUT    9         The Memorial Tournament        Muirfield Village Go
  12   2025   CUT    1         Charles Schwab Challenge       Colonial Country Clu
  13   2025   T19    -2        PGA Championship               Quail Hollow Club
  14   2025   T23    -6        Truist Championship            The Philadelphia Cri
  15   2025   T38    -6        RBC Heritage                   Harbour Town Golf Li

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 41.33
  Last  5 starts : 39.2
  Last 10 starts : 33.2
  Last  3 starts : avg finish = 41.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    39.2     33.2
  Top 3 Finishes                   0        0
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        1

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2022     23       17           73.9      52.6         0       1       3
  2023     24       16           66.7      46.5         1       3       6
  2024     21       18           85.7      31.1         4       6       10
  2025     20       16           80.0      35.3         2       2       7
  2026     4        4            100.0     43.5         0       0       0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [███████████████████░]  95.5th
  SG Last 3 Events             [██████████████████░░]  88.6th
  SG Last 5 Events             [██████████████████░░]  92.2th
  SG Last 8 Events             [███████████████████░]  95.1th
  SG Last 13 Events            [███████████████████░]  95.5th
  SG Last 21 Events            [███████████████████░]  96.5th
  DG Index                     [█████████████████░░░]  85.6th
  OWGR Rank                    [██████████████████░░]  91.6th

  — Finish Position —
  Avg Finish Last 3            [██████████████████░░]  91.8th
  Avg Finish Last 5            [███████████████████░]  94.4th
  Avg Finish Last 10           [███████████████████░]  96.2th
  Cut % Last Year              [█████████████████░░░]  82.7th
  Top 5% Last Year             [███████████████████░]  96.2th
  Top 10% Last Year            [██████████████████░░]  92.5th
  Top 20% Last Year            [███████████████████░]  96.0th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [██████████████████░░]  90.1th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.8463
  Composite Pctile : 80.3th percentile
  Tier             : N/A

  Career Events    : 92
  Career Cuts Miss : 21  (22.8%)
  Career Avg Finish: 42.0

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: RICO HOEY
═════════════════════════════════════════════════════════════════
datagolf ranking: 137.0
 dg_rank
   137.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   CUT    8         Cognizant Classic in The Pal   PGA National Resort
  2    2026   CUT    2         The Genesis Invitational       The Riviera Country
  3    2026   T24    -8        WM Phoenix Open                TPC Scottsdale
  4    2026   T67    -3        ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T70    2         Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   W/D    5         The American Express           PGA West
  7    2026   T50    -4        Sony Open in Hawaii            Waialae Country Club
  8    2025   T7     -18       The RSM Classic                Sea Island Golf Club
  9    2025   T22    -3        Butterfield Bermuda Champion   Port Royal Golf Cour
  10   2025   T21    -18       World Wide Technology Champi   El Cardonal at Diama
  11   2025   2      -18       Black Desert Championship      Black Desert Resort
  12   2025   T4     -14       Baycurrent Classic             Yokohama Country Clu
  13   2025   CUT    1         Sanderson Farms Championship   The Country Club of
  14   2025   T9     -12       Procore Championship           Silverado Resort
  15   2025   T67    0         Wyndham Championship           Sedgefield Country C

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 61.33
  Last  5 starts : 64.2
  Last 10 starts : 42.3
  Last  3 starts : avg finish = 61.33

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    64.2     42.3
  Top 3 Finishes                   0        1
  Top 5 Finishes                   0        1
  Top 10 Finishes                  0        2

  Year     Events   Cuts Made    Cut %     Avg Finish   Top 5   Top 10  Top 20
  ------------------------------------------------------------
  2025     19       14           73.7      42.0         2       4       6
  2026     7        5            71.4      61.8         0       0       0

📈  STROKES GAINED PERCENTILE RANKINGS  (vs. field with 5+ events)
-----------------------------------------------------------------

  Metric                       Percentile Bar
  -------------------------------------------------------
  — Strokes Gained —
  SG Last 1 Event              [████████░░░░░░░░░░░░]  42.3th
  SG Last 3 Events             [█████████████████░░░]  83.2th
  SG Last 5 Events             [████████████████░░░░]  77.6th
  SG Last 8 Events             [██████████████████░░]  87.9th
  SG Last 13 Events            [█████████████████░░░]  84.6th
  SG Last 21 Events            [██████████████████░░]  88.9th
  DG Index                     [██████████████░░░░░░]  67.6th
  OWGR Rank                    [████████████████░░░░]  80.8th

  — Finish Position —
  Avg Finish Last 3            [███████████████░░░░░]  75.1th
  Avg Finish Last 5            [██████████████░░░░░░]  72.5th
  Avg Finish Last 10           [██████████████████░░]  92.1th
  Cut % Last Year              [████████████████░░░░]  78.7th
  Top 5% Last Year             [███████████████████░]  96.5th
  Top 10% Last Year            [███████████████████░]  97.0th
  Top 20% Last Year            [███████████████████░]  94.7th
  Top 5 Finishes (Last 5)      [██████████░░░░░░░░░░]  47.9th
  Top 10 Finishes (Last 5)     [█████████░░░░░░░░░░░]  46.1th
  Top 20 Finishes (Last 5)     [████████░░░░░░░░░░░░]  41.5th
  Top 5 Finishes (Last 10)     [███████████████████░]  94.6th
  Top 10 Finishes(Last 10)     [███████████████████░]  95.5th
  Top 20 Finishes(Last 10)     [██████████████████░░]  90.3th

🎯  COMPOSITE SCORE SUMMARY
-----------------------------------------------------------------
  Composite Score  : 0.7455
  Composite Pctile : 57.3th percentile
  Tier             : N/A

  Career Events    : 26
  Career Cuts Miss : 7  (26.9%)
  Career Avg Finish: 46.8

═════════════════════════════════════════════════════════════════


═════════════════════════════════════════════════════════════════
  🏌️  GOLFER PROFILE: MAX MCGREEVY
═════════════════════════════════════════════════════════════════
datagolf ranking: 66.0
 dg_rank
    66.0

📋  LAST 15 FINISHES
-----------------------------------------------------------------
  #    Year   Pos    To Par    Tournament                     Course
  --------------------------------------------------------------
  1    2026   T40    -4        Cognizant Classic in The Pal   PGA National Resort
  2    2026   CUT    1         The Genesis Invitational       The Riviera Country
  3    2026   T48    -4        WM Phoenix Open                TPC Scottsdale
  4    2026   T29    -13       ATT Pebble Beach Pro-Am        Pebble Beach Golf Li
  5    2026   T30    -8        Farmers Insurance Open         Torrey Pines Golf Co
  6    2026   T27    -17       The American Express           PGA West
  7    2026   CUT    1         Sony Open in Hawaii            Waialae Country Club
  8    2025   2      -22       The RSM Classic                Sea Island Golf Club
  9    2025   T3     -10       Butterfield Bermuda Champion   Port Royal Golf Cour
  10   2025   T56    -12       World Wide Technology Champi   El Cardonal at Diama
  11   2025   T11    -14       Black Desert Championship      Black Desert Resort
  12   2025   T33    -6        Baycurrent Classic             Yokohama Country Clu
  13   2025   CUT    -3        Sanderson Farms Championship   The Country Club of
  14   2025   CUT    5         Procore Championship           Silverado Resort
  15   2025   T34    -6        Wyndham Championship           Sedgefield Country C

📊  AVERAGE FINISH POSITION
-----------------------------------------------------------------
  Last  3 starts : 56.0
  Last  5 starts : 45.4
  Last 10 starts : 39.5
  Last  3 starts : avg finish = 56.0

  Metric                      Last 5  Last 10
  ------------------------------------------
  Avg Finish                    45.4     39.5
  Top 3 Finishes                   0        2

In [49]:
# Need to create a program that prints out the predicted score for the tie breaker for each round

In [50]:
# ------------------------------------------------------------------------------------------------------
# Want to post the golfer metrics to the db 
# ------------------------------------------------------------------------------------------------------

import psycopg2
from psycopg2.extras import execute_values
import pandas as pd
import numpy as np

# ── Config ─────────────────────────────────────────────────────────────────
TABLE_NAME   = 'combined_data'           # change if desired
SCHEMA       = schema                     # already defined as os.getenv('DB_SCHEMA')
FULL_TABLE   = f'{SCHEMA}.{TABLE_NAME}'
IF_EXISTS    = 'replace'                  # 'replace' drops & recreates | 'append' adds rows

# ── 1. Clean the dataframe before writing ──────────────────────────────────
df_out = merged_dataset.copy()

# Replace NaN/inf with None so psycopg2 writes proper NULLs
df_out = df_out.replace([np.inf, -np.inf], np.nan)

for col in df_out.columns:
    if pd.api.types.is_datetime64_any_dtype(df_out[col]):
        df_out[col] = df_out[col].astype(object).where(df_out[col].notna(), None)

df_out = df_out.where(pd.notnull(df_out), None)

In [51]:
# ── 2. Build CREATE TABLE statement from dtypes ────────────────────────────
def pg_dtype(series):
    if pd.api.types.is_datetime64_any_dtype(series):
        return 'TIMESTAMP'
    elif pd.api.types.is_integer_dtype(series):
        return 'BIGINT'
    elif pd.api.types.is_float_dtype(series):
        return 'DOUBLE PRECISION'
    elif pd.api.types.is_bool_dtype(series):
        return 'BOOLEAN'
    else:
        return 'TEXT'

col_defs = ',\n    '.join(
    f'"{col}" {pg_dtype(df_out[col])}' for col in df_out.columns
)

In [52]:
# ── 3. Write to Postgres ───────────────────────────────────────────────────
conn = psycopg2.connect(**db_config)
cur  = conn.cursor()

try:
    if IF_EXISTS == 'replace':
        cur.execute(f'DROP TABLE IF EXISTS {FULL_TABLE};')
        cur.execute(f'CREATE TABLE {FULL_TABLE} (\n    {col_defs}\n);')
        print(f'✅ Table {FULL_TABLE} (re)created — {len(df_out.columns)} columns')

    elif IF_EXISTS == 'append':
        # Table must already exist with matching columns
        pass

    # Batch insert using execute_values for speed
    cols        = [f'"{c}"' for c in df_out.columns]
    col_str     = ', '.join(cols)
    rows        = [tuple(row) for row in df_out.itertuples(index=False, name=None)]

    execute_values(
        cur,
        f'INSERT INTO {FULL_TABLE} ({col_str}) VALUES %s',
        rows,
        page_size=500
    )

    conn.commit()
    print(f'✅ {len(rows):,} rows written to {FULL_TABLE}')

except Exception as e:
    conn.rollback()
    print(f'❌ Write failed: {e}')
    raise

finally:
    cur.close()
    conn.close()

✅ Table pga_stats.combined_data (re)created — 76 columns
✅ 239 rows written to pga_stats.combined_data

In [53]:
results = analyze_tournament(df, "The Genesis Invitational")

NameError: name 'analyze_tournament' is not defined

In [ ]:
'''
Model improvement ideas:
- Pull in historical finishing position for the current event; add it as a metric 
- are there other metrics that could be pulled in; driving accurary; breaking out SGs 
- Fix Ludgid Aberg's name 

'''

In [ ]:
'''
Next Steps: DONE 8-7-25 
- create a new column that combines all of the percentile ranks into a single score 
- ask AI what makes the most sense 
- figure out how to use golfer tiers to find the best value; what will the form look like? 

'''

In [ ]:
'''
# Ensure year and week_of_season are integers (no decimals)
df['year'] = df['year'].astype(int)
df['week_of_season'] = df['week_of_season'].astype(int)

# Create synthetic event date
df['event_date'] = pd.to_datetime(df['year'].astype(str) + df['week_of_season'].astype(str) + '1', format='%G%V%u')

# Sort by golfer and event order
df = df.sort_values(['player', 'event_date'])

# Rolling averages
df['SG_last_3'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(3, min_periods=1).mean())
df['SG_last_6'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(6, min_periods=1).mean())
df['SG_last_10'] = df.groupby('player')['updated_avg'].transform(lambda x: x.rolling(10, min_periods=1).mean())

# Get latest event per golfer
latest = df.groupby('player').tail(1)

# Select desired output
output_df = latest[['player', 'SG_last_3', 'SG_last_6', 'SG_last_10']]
'''

In [ ]:
'''
# Sort descending (best performers at top)
output_df = output_df.sort_values(by='SG_last_3', ascending=False)
print(output_df)
'''